const Emojis = {
	url: 'https://twemoji.maxcdn.com/2/svg/',
	textToEmoji: {} as { [key: string]: string },
	emojis: {
		":O": { text: "open_mouth" },
		":D": { text: "grinning" },
		"<3": { text: "heart" },
		":)": { text: "smile" },
		":/": { text: "confused" },
		";)": { text: "wink" },
		":(": { text: "frowning" },
		":P": { text: "stuck_out_tongue" },
		"(lama)": { text: "lama" },
		":B": { text: "grimacing" },
		"(lucky)": { text: "clover" },
		"0⃣": { text: "zero", image: "30-20e3" },
		"1⃣": { text: "one", image: "31-20e3" },
		"2⃣": { text: "two", image: "32-20e3" },
		"3⃣": { text: "three", image: "33-20e3" },
		"4⃣": { text: "four", image: "34-20e3" },
		"5⃣": { text: "five", image: "35-20e3" },
		"6⃣": { text: "six", image: "36-20e3" },
		"7⃣": { text: "seven", image: "37-20e3" },
		"8⃣": { text: "eight", image: "38-20e3" },
		"9⃣": { text: "nine", image: "39-20e3" },
		"#⃣": { text: "hash", image: "23-20e3" },
		"©": { text: "copyright", image: "a9" },
		"®": { text: "registered", image: "ae" },
		"‼": { text: "bangbang", image: "203c" },
		"⁉": { text: "interrobang", image: "2049" },
		"™": { text: "tm", image: "2122" },
		"ℹ": { text: "information_source", image: "2139" },
		"↔": { text: "left_right_arrow", image: "2194" },
		"↕": { text: "arrow_up_down", image: "2195" },
		"↖": { text: "arrow_upper_left", image: "2196" },
		"↗": { text: "arrow_upper_right", image: "2197" },
		"↘": { text: "arrow_lower_right", image: "2198" },
		"↙": { text: "arrow_lower_left", image: "2199" },
		"↩": { text: "leftwards_arrow_with_hook", image: "21a9" },
		"↪": { text: "arrow_right_hook", image: "21aa" },
		"⌚": { text: "watch", image: "231a" },
		"⌛": { text: "hourglass", image: "231b" },
		"⏩": { text: "fast_forward", image: "23e9" },
		"⏪": { text: "rewind", image: "23ea" },
		"⏫": { text: "arrow_double_up", image: "23eb" },
		"⏬": { text: "arrow_double_down", image: "23ec" },
		"⏰": { text: "alarm_clock", image: "23f0" },
		"⏳": { text: "hourglass_flowing_sand", image: "23f3" },
		"Ⓜ": { text: "m", image: "24c2" },
		"▪": { text: "black_small_square", image: "25aa" },
		"▫": { text: "white_small_square", image: "25ab" },
		"▶": { text: "arrow_forward", image: "25b6" },
		"◀": { text: "arrow_backward", image: "25c0" },
		"◻": { text: "white_medium_square", image: "25fb" },
		"◼": { text: "black_medium_square", image: "25fc" },
		"◽": { text: "white_medium_small_square", image: "25fd" },
		"◾": { text: "black_medium_small_square", image: "25fe" },
		"☀": { text: "sunny", image: "2600" },
		"☁": { text: "cloud", image: "2601" },
		"☎": { text: "telephone", image: "260e" },
		"☑": { text: "ballot_box_with_check", image: "2611" },
		"☔": { text: "umbrella", image: "2614" },
		"☕": { text: "coffee", image: "2615" },
		"☝": { text: "point_up", image: "261d" },
		"☺": { text: "relaxed", image: "263a" },
		"♈": { text: "aries", image: "2648" },
		"♉": { text: "taurus", image: "2649" },
		"♊": { text: "gemini", image: "264a" },
		"♋": { text: "cancer", image: "264b" },
		"♌": { text: "leo", image: "264c" },
		"♍": { text: "virgo", image: "264d" },
		"♎": { text: "libra", image: "264e" },
		"♏": { text: "scorpius", image: "264f" },
		"♐": { text: "sagittarius", image: "2650" },
		"♑": { text: "capricorn", image: "2651" },
		"♒": { text: "aquarius", image: "2652" },
		"♓": { text: "pisces", image: "2653" },
		"♠": { text: "spades", image: "2660" },
		"♣": { text: "clubs", image: "2663" },
		"♥": { text: "hearts", image: "2665" },
		"♦": { text: "diamonds", image: "2666" },
		"♨": { text: "hotsprings", image: "2668" },
		"♻": { text: "recycle", image: "267b" },
		"♿": { text: "wheelchair", image: "267f" },
		"⚓": { text: "anchor", image: "2693" },
		"⚠": { text: "warning", image: "26a0" },
		"⚡": { text: "zap", image: "26a1" },
		"⚪": { text: "white_circle", image: "26aa" },
		"⚫": { text: "black_circle", image: "26ab" },
		"⚽": { text: "soccer", image: "26bd" },
		"⚾": { text: "baseball", image: "26be" },
		"⛄": { text: "snowman", image: "26c4" },
		"⛅": { text: "partly_sunny", image: "26c5" },
		"⛎": { text: "ophiuchus", image: "26ce" },
		"⛔": { text: "no_entry", image: "26d4" },
		"⛪": { text: "church", image: "26ea" },
		"⛲": { text: "fountain", image: "26f2" },
		"⛳": { text: "golf", image: "26f3" },
		"⛵": { text: "sailboat", image: "26f5" },
		"⛺": { text: "tent", image: "26fa" },
		"⛽": { text: "fuelpump", image: "26fd" },
		"✂": { text: "scissors", image: "2702" },
		"✅": { text: "white_check_mark", image: "2705" },
		"✈": { text: "airplane", image: "2708" },
		"✉": { text: "envelope", image: "2709" },
		"✊": { text: "fist", image: "270a" },
		"✋": { text: "raised_hand", image: "270b" },
		"✌": { text: "v", image: "270c" },
		"✏": { text: "pencil2", image: "270f" },
		"✒": { text: "black_nib", image: "2712" },
		"✔": { text: "heavy_check_mark", image: "2714" },
		"✖": { text: "heavy_multiplication_x", image: "2716" },
		"✨": { text: "sparkles", image: "2728" },
		"✳": { text: "eight_spoked_asterisk", image: "2733" },
		"✴": { text: "eight_pointed_black_star", image: "2734" },
		"❄": { text: "snowflake", image: "2744" },
		"❇": { text: "sparkle", image: "2747" },
		"❌": { text: "x", image: "274c" },
		"❎": { text: "negative_squared_cross_mark", image: "274e" },
		"❓": { text: "question", image: "2753" },
		"❔": { text: "grey_question", image: "2754" },
		"❕": { text: "grey_exclamation", image: "2755" },
		"❗": { text: "exclamation", image: "2757" },
		"❤": { text: "heart", image: "2764" },
		"➕": { text: "heavy_plus_sign", image: "2795" },
		"➖": { text: "heavy_minus_sign", image: "2796" },
		"➗": { text: "heavy_division_sign", image: "2797" },
		"➡": { text: "arrow_right", image: "27a1" },
		"➰": { text: "curly_loop", image: "27b0" },
		"➿": { text: "loop", image: "27bf" },
		"⤴": { text: "arrow_heading_up", image: "2934" },
		"⤵": { text: "arrow_heading_down", image: "2935" },
		"⬅": { text: "arrow_left", image: "2b05" },
		"⬆": { text: "arrow_up", image: "2b06" },
		"⬇": { text: "arrow_down", image: "2b07" },
		"⬛": { text: "black_large_square", image: "2b1b" },
		"⬜": { text: "white_large_square", image: "2b1c" },
		"⭐": { text: "star", image: "2b50" },
		"⭕": { text: "o", image: "2b55" },
		"〰": { text: "wavy_dash", image: "3030" },
		"〽": { text: "part_alternation_mark", image: "303d" },
		"㊗": { text: "congratulations", image: "3297" },
		"㊙": { text: "secret", image: "3299" },
		"🀄": { text: "mahjong", image: "1f004" },
		"🃏": { text: "black_joker", image: "1f0cf" },
		"🅰": { text: "a", image: "1f170" },
		"🅱": { text: "b", image: "1f171" },
		"🅾": { text: "o2", image: "1f17e" },
		"🅿": { text: "parking", image: "1f17f" },
		"🆎": { text: "ab", image: "1f18e" },
		"🆑": { text: "cl", image: "1f191" },
		"🆒": { text: "cool", image: "1f192" },
		"🆓": { text: "free", image: "1f193" },
		"🆔": { text: "id", image: "1f194" },
		"🆕": { text: "new", image: "1f195" },
		"🆖": { text: "ng", image: "1f196" },
		"🆗": { text: "ok", image: "1f197" },
		"🆘": { text: "sos", image: "1f198" },
		"🆙": { text: "up", image: "1f199" },
		"🆚": { text: "vs", image: "1f19a" },
		"🇦": { text: "regional_indicator_a", image: "1f1e6" },
		"🇦🇨": { text: "flag_ac", image: "1f1e6-1f1e8" },
		"🇦🇩": { text: "flag_ad", image: "1f1e6-1f1e9" },
		"🇦🇪": { text: "flag_ae", image: "1f1e6-1f1ea" },
		"🇦🇫": { text: "flag_af", image: "1f1e6-1f1eb" },
		"🇦🇬": { text: "flag_ag", image: "1f1e6-1f1ec" },
		"🇦🇮": { text: "flag_ai", image: "1f1e6-1f1ee" },
		"🇦🇱": { text: "flag_al", image: "1f1e6-1f1f1" },
		"🇦🇲": { text: "flag_am", image: "1f1e6-1f1f2" },
		"🇦🇴": { text: "flag_ao", image: "1f1e6-1f1f4" },
		"🇦🇶": { text: "flag_aq", image: "1f1e6-1f1f6" },
		"🇦🇷": { text: "flag_ar", image: "1f1e6-1f1f7" },
		"🇦🇸": { text: "flag_as", image: "1f1e6-1f1f8" },
		"🇦🇹": { text: "flag_at", image: "1f1e6-1f1f9" },
		"🇦🇺": { text: "flag_au", image: "1f1e6-1f1fa" },
		"🇦🇼": { text: "flag_aw", image: "1f1e6-1f1fc" },
		"🇦🇽": { text: "flag_ax", image: "1f1e6-1f1fd" },
		"🇦🇿": { text: "flag_az", image: "1f1e6-1f1ff" },
		"🇧": { text: "regional_indicator_b", image: "1f1e7" },
		"🇧🇦": { text: "flag_ba", image: "1f1e7-1f1e6" },
		"🇧🇧": { text: "flag_bb", image: "1f1e7-1f1e7" },
		"🇧🇩": { text: "flag_bd", image: "1f1e7-1f1e9" },
		"🇧🇪": { text: "flag_be", image: "1f1e7-1f1ea" },
		"🇧🇫": { text: "flag_bf", image: "1f1e7-1f1eb" },
		"🇧🇬": { text: "flag_bg", image: "1f1e7-1f1ec" },
		"🇧🇭": { text: "flag_bh", image: "1f1e7-1f1ed" },
		"🇧🇮": { text: "flag_bi", image: "1f1e7-1f1ee" },
		"🇧🇯": { text: "flag_bj", image: "1f1e7-1f1ef" },
		"🇧🇱": { text: "flag_bl", image: "1f1e7-1f1f1" },
		"🇧🇲": { text: "flag_bm", image: "1f1e7-1f1f2" },
		"🇧🇳": { text: "flag_bn", image: "1f1e7-1f1f3" },
		"🇧🇴": { text: "flag_bo", image: "1f1e7-1f1f4" },
		"🇧🇶": { text: "flag_bq", image: "1f1e7-1f1f6" },
		"🇧🇷": { text: "flag_br", image: "1f1e7-1f1f7" },
		"🇧🇸": { text: "flag_bs", image: "1f1e7-1f1f8" },
		"🇧🇹": { text: "flag_bt", image: "1f1e7-1f1f9" },
		"🇧🇻": { text: "flag_bv", image: "1f1e7-1f1fb" },
		"🇧🇼": { text: "flag_bw", image: "1f1e7-1f1fc" },
		"🇧🇾": { text: "flag_by", image: "1f1e7-1f1fe" },
		"🇧🇿": { text: "flag_bz", image: "1f1e7-1f1ff" },
		"🇨": { text: "regional_indicator_c", image: "1f1e8" },
		"🇨🇦": { text: "flag_ca", image: "1f1e8-1f1e6" },
		"🇨🇨": { text: "flag_cc", image: "1f1e8-1f1e8" },
		"🇨🇩": { text: "flag_cd", image: "1f1e8-1f1e9" },
		"🇨🇫": { text: "flag_cf", image: "1f1e8-1f1eb" },
		"🇨🇬": { text: "flag_cg", image: "1f1e8-1f1ec" },
		"🇨🇭": { text: "flag_ch", image: "1f1e8-1f1ed" },
		"🇨🇮": { text: "flag_ci", image: "1f1e8-1f1ee" },
		"🇨🇰": { text: "flag_ck", image: "1f1e8-1f1f0" },
		"🇨🇱": { text: "flag_cl", image: "1f1e8-1f1f1" },
		"🇨🇲": { text: "flag_cm", image: "1f1e8-1f1f2" },
		"🇨🇳": { text: "flag_cn", image: "1f1e8-1f1f3" },
		"🇨🇴": { text: "flag_co", image: "1f1e8-1f1f4" },
		"🇨🇵": { text: "flag_cp", image: "1f1e8-1f1f5" },
		"🇨🇷": { text: "flag_cr", image: "1f1e8-1f1f7" },
		"🇨🇺": { text: "flag_cu", image: "1f1e8-1f1fa" },
		"🇨🇻": { text: "flag_cv", image: "1f1e8-1f1fb" },
		"🇨🇼": { text: "flag_cw", image: "1f1e8-1f1fc" },
		"🇨🇽": { text: "flag_cx", image: "1f1e8-1f1fd" },
		"🇨🇾": { text: "flag_cy", image: "1f1e8-1f1fe" },
		"🇨🇿": { text: "flag_cz", image: "1f1e8-1f1ff" },
		"🇩": { text: "regional_indicator_d", image: "1f1e9" },
		"🇩🇪": { text: "flag_de", image: "1f1e9-1f1ea" },
		"🇩🇬": { text: "flag_dg", image: "1f1e9-1f1ec" },
		"🇩🇯": { text: "flag_dj", image: "1f1e9-1f1ef" },
		"🇩🇰": { text: "flag_dk", image: "1f1e9-1f1f0" },
		"🇩🇲": { text: "flag_dm", image: "1f1e9-1f1f2" },
		"🇩🇴": { text: "flag_do", image: "1f1e9-1f1f4" },
		"🇩🇿": { text: "flag_dz", image: "1f1e9-1f1ff" },
		"🇪": { text: "regional_indicator_e", image: "1f1ea" },
		"🇪🇦": { text: "flag_ea", image: "1f1ea-1f1e6" },
		"🇪🇨": { text: "flag_ec", image: "1f1ea-1f1e8" },
		"🇪🇪": { text: "flag_ee", image: "1f1ea-1f1ea" },
		"🇪🇬": { text: "flag_eg", image: "1f1ea-1f1ec" },
		"🇪🇭": { text: "flag_eh", image: "1f1ea-1f1ed" },
		"🇪🇷": { text: "flag_er", image: "1f1ea-1f1f7" },
		"🇪🇸": { text: "flag_es", image: "1f1ea-1f1f8" },
		"🇪🇹": { text: "flag_et", image: "1f1ea-1f1f9" },
		"🇪🇺": { text: "flag_eu", image: "1f1ea-1f1fa" },
		"🇫": { text: "regional_indicator_f", image: "1f1eb" },
		"🇫🇮": { text: "flag_fi", image: "1f1eb-1f1ee" },
		"🇫🇯": { text: "flag_fj", image: "1f1eb-1f1ef" },
		"🇫🇰": { text: "flag_fk", image: "1f1eb-1f1f0" },
		"🇫🇲": { text: "flag_fm", image: "1f1eb-1f1f2" },
		"🇫🇴": { text: "flag_fo", image: "1f1eb-1f1f4" },
		"🇫🇷": { text: "flag_fr", image: "1f1eb-1f1f7" },
		"🇬": { text: "regional_indicator_g", image: "1f1ec" },
		"🇬🇦": { text: "flag_ga", image: "1f1ec-1f1e6" },
		"🇬🇧": { text: "flag_gb", image: "1f1ec-1f1e7" },
		"🇬🇩": { text: "flag_gd", image: "1f1ec-1f1e9" },
		"🇬🇪": { text: "flag_ge", image: "1f1ec-1f1ea" },
		"🇬🇫": { text: "flag_gf", image: "1f1ec-1f1eb" },
		"🇬🇬": { text: "flag_gg", image: "1f1ec-1f1ec" },
		"🇬🇭": { text: "flag_gh", image: "1f1ec-1f1ed" },
		"🇬🇮": { text: "flag_gi", image: "1f1ec-1f1ee" },
		"🇬🇱": { text: "flag_gl", image: "1f1ec-1f1f1" },
		"🇬🇲": { text: "flag_gm", image: "1f1ec-1f1f2" },
		"🇬🇳": { text: "flag_gn", image: "1f1ec-1f1f3" },
		"🇬🇵": { text: "flag_gp", image: "1f1ec-1f1f5" },
		"🇬🇶": { text: "flag_gq", image: "1f1ec-1f1f6" },
		"🇬🇷": { text: "flag_gr", image: "1f1ec-1f1f7" },
		"🇬🇸": { text: "flag_gs", image: "1f1ec-1f1f8" },
		"🇬🇹": { text: "flag_gt", image: "1f1ec-1f1f9" },
		"🇬🇺": { text: "flag_gu", image: "1f1ec-1f1fa" },
		"🇬🇼": { text: "flag_gw", image: "1f1ec-1f1fc" },
		"🇬🇾": { text: "flag_gy", image: "1f1ec-1f1fe" },
		"🇭": { text: "regional_indicator_h", image: "1f1ed" },
		"🇭🇰": { text: "flag_hk", image: "1f1ed-1f1f0" },
		"🇭🇲": { text: "flag_hm", image: "1f1ed-1f1f2" },
		"🇭🇳": { text: "flag_hn", image: "1f1ed-1f1f3" },
		"🇭🇷": { text: "flag_hr", image: "1f1ed-1f1f7" },
		"🇭🇹": { text: "flag_ht", image: "1f1ed-1f1f9" },
		"🇭🇺": { text: "flag_hu", image: "1f1ed-1f1fa" },
		"🇮": { text: "regional_indicator_i", image: "1f1ee" },
		"🇮🇨": { text: "flag_ic", image: "1f1ee-1f1e8" },
		"🇮🇩": { text: "flag_id", image: "1f1ee-1f1e9" },
		"🇮🇪": { text: "flag_ie", image: "1f1ee-1f1ea" },
		"🇮🇱": { text: "flag_il", image: "1f1ee-1f1f1" },
		"🇮🇲": { text: "flag_im", image: "1f1ee-1f1f2" },
		"🇮🇳": { text: "flag_in", image: "1f1ee-1f1f3" },
		"🇮🇴": { text: "flag_io", image: "1f1ee-1f1f4" },
		"🇮🇶": { text: "flag_iq", image: "1f1ee-1f1f6" },
		"🇮🇷": { text: "flag_ir", image: "1f1ee-1f1f7" },
		"🇮🇸": { text: "flag_is", image: "1f1ee-1f1f8" },
		"🇮🇹": { text: "flag_it", image: "1f1ee-1f1f9" },
		"🇯": { text: "regional_indicator_j", image: "1f1ef" },
		"🇯🇪": { text: "flag_je", image: "1f1ef-1f1ea" },
		"🇯🇲": { text: "flag_jm", image: "1f1ef-1f1f2" },
		"🇯🇴": { text: "flag_jo", image: "1f1ef-1f1f4" },
		"🇯🇵": { text: "flag_jp", image: "1f1ef-1f1f5" },
		"🇰": { text: "regional_indicator_k", image: "1f1f0" },
		"🇰🇪": { text: "flag_ke", image: "1f1f0-1f1ea" },
		"🇰🇬": { text: "flag_kg", image: "1f1f0-1f1ec" },
		"🇰🇭": { text: "flag_kh", image: "1f1f0-1f1ed" },
		"🇰🇮": { text: "flag_ki", image: "1f1f0-1f1ee" },
		"🇰🇲": { text: "flag_km", image: "1f1f0-1f1f2" },
		"🇰🇳": { text: "flag_kn", image: "1f1f0-1f1f3" },
		"🇰🇵": { text: "flag_kp", image: "1f1f0-1f1f5" },
		"🇰🇷": { text: "flag_kr", image: "1f1f0-1f1f7" },
		"🇰🇼": { text: "flag_kw", image: "1f1f0-1f1fc" },
		"🇰🇾": { text: "flag_ky", image: "1f1f0-1f1fe" },
		"🇰🇿": { text: "flag_kz", image: "1f1f0-1f1ff" },
		"🇱": { text: "regional_indicator_l", image: "1f1f1" },
		"🇱🇦": { text: "flag_la", image: "1f1f1-1f1e6" },
		"🇱🇧": { text: "flag_lb", image: "1f1f1-1f1e7" },
		"🇱🇨": { text: "flag_lc", image: "1f1f1-1f1e8" },
		"🇱🇮": { text: "flag_li", image: "1f1f1-1f1ee" },
		"🇱🇰": { text: "flag_lk", image: "1f1f1-1f1f0" },
		"🇱🇷": { text: "flag_lr", image: "1f1f1-1f1f7" },
		"🇱🇸": { text: "flag_ls", image: "1f1f1-1f1f8" },
		"🇱🇹": { text: "flag_lt", image: "1f1f1-1f1f9" },
		"🇱🇺": { text: "flag_lu", image: "1f1f1-1f1fa" },
		"🇱🇻": { text: "flag_lv", image: "1f1f1-1f1fb" },
		"🇱🇾": { text: "flag_ly", image: "1f1f1-1f1fe" },
		"🇲": { text: "regional_indicator_m", image: "1f1f2" },
		"🇲🇦": { text: "flag_ma", image: "1f1f2-1f1e6" },
		"🇲🇨": { text: "flag_mc", image: "1f1f2-1f1e8" },
		"🇲🇩": { text: "flag_md", image: "1f1f2-1f1e9" },
		"🇲🇪": { text: "flag_me", image: "1f1f2-1f1ea" },
		"🇲🇫": { text: "flag_mf", image: "1f1f2-1f1eb" },
		"🇲🇬": { text: "flag_mg", image: "1f1f2-1f1ec" },
		"🇲🇭": { text: "flag_mh", image: "1f1f2-1f1ed" },
		"🇲🇰": { text: "flag_mk", image: "1f1f2-1f1f0" },
		"🇲🇱": { text: "flag_ml", image: "1f1f2-1f1f1" },
		"🇲🇲": { text: "flag_mm", image: "1f1f2-1f1f2" },
		"🇲🇳": { text: "flag_mn", image: "1f1f2-1f1f3" },
		"🇲🇴": { text: "flag_mo", image: "1f1f2-1f1f4" },
		"🇲🇵": { text: "flag_mp", image: "1f1f2-1f1f5" },
		"🇲🇶": { text: "flag_mq", image: "1f1f2-1f1f6" },
		"🇲🇷": { text: "flag_mr", image: "1f1f2-1f1f7" },
		"🇲🇸": { text: "flag_ms", image: "1f1f2-1f1f8" },
		"🇲🇹": { text: "flag_mt", image: "1f1f2-1f1f9" },
		"🇲🇺": { text: "flag_mu", image: "1f1f2-1f1fa" },
		"🇲🇻": { text: "flag_mv", image: "1f1f2-1f1fb" },
		"🇲🇼": { text: "flag_mw", image: "1f1f2-1f1fc" },
		"🇲🇽": { text: "flag_mx", image: "1f1f2-1f1fd" },
		"🇲🇾": { text: "flag_my", image: "1f1f2-1f1fe" },
		"🇲🇿": { text: "flag_mz", image: "1f1f2-1f1ff" },
		"🇳": { text: "regional_indicator_n", image: "1f1f3" },
		"🇳🇦": { text: "flag_na", image: "1f1f3-1f1e6" },
		"🇳🇨": { text: "flag_nc", image: "1f1f3-1f1e8" },
		"🇳🇪": { text: "flag_ne", image: "1f1f3-1f1ea" },
		"🇳🇫": { text: "flag_nf", image: "1f1f3-1f1eb" },
		"🇳🇬": { text: "flag_ng", image: "1f1f3-1f1ec" },
		"🇳🇮": { text: "flag_ni", image: "1f1f3-1f1ee" },
		"🇳🇱": { text: "flag_nl", image: "1f1f3-1f1f1" },
		"🇳🇴": { text: "flag_no", image: "1f1f3-1f1f4" },
		"🇳🇵": { text: "flag_np", image: "1f1f3-1f1f5" },
		"🇳🇷": { text: "flag_nr", image: "1f1f3-1f1f7" },
		"🇳🇺": { text: "flag_nu", image: "1f1f3-1f1fa" },
		"🇳🇿": { text: "flag_nz", image: "1f1f3-1f1ff" },
		"🇴": { text: "regional_indicator_o", image: "1f1f4" },
		"🇴🇲": { text: "flag_om", image: "1f1f4-1f1f2" },
		"🇵": { text: "regional_indicator_p", image: "1f1f5" },
		"🇵🇦": { text: "flag_pa", image: "1f1f5-1f1e6" },
		"🇵🇪": { text: "flag_pe", image: "1f1f5-1f1ea" },
		"🇵🇫": { text: "flag_pf", image: "1f1f5-1f1eb" },
		"🇵🇬": { text: "flag_pg", image: "1f1f5-1f1ec" },
		"🇵🇭": { text: "flag_ph", image: "1f1f5-1f1ed" },
		"🇵🇰": { text: "flag_pk", image: "1f1f5-1f1f0" },
		"🇵🇱": { text: "flag_pl", image: "1f1f5-1f1f1" },
		"🇵🇲": { text: "flag_pm", image: "1f1f5-1f1f2" },
		"🇵🇳": { text: "flag_pn", image: "1f1f5-1f1f3" },
		"🇵🇷": { text: "flag_pr", image: "1f1f5-1f1f7" },
		"🇵🇸": { text: "flag_ps", image: "1f1f5-1f1f8" },
		"🇵🇹": { text: "flag_pt", image: "1f1f5-1f1f9" },
		"🇵🇼": { text: "flag_pw", image: "1f1f5-1f1fc" },
		"🇵🇾": { text: "flag_py", image: "1f1f5-1f1fe" },
		"🇶": { text: "regional_indicator_q", image: "1f1f6" },
		"🇶🇦": { text: "flag_qa", image: "1f1f6-1f1e6" },
		"🇷": { text: "regional_indicator_r", image: "1f1f7" },
		"🇷🇪": { text: "flag_re", image: "1f1f7-1f1ea" },
		"🇷🇴": { text: "flag_ro", image: "1f1f7-1f1f4" },
		"🇷🇸": { text: "flag_rs", image: "1f1f7-1f1f8" },
		"🇷🇺": { text: "flag_ru", image: "1f1f7-1f1fa" },
		"🇷🇼": { text: "flag_rw", image: "1f1f7-1f1fc" },
		"🇸": { text: "regional_indicator_s", image: "1f1f8" },
		"🇸🇦": { text: "flag_sa", image: "1f1f8-1f1e6" },
		"🇸🇧": { text: "flag_sb", image: "1f1f8-1f1e7" },
		"🇸🇨": { text: "flag_sc", image: "1f1f8-1f1e8" },
		"🇸🇩": { text: "flag_sd", image: "1f1f8-1f1e9" },
		"🇸🇪": { text: "flag_se", image: "1f1f8-1f1ea" },
		"🇸🇬": { text: "flag_sg", image: "1f1f8-1f1ec" },
		"🇸🇭": { text: "flag_sh", image: "1f1f8-1f1ed" },
		"🇸🇮": { text: "flag_si", image: "1f1f8-1f1ee" },
		"🇸🇯": { text: "flag_sj", image: "1f1f8-1f1ef" },
		"🇸🇰": { text: "flag_sk", image: "1f1f8-1f1f0" },
		"🇸🇱": { text: "flag_sl", image: "1f1f8-1f1f1" },
		"🇸🇲": { text: "flag_sm", image: "1f1f8-1f1f2" },
		"🇸🇳": { text: "flag_sn", image: "1f1f8-1f1f3" },
		"🇸🇴": { text: "flag_so", image: "1f1f8-1f1f4" },
		"🇸🇷": { text: "flag_sr", image: "1f1f8-1f1f7" },
		"🇸🇸": { text: "flag_ss", image: "1f1f8-1f1f8" },
		"🇸🇹": { text: "flag_st", image: "1f1f8-1f1f9" },
		"🇸🇻": { text: "flag_sv", image: "1f1f8-1f1fb" },
		"🇸🇽": { text: "flag_sx", image: "1f1f8-1f1fd" },
		"🇸🇾": { text: "flag_sy", image: "1f1f8-1f1fe" },
		"🇸🇿": { text: "flag_sz", image: "1f1f8-1f1ff" },
		"🇹": { text: "regional_indicator_t", image: "1f1f9" },
		"🇹🇦": { text: "flag_ta", image: "1f1f9-1f1e6" },
		"🇹🇨": { text: "flag_tc", image: "1f1f9-1f1e8" },
		"🇹🇩": { text: "flag_td", image: "1f1f9-1f1e9" },
		"🇹🇫": { text: "flag_tf", image: "1f1f9-1f1eb" },
		"🇹🇬": { text: "flag_tg", image: "1f1f9-1f1ec" },
		"🇹🇭": { text: "flag_th", image: "1f1f9-1f1ed" },
		"🇹🇯": { text: "flag_tj", image: "1f1f9-1f1ef" },
		"🇹🇰": { text: "flag_tk", image: "1f1f9-1f1f0" },
		"🇹🇱": { text: "flag_tl", image: "1f1f9-1f1f1" },
		"🇹🇲": { text: "flag_tm", image: "1f1f9-1f1f2" },
		"🇹🇳": { text: "flag_tn", image: "1f1f9-1f1f3" },
		"🇹🇴": { text: "flag_to", image: "1f1f9-1f1f4" },
		"🇹🇷": { text: "flag_tr", image: "1f1f9-1f1f7" },
		"🇹🇹": { text: "flag_tt", image: "1f1f9-1f1f9" },
		"🇹🇻": { text: "flag_tv", image: "1f1f9-1f1fb" },
		"🇹🇼": { text: "flag_tw", image: "1f1f9-1f1fc" },
		"🇹🇿": { text: "flag_tz", image: "1f1f9-1f1ff" },
		"🇺": { text: "regional_indicator_u", image: "1f1fa" },
		"🇺🇦": { text: "flag_ua", image: "1f1fa-1f1e6" },
		"🇺🇬": { text: "flag_ug", image: "1f1fa-1f1ec" },
		"🇺🇲": { text: "flag_um", image: "1f1fa-1f1f2" },
		"🇺🇸": { text: "flag_us", image: "1f1fa-1f1f8" },
		"🇺🇾": { text: "flag_uy", image: "1f1fa-1f1fe" },
		"🇺🇿": { text: "flag_uz", image: "1f1fa-1f1ff" },
		"🇻": { text: "regional_indicator_v", image: "1f1fb" },
		"🇻🇦": { text: "flag_va", image: "1f1fb-1f1e6" },
		"🇻🇨": { text: "flag_vc", image: "1f1fb-1f1e8" },
		"🇻🇪": { text: "flag_ve", image: "1f1fb-1f1ea" },
		"🇻🇬": { text: "flag_vg", image: "1f1fb-1f1ec" },
		"🇻🇮": { text: "flag_vi", image: "1f1fb-1f1ee" },
		"🇻🇳": { text: "flag_vn", image: "1f1fb-1f1f3" },
		"🇻🇺": { text: "flag_vu", image: "1f1fb-1f1fa" },
		"🇼": { text: "regional_indicator_w", image: "1f1fc" },
		"🇼🇫": { text: "flag_wf", image: "1f1fc-1f1eb" },
		"🇼🇸": { text: "flag_ws", image: "1f1fc-1f1f8" },
		"🇽": { text: "regional_indicator_x", image: "1f1fd" },
		"🇽🇰": { text: "flag_xk", image: "1f1fd-1f1f0" },
		"🇾": { text: "regional_indicator_y", image: "1f1fe" },
		"🇾🇪": { text: "flag_ye", image: "1f1fe-1f1ea" },
		"🇾🇹": { text: "flag_yt", image: "1f1fe-1f1f9" },
		"🇿": { text: "regional_indicator_z", image: "1f1ff" },
		"🇿🇦": { text: "flag_za", image: "1f1ff-1f1e6" },
		"🇿🇲": { text: "flag_zm", image: "1f1ff-1f1f2" },
		"🇿🇼": { text: "flag_zw", image: "1f1ff-1f1fc" },
		"🈁": { text: "koko", image: "1f201" },
		"🈂": { text: "sa", image: "1f202" },
		"🈚": { text: "u7121", image: "1f21a" },
		"🈯": { text: "u6307", image: "1f22f" },
		"🈲": { text: "u7981", image: "1f232" },
		"🈳": { text: "u7a7a", image: "1f233" },
		"🈴": { text: "u5408", image: "1f234" },
		"🈵": { text: "u6e80", image: "1f235" },
		"🈶": { text: "u6709", image: "1f236" },
		"🈷": { text: "u6708", image: "1f237" },
		"🈸": { text: "u7533", image: "1f238" },
		"🈹": { text: "u5272", image: "1f239" },
		"🈺": { text: "u55b6", image: "1f23a" },
		"🉐": { text: "ideograph_advantage", image: "1f250" },
		"🉑": { text: "accept", image: "1f251" },
		"🌀": { text: "cyclone", image: "1f300" },
		"🌁": { text: "foggy", image: "1f301" },
		"🌂": { text: "closed_umbrella", image: "1f302" },
		"🌃": { text: "night_with_stars", image: "1f303" },
		"🌄": { text: "sunrise_over_mountains", image: "1f304" },
		"🌅": { text: "sunrise", image: "1f305" },
		"🌆": { text: "city_dusk", image: "1f306" },
		"🌇": { text: "city_sunrise", image: "1f307" },
		"🌈": { text: "rainbow", image: "1f308" },
		"🌉": { text: "bridge_at_night", image: "1f309" },
		"🌊": { text: "ocean", image: "1f30a" },
		"🌋": { text: "volcano", image: "1f30b" },
		"🌌": { text: "milky_way", image: "1f30c" },
		"🌍": { text: "earth_africa", image: "1f30d" },
		"🌎": { text: "earth_americas", image: "1f30e" },
		"🌏": { text: "earth_asia", image: "1f30f" },
		"🌐": { text: "globe_with_meridians", image: "1f310" },
		"🌑": { text: "new_moon", image: "1f311" },
		"🌒": { text: "waxing_crescent_moon", image: "1f312" },
		"🌓": { text: "first_quarter_moon", image: "1f313" },
		"🌔": { text: "waxing_gibbous_moon", image: "1f314" },
		"🌕": { text: "full_moon", image: "1f315" },
		"🌖": { text: "waning_gibbous_moon", image: "1f316" },
		"🌗": { text: "last_quarter_moon", image: "1f317" },
		"🌘": { text: "waning_crescent_moon", image: "1f318" },
		"🌙": { text: "crescent_moon", image: "1f319" },
		"🌚": { text: "new_moon_with_face", image: "1f31a" },
		"🌛": { text: "first_quarter_moon_with_face", image: "1f31b" },
		"🌜": { text: "last_quarter_moon_with_face", image: "1f31c" },
		"🌝": { text: "full_moon_with_face", image: "1f31d" },
		"🌞": { text: "sun_with_face", image: "1f31e" },
		"🌟": { text: "star2", image: "1f31f" },
		"🌠": { text: "stars", image: "1f320" },
		"🌰": { text: "chestnut", image: "1f330" },
		"🌱": { text: "seedling", image: "1f331" },
		"🌲": { text: "evergreen_tree", image: "1f332" },
		"🌳": { text: "deciduous_tree", image: "1f333" },
		"🌴": { text: "palm_tree", image: "1f334" },
		"🌵": { text: "cactus", image: "1f335" },
		"🌷": { text: "tulip", image: "1f337" },
		"🌸": { text: "cherry_blossom", image: "1f338" },
		"🌹": { text: "rose", image: "1f339" },
		"🌺": { text: "hibiscus", image: "1f33a" },
		"🌻": { text: "sunflower", image: "1f33b" },
		"🌼": { text: "blossom", image: "1f33c" },
		"🌽": { text: "corn", image: "1f33d" },
		"🌾": { text: "ear_of_rice", image: "1f33e" },
		"🌿": { text: "herb", image: "1f33f" },
		"🍀": { text: "four_leaf_clover", image: "1f340" },
		"🍁": { text: "maple_leaf", image: "1f341" },
		"🍂": { text: "fallen_leaf", image: "1f342" },
		"🍃": { text: "leaves", image: "1f343" },
		"🍄": { text: "mushroom", image: "1f344" },
		"🍅": { text: "tomato", image: "1f345" },
		"🍆": { text: "eggplant", image: "1f346" },
		"🍇": { text: "grapes", image: "1f347" },
		"🍈": { text: "melon", image: "1f348" },
		"🍉": { text: "watermelon", image: "1f349" },
		"🍊": { text: "tangerine", image: "1f34a" },
		"🍋": { text: "lemon", image: "1f34b" },
		"🍌": { text: "banana", image: "1f34c" },
		"🍍": { text: "pineapple", image: "1f34d" },
		"🍎": { text: "apple", image: "1f34e" },
		"🍏": { text: "green_apple", image: "1f34f" },
		"🍐": { text: "pear", image: "1f350" },
		"🍑": { text: "peach", image: "1f351" },
		"🍒": { text: "cherries", image: "1f352" },
		"🍓": { text: "strawberry", image: "1f353" },
		"🍔": { text: "hamburger", image: "1f354" },
		"🍕": { text: "pizza", image: "1f355" },
		"🍖": { text: "meat_on_bone", image: "1f356" },
		"🍗": { text: "poultry_leg", image: "1f357" },
		"🍘": { text: "rice_cracker", image: "1f358" },
		"🍙": { text: "rice_ball", image: "1f359" },
		"🍚": { text: "rice", image: "1f35a" },
		"🍛": { text: "curry", image: "1f35b" },
		"🍜": { text: "ramen", image: "1f35c" },
		"🍝": { text: "spaghetti", image: "1f35d" },
		"🍞": { text: "bread", image: "1f35e" },
		"🍟": { text: "fries", image: "1f35f" },
		"🍠": { text: "sweet_potato", image: "1f360" },
		"🍡": { text: "dango", image: "1f361" },
		"🍢": { text: "oden", image: "1f362" },
		"🍣": { text: "sushi", image: "1f363" },
		"🍤": { text: "fried_shrimp", image: "1f364" },
		"🍥": { text: "fish_cake", image: "1f365" },
		"🍦": { text: "icecream", image: "1f366" },
		"🍧": { text: "shaved_ice", image: "1f367" },
		"🍨": { text: "ice_cream", image: "1f368" },
		"🍩": { text: "doughnut", image: "1f369" },
		"🍪": { text: "cookie", image: "1f36a" },
		"🍫": { text: "chocolate_bar", image: "1f36b" },
		"🍬": { text: "candy", image: "1f36c" },
		"🍭": { text: "lollipop", image: "1f36d" },
		"🍮": { text: "flan", image: "1f36e" },
		"🍯": { text: "honey_pot", image: "1f36f" },
		"🍰": { text: "cake", image: "1f370" },
		"🍱": { text: "bento", image: "1f371" },
		"🍲": { text: "stew", image: "1f372" },
		"🍳": { text: "cooking", image: "1f373" },
		"🍴": { text: "fork_and_knife", image: "1f374" },
		"🍵": { text: "tea", image: "1f375" },
		"🍶": { text: "sake", image: "1f376" },
		"🍷": { text: "wine_glass", image: "1f377" },
		"🍸": { text: "cocktail", image: "1f378" },
		"🍹": { text: "tropical_drink", image: "1f379" },
		"🍺": { text: "beer", image: "1f37a" },
		"🍻": { text: "beers", image: "1f37b" },
		"🍼": { text: "baby_bottle", image: "1f37c" },
		"🎀": { text: "ribbon", image: "1f380" },
		"🎁": { text: "gift", image: "1f381" },
		"🎂": { text: "birthday", image: "1f382" },
		"🎃": { text: "jack_o_lantern", image: "1f383" },
		"🎄": { text: "christmas_tree", image: "1f384" },
		"🎅": { text: "santa", image: "1f385" },
		"🎆": { text: "fireworks", image: "1f386" },
		"🎇": { text: "sparkler", image: "1f387" },
		"🎈": { text: "balloon", image: "1f388" },
		"🎉": { text: "tada", image: "1f389" },
		"🎊": { text: "confetti_ball", image: "1f38a" },
		"🎋": { text: "tanabata_tree", image: "1f38b" },
		"🎌": { text: "crossed_flags", image: "1f38c" },
		"🎍": { text: "bamboo", image: "1f38d" },
		"🎎": { text: "dolls", image: "1f38e" },
		"🎏": { text: "flags", image: "1f38f" },
		"🎐": { text: "wind_chime", image: "1f390" },
		"🎑": { text: "rice_scene", image: "1f391" },
		"🎒": { text: "school_satchel", image: "1f392" },
		"🎓": { text: "mortar_board", image: "1f393" },
		"🎠": { text: "carousel_horse", image: "1f3a0" },
		"🎡": { text: "ferris_wheel", image: "1f3a1" },
		"🎢": { text: "roller_coaster", image: "1f3a2" },
		"🎣": { text: "fishing_pole_and_fish", image: "1f3a3" },
		"🎤": { text: "microphone", image: "1f3a4" },
		"🎥": { text: "movie_camera", image: "1f3a5" },
		"🎦": { text: "cinema", image: "1f3a6" },
		"🎧": { text: "headphones", image: "1f3a7" },
		"🎨": { text: "art", image: "1f3a8" },
		"🎩": { text: "tophat", image: "1f3a9" },
		"🎪": { text: "circus_tent", image: "1f3aa" },
		"🎫": { text: "ticket", image: "1f3ab" },
		"🎬": { text: "clapper", image: "1f3ac" },
		"🎭": { text: "performing_arts", image: "1f3ad" },
		"🎮": { text: "video_game", image: "1f3ae" },
		"🎯": { text: "dart", image: "1f3af" },
		"🎰": { text: "slot_machine", image: "1f3b0" },
		"🎱": { text: "8ball", image: "1f3b1" },
		"🎲": { text: "game_die", image: "1f3b2" },
		"🎳": { text: "bowling", image: "1f3b3" },
		"🎴": { text: "flower_playing_cards", image: "1f3b4" },
		"🎵": { text: "musical_note", image: "1f3b5" },
		"🎶": { text: "notes", image: "1f3b6" },
		"🎷": { text: "saxophone", image: "1f3b7" },
		"🎸": { text: "guitar", image: "1f3b8" },
		"🎹": { text: "musical_keyboard", image: "1f3b9" },
		"🎺": { text: "trumpet", image: "1f3ba" },
		"🎻": { text: "violin", image: "1f3bb" },
		"🎼": { text: "musical_score", image: "1f3bc" },
		"🎽": { text: "running_shirt_with_sash", image: "1f3bd" },
		"🎾": { text: "tennis", image: "1f3be" },
		"🎿": { text: "ski", image: "1f3bf" },
		"🏀": { text: "basketball", image: "1f3c0" },
		"🏁": { text: "checkered_flag", image: "1f3c1" },
		"🏂": { text: "snowboarder", image: "1f3c2" },
		"🏃": { text: "runner", image: "1f3c3" },
		"🏄": { text: "surfer", image: "1f3c4" },
		"🏆": { text: "trophy", image: "1f3c6" },
		"🏇": { text: "horse_racing", image: "1f3c7" },
		"🏈": { text: "football", image: "1f3c8" },
		"🏉": { text: "rugby_football", image: "1f3c9" },
		"🏊": { text: "swimmer", image: "1f3ca" },
		"🏠": { text: "house", image: "1f3e0" },
		"🏡": { text: "house_with_garden", image: "1f3e1" },
		"🏢": { text: "office", image: "1f3e2" },
		"🏣": { text: "post_office", image: "1f3e3" },
		"🏤": { text: "european_post_office", image: "1f3e4" },
		"🏥": { text: "hospital", image: "1f3e5" },
		"🏦": { text: "bank", image: "1f3e6" },
		"🏧": { text: "atm", image: "1f3e7" },
		"🏨": { text: "hotel", image: "1f3e8" },
		"🏩": { text: "love_hotel", image: "1f3e9" },
		"🏪": { text: "convenience_store", image: "1f3ea" },
		"🏫": { text: "school", image: "1f3eb" },
		"🏬": { text: "department_store", image: "1f3ec" },
		"🏭": { text: "factory", image: "1f3ed" },
		"🏮": { text: "izakaya_lantern", image: "1f3ee" },
		"🏯": { text: "japanese_castle", image: "1f3ef" },
		"🏰": { text: "european_castle", image: "1f3f0" },
		"🏳️‍🌈": { text: "rainbow_flag", image: "1f3f3-fe0f-200d-1f308" },
		"🐀": { text: "rat", image: "1f400" },
		"🐁": { text: "mouse2", image: "1f401" },
		"🐂": { text: "ox", image: "1f402" },
		"🐃": { text: "water_buffalo", image: "1f403" },
		"🐄": { text: "cow2", image: "1f404" },
		"🐅": { text: "tiger2", image: "1f405" },
		"🐆": { text: "leopard", image: "1f406" },
		"🐇": { text: "rabbit2", image: "1f407" },
		"🐈": { text: "cat2", image: "1f408" },
		"🐉": { text: "dragon", image: "1f409" },
		"🐊": { text: "crocodile", image: "1f40a" },
		"🐋": { text: "whale2", image: "1f40b" },
		"🐌": { text: "snail", image: "1f40c" },
		"🐍": { text: "snake", image: "1f40d" },
		"🐎": { text: "racehorse", image: "1f40e" },
		"🐏": { text: "ram", image: "1f40f" },
		"🐐": { text: "goat", image: "1f410" },
		"🐑": { text: "sheep", image: "1f411" },
		"🐒": { text: "monkey", image: "1f412" },
		"🐓": { text: "rooster", image: "1f413" },
		"🐔": { text: "chicken", image: "1f414" },
		"🐕": { text: "dog2", image: "1f415" },
		"🐖": { text: "pig2", image: "1f416" },
		"🐗": { text: "boar", image: "1f417" },
		"🐘": { text: "elephant", image: "1f418" },
		"🐙": { text: "octopus", image: "1f419" },
		"🐚": { text: "shell", image: "1f41a" },
		"🐛": { text: "bug", image: "1f41b" },
		"🐜": { text: "ant", image: "1f41c" },
		"🐝": { text: "bee", image: "1f41d" },
		"🐞": { text: "beetle", image: "1f41e" },
		"🐟": { text: "fish", image: "1f41f" },
		"🐠": { text: "tropical_fish", image: "1f420" },
		"🐡": { text: "blowfish", image: "1f421" },
		"🐢": { text: "turtle", image: "1f422" },
		"🐣": { text: "hatching_chick", image: "1f423" },
		"🐤": { text: "baby_chick", image: "1f424" },
		"🐥": { text: "hatched_chick", image: "1f425" },
		"🐦": { text: "bird", image: "1f426" },
		"🐧": { text: "penguin", image: "1f427" },
		"🐨": { text: "koala", image: "1f428" },
		"🐩": { text: "poodle", image: "1f429" },
		"🐪": { text: "dromedary_camel", image: "1f42a" },
		"🐫": { text: "camel", image: "1f42b" },
		"🐬": { text: "dolphin", image: "1f42c" },
		"🐭": { text: "mouse", image: "1f42d" },
		"🐮": { text: "cow", image: "1f42e" },
		"🐯": { text: "tiger", image: "1f42f" },
		"🐰": { text: "rabbit", image: "1f430" },
		"🐱": { text: "cat", image: "1f431" },
		"🐲": { text: "dragon_face", image: "1f432" },
		"🐳": { text: "whale", image: "1f433" },
		"🐴": { text: "horse", image: "1f434" },
		"🐵": { text: "monkey_face", image: "1f435" },
		"🐶": { text: "dog", image: "1f436" },
		"🐷": { text: "pig", image: "1f437" },
		"🐸": { text: "frog", image: "1f438" },
		"🐹": { text: "hamster", image: "1f439" },
		"🐺": { text: "wolf", image: "1f43a" },
		"🐻": { text: "bear", image: "1f43b" },
		"🐼": { text: "panda_face", image: "1f43c" },
		"🐽": { text: "pig_nose", image: "1f43d" },
		"🐾": { text: "paw_prints", image: "1f43e" },
		"👀": { text: "eyes", image: "1f440" },
		"👂": { text: "ear", image: "1f442" },
		"👃": { text: "nose", image: "1f443" },
		"👄": { text: "lips", image: "1f444" },
		"👅": { text: "tongue", image: "1f445" },
		"👆": { text: "point_up_2", image: "1f446" },
		"👇": { text: "point_down", image: "1f447" },
		"👈": { text: "point_left", image: "1f448" },
		"👉": { text: "point_right", image: "1f449" },
		"👊": { text: "punch", image: "1f44a" },
		"👋": { text: "wave", image: "1f44b" },
		"👌": { text: "ok_hand", image: "1f44c" },
		"👍": { text: "thumbup", image: "1f44d" },
		"👎": { text: "thumbdown", image: "1f44e" },
		"👏": { text: "clap", image: "1f44f" },
		"👐": { text: "open_hands", image: "1f450" },
		"👑": { text: "crown", image: "1f451" },
		"👒": { text: "womans_hat", image: "1f452" },
		"👓": { text: "eyeglasses", image: "1f453" },
		"👔": { text: "necktie", image: "1f454" },
		"👕": { text: "shirt", image: "1f455" },
		"👖": { text: "jeans", image: "1f456" },
		"👗": { text: "dress", image: "1f457" },
		"👘": { text: "kimono", image: "1f458" },
		"👙": { text: "bikini", image: "1f459" },
		"👚": { text: "womans_clothes", image: "1f45a" },
		"👛": { text: "purse", image: "1f45b" },
		"👜": { text: "handbag", image: "1f45c" },
		"👝": { text: "pouch", image: "1f45d" },
		"👞": { text: "mans_shoe", image: "1f45e" },
		"👟": { text: "athletic_shoe", image: "1f45f" },
		"👠": { text: "high_heel", image: "1f460" },
		"👡": { text: "sandal", image: "1f461" },
		"👢": { text: "boot", image: "1f462" },
		"👣": { text: "footprints", image: "1f463" },
		"👤": { text: "bust_in_silhouette", image: "1f464" },
		"👥": { text: "busts_in_silhouette", image: "1f465" },
		"👦": { text: "boy", image: "1f466" },
		"👧": { text: "girl", image: "1f467" },
		"👨": { text: "man", image: "1f468" },
		"👨‍❤️‍👨": { text: "couple_with_heart_mm", image: "1f468-200d-2764-fe0f-200d-1f468" },
		"👨‍❤️‍💋‍👨": { text: "couplekiss_mm", image: "1f468-200d-2764-fe0f-200d-1f48b-200d-1f468" },
		"👨‍👨‍👦": { text: "family_mmb", image: "1f468-200d-1f468-200d-1f466" },
		"👨‍👨‍👦‍👦": { text: "family_mmbb", image: "1f468-200d-1f468-200d-1f466-200d-1f466" },
		"👨‍👨‍👧": { text: "family_mmg", image: "1f468-200d-1f468-200d-1f467" },
		"👨‍👨‍👧‍👦": { text: "family_mmgb", image: "1f468-200d-1f468-200d-1f467-200d-1f466" },
		"👨‍👨‍👧‍👧": { text: "family_mmgg", image: "1f468-200d-1f468-200d-1f467-200d-1f467" },
		"👨‍👩‍👦‍👦": { text: "family_mwbb", image: "1f468-200d-1f469-200d-1f466-200d-1f466" },
		"👨‍👩‍👧": { text: "family_mwg", image: "1f468-200d-1f469-200d-1f467" },
		"👨‍👩‍👧‍👦": { text: "family_mwgb", image: "1f468-200d-1f469-200d-1f467-200d-1f466" },
		"👨‍👩‍👧‍👧": { text: "family_mwgg", image: "1f468-200d-1f469-200d-1f467-200d-1f467" },
		"👩": { text: "woman", image: "1f469" },
		"👩‍❤️‍👩": { text: "couple_with_heart_ww", image: "1f469-200d-2764-fe0f-200d-1f469" },
		"👩‍❤️‍💋‍👩": { text: "couplekiss_ww", image: "1f469-200d-2764-fe0f-200d-1f48b-200d-1f469" },
		"👩‍👩‍👦": { text: "family_wwb", image: "1f469-200d-1f469-200d-1f466" },
		"👩‍👩‍👦‍👦": { text: "family_wwbb", image: "1f469-200d-1f469-200d-1f466-200d-1f466" },
		"👩‍👩‍👧": { text: "family_wwg", image: "1f469-200d-1f469-200d-1f467" },
		"👩‍👩‍👧‍👦": { text: "family_wwgb", image: "1f469-200d-1f469-200d-1f467-200d-1f466" },
		"👩‍👩‍👧‍👧": { text: "family_wwgg", image: "1f469-200d-1f469-200d-1f467-200d-1f467" },
		"👪": { text: "family", image: "1f46a" },
		"👫": { text: "couple", image: "1f46b" },
		"👬": { text: "two_men_holding_hands", image: "1f46c" },
		"👭": { text: "two_women_holding_hands", image: "1f46d" },
		"👮": { text: "cop", image: "1f46e" },
		"👯": { text: "dancers", image: "1f46f" },
		"👰": { text: "bride_with_veil", image: "1f470" },
		"👱": { text: "person_with_blond_hair", image: "1f471" },
		"👲": { text: "man_with_gua_pi_mao", image: "1f472" },
		"👳": { text: "man_with_turban", image: "1f473" },
		"👴": { text: "older_man", image: "1f474" },
		"👵": { text: "grandma", image: "1f475" },
		"👶": { text: "baby", image: "1f476" },
		"👷": { text: "construction_worker", image: "1f477" },
		"👸": { text: "princess", image: "1f478" },
		"👹": { text: "japanese_ogre", image: "1f479" },
		"👺": { text: "japanese_goblin", image: "1f47a" },
		"👻": { text: "ghost", image: "1f47b" },
		"👼": { text: "angel", image: "1f47c" },
		"👽": { text: "alien", image: "1f47d" },
		"👾": { text: "space_invader", image: "1f47e" },
		"👿": { text: "imp", image: "1f47f" },
		"💀": { text: "skeleton", image: "1f480" },
		"💁": { text: "information_desk_person", image: "1f481" },
		"💂": { text: "guardsman", image: "1f482" },
		"💃": { text: "dancer", image: "1f483" },
		"💄": { text: "lipstick", image: "1f484" },
		"💅": { text: "nail_care", image: "1f485" },
		"💆": { text: "massage", image: "1f486" },
		"💇": { text: "haircut", image: "1f487" },
		"💈": { text: "barber", image: "1f488" },
		"💉": { text: "syringe", image: "1f489" },
		"💊": { text: "pill", image: "1f48a" },
		"💋": { text: "kiss", image: "1f48b" },
		"💌": { text: "love_letter", image: "1f48c" },
		"💍": { text: "ring", image: "1f48d" },
		"💎": { text: "gem", image: "1f48e" },
		"💏": { text: "couplekiss", image: "1f48f" },
		"💐": { text: "bouquet", image: "1f490" },
		"💑": { text: "couple_with_heart", image: "1f491" },
		"💒": { text: "wedding", image: "1f492" },
		"💓": { text: "heartbeat", image: "1f493" },
		"💔": { text: "broken_heart", image: "1f494" },
		"💕": { text: "two_hearts", image: "1f495" },
		"💖": { text: "sparkling_heart", image: "1f496" },
		"💗": { text: "heartpulse", image: "1f497" },
		"💘": { text: "cupid", image: "1f498" },
		"💙": { text: "blue_heart", image: "1f499" },
		"💚": { text: "green_heart", image: "1f49a" },
		"💛": { text: "yellow_heart", image: "1f49b" },
		"💜": { text: "purple_heart", image: "1f49c" },
		"💝": { text: "gift_heart", image: "1f49d" },
		"💞": { text: "revolving_hearts", image: "1f49e" },
		"💟": { text: "heart_decoration", image: "1f49f" },
		"💠": { text: "diamond_shape_with_a_dot_inside", image: "1f4a0" },
		"💡": { text: "bulb", image: "1f4a1" },
		"💢": { text: "anger", image: "1f4a2" },
		"💣": { text: "bomb", image: "1f4a3" },
		"💤": { text: "zzz", image: "1f4a4" },
		"💥": { text: "boom", image: "1f4a5" },
		"💦": { text: "sweat_drops", image: "1f4a6" },
		"💧": { text: "droplet", image: "1f4a7" },
		"💨": { text: "dash", image: "1f4a8" },
		"💩": { text: "poo", image: "1f4a9" },
		"💪": { text: "muscle", image: "1f4aa" },
		"💫": { text: "dizzy", image: "1f4ab" },
		"💬": { text: "speech_balloon", image: "1f4ac" },
		"💭": { text: "thought_balloon", image: "1f4ad" },
		"💮": { text: "white_flower", image: "1f4ae" },
		"💯": { text: "100", image: "1f4af" },
		"💰": { text: "moneybag", image: "1f4b0" },
		"💱": { text: "currency_exchange", image: "1f4b1" },
		"💲": { text: "heavy_dollar_sign", image: "1f4b2" },
		"💳": { text: "credit_card", image: "1f4b3" },
		"💴": { text: "yen", image: "1f4b4" },
		"💵": { text: "dollar", image: "1f4b5" },
		"💶": { text: "euro", image: "1f4b6" },
		"💷": { text: "pound", image: "1f4b7" },
		"💸": { text: "money_with_wings", image: "1f4b8" },
		"💹": { text: "chart", image: "1f4b9" },
		"💺": { text: "seat", image: "1f4ba" },
		"💻": { text: "computer", image: "1f4bb" },
		"💼": { text: "briefcase", image: "1f4bc" },
		"💽": { text: "minidisc", image: "1f4bd" },
		"💾": { text: "floppy_disk", image: "1f4be" },
		"💿": { text: "cd", image: "1f4bf" },
		"📀": { text: "dvd", image: "1f4c0" },
		"📁": { text: "file_folder", image: "1f4c1" },
		"📂": { text: "open_file_folder", image: "1f4c2" },
		"📃": { text: "page_with_curl", image: "1f4c3" },
		"📄": { text: "page_facing_up", image: "1f4c4" },
		"📅": { text: "date", image: "1f4c5" },
		"📆": { text: "calendar", image: "1f4c6" },
		"📇": { text: "card_index", image: "1f4c7" },
		"📈": { text: "chart_with_upwards_trend", image: "1f4c8" },
		"📉": { text: "chart_with_downwards_trend", image: "1f4c9" },
		"📊": { text: "bar_chart", image: "1f4ca" },
		"📋": { text: "clipboard", image: "1f4cb" },
		"📌": { text: "pushpin", image: "1f4cc" },
		"📍": { text: "round_pushpin", image: "1f4cd" },
		"📎": { text: "paperclip", image: "1f4ce" },
		"📏": { text: "straight_ruler", image: "1f4cf" },
		"📐": { text: "triangular_ruler", image: "1f4d0" },
		"📑": { text: "bookmark_tabs", image: "1f4d1" },
		"📒": { text: "ledger", image: "1f4d2" },
		"📓": { text: "notebook", image: "1f4d3" },
		"📔": { text: "notebook_with_decorative_cover", image: "1f4d4" },
		"📕": { text: "closed_book", image: "1f4d5" },
		"📖": { text: "book", image: "1f4d6" },
		"📗": { text: "green_book", image: "1f4d7" },
		"📘": { text: "blue_book", image: "1f4d8" },
		"📙": { text: "orange_book", image: "1f4d9" },
		"📚": { text: "books", image: "1f4da" },
		"📛": { text: "name_badge", image: "1f4db" },
		"📜": { text: "scroll", image: "1f4dc" },
		"📝": { text: "pencil", image: "1f4dd" },
		"📞": { text: "telephone_receiver", image: "1f4de" },
		"📟": { text: "pager", image: "1f4df" },
		"📠": { text: "fax", image: "1f4e0" },
		"📡": { text: "satellite", image: "1f4e1" },
		"📢": { text: "loudspeaker", image: "1f4e2" },
		"📣": { text: "mega", image: "1f4e3" },
		"📤": { text: "outbox_tray", image: "1f4e4" },
		"📥": { text: "inbox_tray", image: "1f4e5" },
		"📦": { text: "package", image: "1f4e6" },
		"📧": { text: "email", image: "1f4e7" },
		"📨": { text: "incoming_envelope", image: "1f4e8" },
		"📩": { text: "envelope_with_arrow", image: "1f4e9" },
		"📪": { text: "mailbox_closed", image: "1f4ea" },
		"📫": { text: "mailbox", image: "1f4eb" },
		"📬": { text: "mailbox_with_mail", image: "1f4ec" },
		"📭": { text: "mailbox_with_no_mail", image: "1f4ed" },
		"📮": { text: "postbox", image: "1f4ee" },
		"📯": { text: "postal_horn", image: "1f4ef" },
		"📰": { text: "newspaper", image: "1f4f0" },
		"📱": { text: "iphone", image: "1f4f1" },
		"📲": { text: "calling", image: "1f4f2" },
		"📳": { text: "vibration_mode", image: "1f4f3" },
		"📴": { text: "mobile_phone_off", image: "1f4f4" },
		"📵": { text: "no_mobile_phones", image: "1f4f5" },
		"📶": { text: "signal_strength", image: "1f4f6" },
		"📷": { text: "camera", image: "1f4f7" },
		"📹": { text: "video_camera", image: "1f4f9" },
		"📺": { text: "tv", image: "1f4fa" },
		"📻": { text: "radio", image: "1f4fb" },
		"📼": { text: "vhs", image: "1f4fc" },
		"🔀": { text: "twisted_rightwards_arrows", image: "1f500" },
		"🔁": { text: "repeat", image: "1f501" },
		"🔂": { text: "repeat_one", image: "1f502" },
		"🔃": { text: "arrows_clockwise", image: "1f503" },
		"🔄": { text: "arrows_counterclockwise", image: "1f504" },
		"🔅": { text: "low_brightness", image: "1f505" },
		"🔆": { text: "high_brightness", image: "1f506" },
		"🔇": { text: "mute", image: "1f507" },
		"🔈": { text: "speaker", image: "1f508" },
		"🔉": { text: "sound", image: "1f509" },
		"🔊": { text: "loud_sound", image: "1f50a" },
		"🔋": { text: "battery", image: "1f50b" },
		"🔌": { text: "electric_plug", image: "1f50c" },
		"🔍": { text: "mag", image: "1f50d" },
		"🔎": { text: "mag_right", image: "1f50e" },
		"🔏": { text: "lock_with_ink_pen", image: "1f50f" },
		"🔐": { text: "closed_lock_with_key", image: "1f510" },
		"🔑": { text: "key", image: "1f511" },
		"🔒": { text: "lock", image: "1f512" },
		"🔓": { text: "unlock", image: "1f513" },
		"🔔": { text: "bell", image: "1f514" },
		"🔕": { text: "no_bell", image: "1f515" },
		"🔖": { text: "bookmark", image: "1f516" },
		"🔗": { text: "link", image: "1f517" },
		"🔘": { text: "radio_button", image: "1f518" },
		"🔙": { text: "back", image: "1f519" },
		"🔚": { text: "end", image: "1f51a" },
		"🔛": { text: "on", image: "1f51b" },
		"🔜": { text: "soon", image: "1f51c" },
		"🔝": { text: "top", image: "1f51d" },
		"🔞": { text: "underage", image: "1f51e" },
		"🔟": { text: "keycap_ten", image: "1f51f" },
		"🔠": { text: "capital_abcd", image: "1f520" },
		"🔡": { text: "abcd", image: "1f521" },
		"🔢": { text: "1234", image: "1f522" },
		"🔣": { text: "symbols", image: "1f523" },
		"🔤": { text: "abc", image: "1f524" },
		"🔥": { text: "flame", image: "1f525" },
		"🔦": { text: "flashlight", image: "1f526" },
		"🔧": { text: "wrench", image: "1f527" },
		"🔨": { text: "hammer", image: "1f528" },
		"🔩": { text: "nut_and_bolt", image: "1f529" },
		"🔪": { text: "knife", image: "1f52a" },
		"🔫": { text: "gun", image: "1f52b" },
		"🔬": { text: "microscope", image: "1f52c" },
		"🔭": { text: "telescope", image: "1f52d" },
		"🔮": { text: "crystal_ball", image: "1f52e" },
		"🔯": { text: "six_pointed_star", image: "1f52f" },
		"🔰": { text: "beginner", image: "1f530" },
		"🔱": { text: "trident", image: "1f531" },
		"🔲": { text: "black_square_button", image: "1f532" },
		"🔳": { text: "white_square_button", image: "1f533" },
		"🔴": { text: "red_circle", image: "1f534" },
		"🔵": { text: "large_blue_circle", image: "1f535" },
		"🔶": { text: "large_orange_diamond", image: "1f536" },
		"🔷": { text: "large_blue_diamond", image: "1f537" },
		"🔸": { text: "small_orange_diamond", image: "1f538" },
		"🔹": { text: "small_blue_diamond", image: "1f539" },
		"🔺": { text: "small_red_triangle", image: "1f53a" },
		"🔻": { text: "small_red_triangle_down", image: "1f53b" },
		"🔼": { text: "arrow_up_small", image: "1f53c" },
		"🔽": { text: "arrow_down_small", image: "1f53d" },
		"🕐": { text: "clock1", image: "1f550" },
		"🕑": { text: "clock2", image: "1f551" },
		"🕒": { text: "clock3", image: "1f552" },
		"🕓": { text: "clock4", image: "1f553" },
		"🕔": { text: "clock5", image: "1f554" },
		"🕕": { text: "clock6", image: "1f555" },
		"🕖": { text: "clock7", image: "1f556" },
		"🕗": { text: "clock8", image: "1f557" },
		"🕘": { text: "clock9", image: "1f558" },
		"🕙": { text: "clock10", image: "1f559" },
		"🕚": { text: "clock11", image: "1f55a" },
		"🕛": { text: "clock12", image: "1f55b" },
		"🕜": { text: "clock130", image: "1f55c" },
		"🕝": { text: "clock230", image: "1f55d" },
		"🕞": { text: "clock330", image: "1f55e" },
		"🕟": { text: "clock430", image: "1f55f" },
		"🕠": { text: "clock530", image: "1f560" },
		"🕡": { text: "clock630", image: "1f561" },
		"🕢": { text: "clock730", image: "1f562" },
		"🕣": { text: "clock830", image: "1f563" },
		"🕤": { text: "clock930", image: "1f564" },
		"🕥": { text: "clock1030", image: "1f565" },
		"🕦": { text: "clock1130", image: "1f566" },
		"🕧": { text: "clock1230", image: "1f567" },
		"🗻": { text: "mount_fuji", image: "1f5fb" },
		"🗼": { text: "tokyo_tower", image: "1f5fc" },
		"🗽": { text: "statue_of_liberty", image: "1f5fd" },
		"🗾": { text: "japan", image: "1f5fe" },
		"🗿": { text: "moyai", image: "1f5ff" },
		"😀": { text: "grinning", image: "1f600" },
		"😁": { text: "grin", image: "1f601" },
		"😂": { text: "joy", image: "1f602" },
		"😃": { text: "smiley", image: "1f603" },
		"😄": { text: "smile", image: "1f604" },
		"😅": { text: "sweat_smile", image: "1f605" },
		"😆": { text: "laughing", image: "1f606" },
		"😇": { text: "innocent", image: "1f607" },
		"😈": { text: "smiling_imp", image: "1f608" },
		"😉": { text: "wink", image: "1f609" },
		"😊": { text: "blush", image: "1f60a" },
		"😋": { text: "yum", image: "1f60b" },
		"😌": { text: "relieved", image: "1f60c" },
		"😍": { text: "heart_eyes", image: "1f60d" },
		"😎": { text: "sunglasses", image: "1f60e" },
		"😏": { text: "smirk", image: "1f60f" },
		"😐": { text: "neutral_face", image: "1f610" },
		"😑": { text: "expressionless", image: "1f611" },
		"😒": { text: "unamused", image: "1f612" },
		"😓": { text: "sweat", image: "1f613" },
		"😔": { text: "pensive", image: "1f614" },
		"😕": { text: "confused", image: "1f615" },
		"😖": { text: "confounded", image: "1f616" },
		"😗": { text: "kissing", image: "1f617" },
		"😘": { text: "kissing_heart", image: "1f618" },
		"😙": { text: "kissing_smiling_eyes", image: "1f619" },
		"😚": { text: "kissing_closed_eyes", image: "1f61a" },
		"😛": { text: "stuck_out_tongue", image: "1f61b" },
		"😜": { text: "stuck_out_tongue_winking_eye", image: "1f61c" },
		"😝": { text: "stuck_out_tongue_closed_eyes", image: "1f61d" },
		"😞": { text: "disappointed", image: "1f61e" },
		"😟": { text: "worried", image: "1f61f" },
		"😠": { text: "angry", image: "1f620" },
		"😡": { text: "rage", image: "1f621" },
		"😢": { text: "cry", image: "1f622" },
		"😣": { text: "persevere", image: "1f623" },
		"😤": { text: "triumph", image: "1f624" },
		"😥": { text: "disappointed_relieved", image: "1f625" },
		"😦": { text: "frowning", image: "1f626" },
		"😧": { text: "anguished", image: "1f627" },
		"😨": { text: "fearful", image: "1f628" },
		"😩": { text: "weary", image: "1f629" },
		"😪": { text: "sleepy", image: "1f62a" },
		"😫": { text: "tired_face", image: "1f62b" },
		"😬": { text: "grimacing", image: "1f62c" },
		"😭": { text: "sob", image: "1f62d" },
		"😮": { text: "open_mouth", image: "1f62e" },
		"😯": { text: "hushed", image: "1f62f" },
		"😰": { text: "cold_sweat", image: "1f630" },
		"😱": { text: "scream", image: "1f631" },
		"😲": { text: "astonished", image: "1f632" },
		"😳": { text: "flushed", image: "1f633" },
		"😴": { text: "sleeping", image: "1f634" },
		"😵": { text: "dizzy_face", image: "1f635" },
		"😶": { text: "no_mouth", image: "1f636" },
		"😷": { text: "mask", image: "1f637" },
		"😸": { text: "smile_cat", image: "1f638" },
		"😹": { text: "joy_cat", image: "1f639" },
		"😺": { text: "smiley_cat", image: "1f63a" },
		"😻": { text: "heart_eyes_cat", image: "1f63b" },
		"😼": { text: "smirk_cat", image: "1f63c" },
		"😽": { text: "kissing_cat", image: "1f63d" },
		"😾": { text: "pouting_cat", image: "1f63e" },
		"😿": { text: "crying_cat_face", image: "1f63f" },
		"🙀": { text: "scream_cat", image: "1f640" },
		"🙅": { text: "no_good", image: "1f645" },
		"🙆": { text: "ok_woman", image: "1f646" },
		"🙇": { text: "bow", image: "1f647" },
		"🙈": { text: "see_no_evil", image: "1f648" },
		"🙉": { text: "hear_no_evil", image: "1f649" },
		"🙊": { text: "speak_no_evil", image: "1f64a" },
		"🙋": { text: "raising_hand", image: "1f64b" },
		"🙌": { text: "raised_hands", image: "1f64c" },
		"🙍": { text: "person_frowning", image: "1f64d" },
		"🙎": { text: "person_with_pouting_face", image: "1f64e" },
		"🙏": { text: "pray", image: "1f64f" },
		"🚀": { text: "rocket", image: "1f680" },
		"🚁": { text: "helicopter", image: "1f681" },
		"🚂": { text: "steam_locomotive", image: "1f682" },
		"🚃": { text: "railway_car", image: "1f683" },
		"🚄": { text: "bullettrain_side", image: "1f684" },
		"🚅": { text: "bullettrain_front", image: "1f685" },
		"🚆": { text: "train2", image: "1f686" },
		"🚇": { text: "metro", image: "1f687" },
		"🚈": { text: "light_rail", image: "1f688" },
		"🚉": { text: "station", image: "1f689" },
		"🚊": { text: "tram", image: "1f68a" },
		"🚋": { text: "train", image: "1f68b" },
		"🚌": { text: "bus", image: "1f68c" },
		"🚍": { text: "oncoming_bus", image: "1f68d" },
		"🚎": { text: "trolleybus", image: "1f68e" },
		"🚏": { text: "busstop", image: "1f68f" },
		"🚐": { text: "minibus", image: "1f690" },
		"🚑": { text: "ambulance", image: "1f691" },
		"🚒": { text: "fire_engine", image: "1f692" },
		"🚓": { text: "police_car", image: "1f693" },
		"🚔": { text: "oncoming_police_car", image: "1f694" },
		"🚕": { text: "taxi", image: "1f695" },
		"🚖": { text: "oncoming_taxi", image: "1f696" },
		"🚗": { text: "red_car", image: "1f697" },
		"🚘": { text: "oncoming_automobile", image: "1f698" },
		"🚙": { text: "blue_car", image: "1f699" },
		"🚚": { text: "truck", image: "1f69a" },
		"🚛": { text: "articulated_lorry", image: "1f69b" },
		"🚜": { text: "tractor", image: "1f69c" },
		"🚝": { text: "monorail", image: "1f69d" },
		"🚞": { text: "mountain_railway", image: "1f69e" },
		"🚟": { text: "suspension_railway", image: "1f69f" },
		"🚠": { text: "mountain_cableway", image: "1f6a0" },
		"🚡": { text: "aerial_tramway", image: "1f6a1" },
		"🚢": { text: "ship", image: "1f6a2" },
		"🚣": { text: "rowboat", image: "1f6a3" },
		"🚤": { text: "speedboat", image: "1f6a4" },
		"🚥": { text: "traffic_light", image: "1f6a5" },
		"🚦": { text: "vertical_traffic_light", image: "1f6a6" },
		"🚧": { text: "construction", image: "1f6a7" },
		"🚨": { text: "rotating_light", image: "1f6a8" },
		"🚩": { text: "triangular_flag_on_post", image: "1f6a9" },
		"🚪": { text: "door", image: "1f6aa" },
		"🚫": { text: "no_entry_sign", image: "1f6ab" },
		"🚬": { text: "smoking", image: "1f6ac" },
		"🚭": { text: "no_smoking", image: "1f6ad" },
		"🚮": { text: "put_litter_in_its_place", image: "1f6ae" },
		"🚯": { text: "do_not_litter", image: "1f6af" },
		"🚰": { text: "potable_water", image: "1f6b0" },
		"🚱": { text: "non_potable_water", image: "1f6b1" },
		"🚲": { text: "bike", image: "1f6b2" },
		"🚳": { text: "no_bicycles", image: "1f6b3" },
		"🚴": { text: "bicyclist", image: "1f6b4" },
		"🚵": { text: "mountain_bicyclist", image: "1f6b5" },
		"🚶": { text: "walking", image: "1f6b6" },
		"🚷": { text: "no_pedestrians", image: "1f6b7" },
		"🚸": { text: "children_crossing", image: "1f6b8" },
		"🚹": { text: "mens", image: "1f6b9" },
		"🚺": { text: "womens", image: "1f6ba" },
		"🚻": { text: "restroom", image: "1f6bb" },
		"🚼": { text: "baby_symbol", image: "1f6bc" },
		"🚽": { text: "toilet", image: "1f6bd" },
		"🚾": { text: "wc", image: "1f6be" },
		"🚿": { text: "shower", image: "1f6bf" },
		"🛀": { text: "bath", image: "1f6c0" },
		"🛁": { text: "bathtub", image: "1f6c1" },
		"🛂": { text: "passport_control", image: "1f6c2" },
		"🛃": { text: "customs", image: "1f6c3" },
		"🛄": { text: "baggage_claim", image: "1f6c4" },
		"🛅": { text: "left_luggage", image: "1f6c5" }
	} as { [key: string]: any },
	shorcuts: {
		"&gt;:(": ":angry:",
		"&gt;:-(": ":angry:",
		"&gt;=(": ":angry:",
		"&gt;=-(": ":angry:",
		":\")": ":blush:",
		":-\")": ":blush:",
		"=\")": ":blush:",
		"=-\")": ":blush:",
		"&lt;/3": ":broken_heart:",
		"&lt;\\3": ":broken_heart:",
		":\\": ":/",
		":-\\": ":/",
		":-/": ":/",
		"=-\\": ":/",
		"=-/": ":/",
		":&#39;(": ":cry:",
		":&#39;-(": ":cry:",
		":,(": ":cry:",
		":,-(": ":cry:",
		"=&#39;(": ":cry:",
		"=&#39;-(": ":cry:",
		"=,(": ":cry:",
		"=,-(": ":cry:",
		":-(": ":(",
		"=(": ":(",
		"=-(": ":(",
		":b": ":B",
		"&lt;3": "<3",
		"(l)": "<3",
		"(L)": "<3",
		"]:(": ":imp:",
		"]:-(": ":imp:",
		"]=(": ":imp:",
		"]=-(": ":imp:",
		"o:)": ":innocent:",
		"O:)": ":innocent:",
		"o:-)": ":innocent:",
		"O:-)": ":innocent:",
		"0:)": ":innocent:",
		"0:-)": ":innocent:",
		"o=)": ":innocent:",
		"O=)": ":innocent:",
		"o=-)": ":innocent:",
		"O=-)": ":innocent:",
		"0=)": ":innocent:",
		"0=-)": ":innocent:",
		":&#39;)": ":joy:",
		":&#39;-)": ":joy:",
		":,)": ":joy:",
		":,-)": ":joy:",
		":&#39;D": ":joy:",
		":&#39;-D": ":joy:",
		":,D": ":joy:",
		":,-D": ":joy:",
		"=&#39;)": ":joy:",
		"=&#39;-)": ":joy:",
		"=,)": ":joy:",
		"=,-)": ":joy:",
		"=&#39;D": ":joy:",
		"=&#39;-D": ":joy:",
		"=,D": ":joy:",
		"=,-D": ":joy:",
		":*": ":kissing:",
		":-*": ":kissing:",
		"=*": ":kissing:",
		"=-*": ":kissing:",
		"x-)": ":laughing:",
		"X-)": ":laughing:",
		":|": ":neutral_face:",
		":-|": ":neutral_face:",
		"=|": ":neutral_face:",
		"=-|": ":neutral_face:",
		":o": ":O",
		":-o": ":O",
		":-O": ":O",
		"=o": ":O",
		"=-o": ":O",
		"=O": ":O",
		"=-O": ":O",
		":@": ":rage:",
		":-@": ":rage:",
		"=@": ":rage:",
		"=-@": ":rage:",
		":-D": ":D",
		"=D": ":D",
		"=-D": ":D",
		":-)": ":)",
		"=)": ":)",
		"=-)": ":)",
		":]": ":)",
		":-]": ":)",
		"=]": ":)",
		"=-]": ":)",
		"]:)": ":smiling_imp:",
		"]:-)": ":smiling_imp:",
		"]=)": ":smiling_imp:",
		"]=-)": ":smiling_imp:",
		":,&#39;(": ":sob:",
		":,&#39;-(": ":sob:",
		";(": ":sob:",
		";-(": ":sob:",
		"=,&#39;(": ":sob:",
		"=,&#39;-(": ":sob:",
		":-P": ":P",
		"=P": ":P",
		"=-P": ":P",
		":p": ":P",
		":-p": ":P",
		"=p": ":P",
		"=-p": ":P",
		"8-)": ":sunglasses:",
		"B-)": ":sunglasses:",
		",:(": ":sweat:",
		",:-(": ":sweat:",
		",=(": ":sweat:",
		",=-(": ":sweat:",
		",:)": ":sweat_smile:",
		",:-)": ":sweat_smile:",
		",=)": ":sweat_smile:",
		",=-)": ":sweat_smile:",
		":s": ":unamused:",
		":-S": ":unamused:",
		":z": ":unamused:",
		":-Z": ":unamused:",
		":$": ":unamused:",
		":-$": ":unamused:",
		"=s": ":unamused:",
		"=-S": ":unamused:",
		"=z": ":unamused:",
		"=-Z": ":unamused:",
		"=$": ":unamused:",
		"=-$": ":unamused:",
		";-)": ";)"
	} as { [key: string]: string },
	custom: {
		":O": "open_mouth",
		":D": "grinning",
		"<3": "heart",
		":)": "smile",
		":/": "confused",
		";)": "wink",
		":(": "frowning",
		":P": "stuck_out_tongue",
		"(lama)": "lama",
		":B": "grimacing",
		"(lucky)": "clover"
	} as { [key: string]: string },
	categories_formatted: [] as any,
	categories: [
		{ icon: "1f600", emojis: [":O", ":D",	"<3", ":)",	":/", ";)", ":(", ":P",	"(lama)",":B",
		"(lucky)", "😀", "😬", "😁", "😂", "😃", "😄", "😅", "😆", "😇", "😉", "😊", "☺", "😋", "😌", "😍", "😘", "😗", "😙", "😚", "😜", "😝", "😛", "😎", "😏", "😶", "😐", "😑", "😒", "😳", "😞", "😟", "😠", "😡", "😔", "😕", "😣", "😖", "😫", "😩", "😤", "😮", "😱", "😨", "😰", "😯", "😦", "😧", "😢", "😥", "😪", "😓", "😭", "😵", "😲", "😷", "😴", "💤", "💩", "😈", "👿", "👹", "👺", "💀", "👻", "👽", "😺", "😸", "😹", "😻", "😼", "😽", "🙀", "😿", "😾", "🙌", "👏", "👋", "👍", "👎", "👊", "✊", "✌", "👌", "✋", "👐", "💪", "🙏", "☝", "👆", "👇", "👈", "👉", "💅", "👄", "👅", "👂", "👃", "👀", "👤", "👥", "👶", "👦", "👧", "👨", "👩", "👱", "👴", "👲", "👳", "👮", "👷", "💂", "🎅", "👼", "👸", "👰", "🚶", "🏃", "💃", "👯", "👫", "👬", "👭", "🙇", "💁", "🙅", "🙆", "🙋", "🙎", "🙍", "💇", "💆", "💑", "👩‍❤️‍👩", "👨‍❤️‍👨", "💏", "👩‍❤️‍💋‍👩", "👨‍❤️‍💋‍👨", "👪", "👨‍👩‍👧", "👨‍👩‍👧‍👦", "👨‍👩‍👦‍👦", "👨‍👩‍👧‍👧", "👩‍👩‍👦", "👩‍👩‍👧", "👩‍👩‍👧‍👦", "👩‍👩‍👦‍👦", "👩‍👩‍👧‍👧", "👨‍👨‍👦", "👨‍👨‍👧", "👨‍👨‍👧‍👦", "👨‍👨‍👦‍👦", "👨‍👨‍👧‍👧", "👚", "👕", "👖", "👔", "👗", "👙", "👘", "💄", "💋", "👣", "👠", "👡", "👢", "👞", "👟", "👒", "🎩", "🎓", "👑", "🎒", "👝", "👛", "👜", "💼", "👓", "💍", "🌂"] },
		{ icon: "1f433", emojis: ["🐶", "🐱", "🐭", "🐹", "🐰", "🐻", "🐼", "🐨", "🐯", "🐮", "🐷", "🐽", "🐸", "🐙", "🐵", "🙈", "🙉", "🙊", "🐒", "🐔", "🐧", "🐦", "🐤", "🐣", "🐥", "🐺", "🐗", "🐴", "🐝", "🐛", "🐌", "🐞", "🐜", "🐍", "🐢", "🐠", "🐟", "🐡", "🐬", "🐳", "🐋", "🐊", "🐆", "🐅", "🐃", "🐂", "🐄", "🐪", "🐫", "🐘", "🐐", "🐏", "🐑", "🐎", "🐖", "🐀", "🐁", "🐓", "🐕", "🐩", "🐈", "🐇", "🐉", "🐲", "🌵", "🎄", "🌲", "🌳", "🌴", "🌱", "🌿", "🍀", "🎍", "🎋", "🍃", "🍂", "🍁", "🌾", "🌺", "🌻", "🌹", "🌷", "🌼", "🌸", "💐", "🍄", "🌰", "🎃", "🐚", "🌎", "🌍", "🌏", "🌕", "🌖", "🌗", "🌘", "🌑", "🌒", "🌓", "🌔", "🌚", "🌝", "🌛", "🌜", "🌞", "🌙", "⭐", "🌟", "💫", "✨", "☀", "⛅", "☁", "⚡", "💥", "❄", "⛄", "💨", "☔", "💧", "💦", "🌊"] },
		{ icon: "1f34e", emojis: ["🍏", "🍎", "🍐", "🍊", "🍋", "🍌", "🍉", "🍇", "🍓", "🍈", "🍒", "🍑", "🍍", "🍅", "🍆", "🌽", "🍠", "🍯", "🍞", "🍗", "🍖", "🍤", "🍳", "🍔", "🍟", "🍕", "🍝", "🍜", "🍲", "🍥", "🍣", "🍱", "🍛", "🍙", "🍚", "🍘", "🍢", "🍡", "🍧", "🍨", "🍦", "🍰", "🎂", "🍮", "🍬", "🍭", "🍫", "🍩", "🍪", "🍺", "🍻", "🍷", "🍸", "🍹", "🍶", "🍵", "☕", "🍼", "🍴"] }, 
		{ icon: "26bd", emojis: ["⚽", "🏀", "🏈", "⚾", "🎾", "🏉", "🎱", "⛳", "🎿", "🏂", "🎣", "🚣", "🏊", "🏄", "🛀", "🚴", "🚵", "🏇", "🏆", "🎽", "🎫", "🎭", "🎨", "🎪", "🎤", "🎧", "🎼", "🎹", "🎷", "🎺", "🎸", "🎻", "🎬", "🎮", "👾", "🎯", "🎲", "🎰", "🎳"] }, 
		{ icon: "1f699", "emojis": ["🚗", "🚕", "🚙", "🚌", "🚎", "🚓", "🚑", "🚒", "🚐", "🚚", "🚛", "🚜", "🚲", "🚨", "🚔", "🚍", "🚘", "🚖", "🚡", "🚠", "🚟", "🚃", "🚋", "🚝", "🚄", "🚅", "🚈", "🚞", "🚂", "🚆", "🚇", "🚊", "🚉", "🚁", "✈", "⛵", "🚤", "🚀", "💺", "⚓", "🚧", "⛽", "🚏", "🚦", "🚥", "🏁", "🚢", "🎡", "🎢", "🎠", "🌁", "🗼", "🏭", "⛲", "🎑", "🗻", "🌋", "🗾", "⛺", "🌅", "🌄", "🌠", "🌆", "🌃", "🌉", "🌌", "🌠", "🎇", "🎆", "🌈", "🏰", "🏯", "🗽", "🏠", "🏡", "🏢", "🏬", "🏣", "🏤", "🏥", "🏦", "🏨", "🏪", "🏫", "🏩", "💒", "⛪"] }, 
		{ icon: "1f4f1", emojis: ["⌚", "📱", "📲", "💻", "💽", "💾", "💿", "📀", "📼", "📷", "📹", "🎥", "📞", "☎", "📟", "📠", "📺", "📻", "⏰", "⏳", "⌛", "📡", "🔋", "🔌", "💡", "🔦", "💸", "💵", "💴", "💶", "💷", "💰", "💳", "💎", "🔧", "🔨", "🔩", "🔫", "💣", "🔪", "🚬", "🔮", "💈", "🔭", "🔬", "💊", "💉", "🔖", "🚽", "🚿", "🛁", "🔑", "🚪", "🗿", "🎈", "🎏", "🎀", "🎁", "🎊", "🎉", "🎎", "🎐", "🎌", "🏮", "✉", "📩", "📨", "📧", "💌", "📮", "📪", "📫", "📬", "📭", "📦", "📯", "📥", "📤", "📜", "📃", "📑", "📊", "📈", "📉", "📄", "📅", "📆", "📇", "📋", "📁", "📂", "📰", "📓", "📕", "📗", "📘", "📙", "📔", "📒", "📚", "📖", "🔗", "📎", "✂", "📐", "📏", "📌", "📍", "🚩", "🔐", "🔒", "🔓", "🔏", "✒", "📝", "✏", "🔍", "🔎"] }, 
		{ icon: "2764", emojis: ["💯", "🔢", "❤", "💛", "💚", "💙", "💜", "💔", "💕", "💞", "💓", "💗", "💖", "💘", "💝", "💟", "🔯", "⛎", "♈", "♉", "♊", "♋", "♌", "♍", "♎", "♏", "♐", "♑", "♒", "♓", "🆔", "🈳", "🈹", "📴", "📳", "🈶", "🈚", "🈸", "🈺", "🈷", "✴", "🆚", "🉑", "💮", "🉐", "㊙", "㊗", "🈴", "🈵", "🈲", "🅰", "🅱", "🆎", "🆑", "🅾", "🆘", "⛔", "📛", "🚫", "❌", "⭕", "💢", "♨", "🚷", "🚯", "🚳", "🚱", "🔞", "📵", "❗", "❕", "❓", "❔", "‼", "⁉", "🔅", "🔆", "🔱", "〽", "⚠", "🚸", "🔰", "♻", "🈯", "💹", "❇", "✳", "❎", "✅", "💠", "🌀", "➿", "🌐", "Ⓜ", "🏧", "🈂", "🛂", "🛃", "🛄", "🛅", "♿", "🚭", "🚾", "🅿", "🚰", "🚹", "🚺", "🚼", "🚻", "🚮", "🎦", "📶", "🈁", "🆖", "🆗", "🆙", "🆒", "🆕", "🆓", "0⃣", "1⃣", "2⃣", "3⃣", "4⃣", "5⃣", "6⃣", "7⃣", "8⃣", "9⃣", "🔟", "▶", "⏩", "⏪", "🔀", "🔁", "🔂", "◀", "🔼", "🔽", "⏫", "⏬", "➡", "⬅", "⬆", "⬇", "↗", "↘", "↙", "↖", "↕", "↔", "🔄", "↪", "↩", "⤴", "⤵", "#⃣", "ℹ", "🔤", "🔡", "🔠", "🔣", "🎵", "🎶", "〰", "➰", "✔", "🔃", "➕", "➖", "➗", "✖", "💲", "💱", "©", "®", "™", "🔚", "🔙", "🔛", "🔝", "🔜", "☑", "🔘", "⚪", "⚫", "🔴", "🔵", "🔸", "🔹", "🔶", "🔷", "🔺", "▪", "▫", "⬛", "⬜", "🔻", "◼", "◻", "◾", "◽", "🔲", "🔳", "🔈", "🔉", "🔊", "🔇", "📣", "📢", "🔔", "🔕", "🃏", "🀄", "♠", "♣", "♥", "♦", "🎴", "💭", "💬", "🕐", "🕑", "🕒", "🕓", "🕔", "🕕", "🕖", "🕗", "🕘", "🕙", "🕚", "🕛", "🕜", "🕝", "🕞", "🕟", "🕠", "🕡", "🕢", "🕣", "🕤", "🕥", "🕦", "🕧", "🇿", "🇾", "🇽", "🇼", "🇻", "🇺", "🇹", "🇸", "🇷", "🇶", "🇵", "🇴", "🇳", "🇲", "🇱", "🇰", "🇯", "🇮", "🇭", "🇬", "🇫", "🇪", "🇩", "🇨", "🇧", "🇦"] }, 
		{ icon: "1f1eb-1f1f7", "emojis": ["🇦🇨", "🇦🇫", "🇦🇱", "🇩🇿", "🇦🇩", "🇦🇴", "🇦🇮", "🇦🇬", "🇦🇷", "🇦🇲", "🇦🇼", "🇦🇺", "🇦🇹", "🇦🇿", "🇧🇸", "🇧🇭", "🇧🇩", "🇧🇧", "🇧🇾", "🇧🇪", "🇧🇿", "🇧🇯", "🇧🇲", "🇧🇹", "🇧🇴", "🇧🇦", "🇧🇼", "🇧🇷", "🇧🇳", "🇧🇬", "🇧🇫", "🇧🇮", "🇨🇻", "🇰🇭", "🇨🇲", "🇨🇦", "🇰🇾", "🇨🇫", "🇹🇩", "🇨🇱", "🇨🇳", "🇨🇴", "🇰🇲", "🇨🇬", "🇨🇩", "🇨🇷", "🇭🇷", "🇨🇺", "🇨🇾", "🇨🇿", "🇩🇰", "🇩🇯", "🇩🇲", "🇩🇴", "🇪🇨", "🇪🇬", "🇸🇻", "🇬🇶", "🇪🇷", "🇪🇪", "🇪🇹", "🇫🇰", "🇫🇴", "🇫🇯", "🇫🇮", "🇫🇷", "🇵🇫", "🇬🇦", "🇬🇲", "🇬🇪", "🇩🇪", "🇬🇭", "🇬🇮", "🇬🇷", "🇬🇱", "🇬🇩", "🇬🇺", "🇬🇹", "🇬🇳", "🇬🇼", "🇬🇾", "🇭🇹", "🇭🇳", "🇭🇰", "🇭🇺", "🇮🇸", "🇮🇳", "🇮🇩", "🇮🇷", "🇮🇶", "🇮🇪", "🇮🇱", "🇮🇹", "🇨🇮", "🇯🇲", "🇯🇵", "🇯🇪", "🇯🇴", "🇰🇿", "🇰🇪", "🇰🇮", "🇽🇰", "🇰🇼", "🇰🇬", "🇱🇦", "🇱🇻", "🇱🇧", "🇱🇸", "🇱🇷", "🇱🇾", "🇱🇮", "🇱🇹", "🇱🇺", "🇲🇴", "🇲🇰", "🇲🇬", "🇲🇼", "🇲🇾", "🇲🇻", "🇲🇱", "🇲🇹", "🇲🇭", "🇲🇷", "🇲🇺", "🇲🇽", "🇫🇲", "🇲🇩", "🇲🇨", "🇲🇳", "🇲🇪", "🇲🇸", "🇲🇦", "🇲🇿", "🇲🇲", "🇳🇦", "🇳🇷", "🇳🇵", "🇳🇱", "🇳🇨", "🇳🇿", "🇳🇮", "🇳🇪", "🇳🇬", "🇳🇺", "🇰🇵", "🇳🇴", "🇴🇲", "🇵🇰", "🇵🇼", "🇵🇸", "🇵🇦", "🇵🇬", "🇵🇾", "🇵🇪", "🇵🇭", "🇵🇱", "🇵🇹", "🇵🇷", "🇶🇦", "🇷🇴", "🇷🇺", "🇷🇼", "🇸🇭", "🇰🇳", "🇱🇨", "🇻🇨", "🇼🇸", "🇸🇲", "🇸🇹", "🇸🇦", "🇸🇳", "🇷🇸", "🇸🇨", "🇸🇱", "🇸🇬", "🇸🇰", "🇸🇮", "🇸🇧", "🇸🇴", "🇿🇦", "🇰🇷", "🇪🇸", "🇱🇰", "🇸🇩", "🇸🇷", "🇸🇿", "🇸🇪", "🇨🇭", "🇸🇾", "🇹🇼", "🇹🇯", "🇹🇿", "🇹🇭", "🇹🇱", "🇹🇬", "🇹🇴", "🇹🇹", "🇹🇳", "🇹🇷", "🇹🇲", "🇹🇻", "🇺🇬", "🇺🇦", "🇦🇪", "🇬🇧", "🇺🇸", "🇻🇮", "🇺🇾", "🇺🇿", "🇻🇺", "🇻🇦", "🇻🇪", "🇻🇳", "🇼🇫", "🇪🇭", "🇾🇪", "🇿🇲", "🇿🇼", "🇷🇪", "🇦🇽", "🇹🇦", "🇮🇴", "🇧🇶", "🇨🇽", "🇨🇨", "🇬🇬", "🇮🇲", "🇾🇹", "🇳🇫", "🇵🇳", "🇧🇱", "🇵🇲", "🇬🇸", "🇹🇰", "🇧🇻", "🇭🇲", "🇸🇯", "🇺🇲", "🇮🇨", "🇪🇦", "🇨🇵", "🇩🇬", "🇦🇸", "🇦🇶", "🇻🇬", "🇨🇰", "🇨🇼", "🇪🇺", "🇬🇫", "🇹🇫", "🇬🇵", "🇲🇶", "🇲🇵", "🇸🇽", "🇸🇸", "🇹🇨", "🇲🇫", "🏳️‍🌈"] }
	]
}

export { Emojis }