/*
 * Smiley library
 */

var smileys = {
	url: 'https://twemoji.maxcdn.com/2/svg/',
	smileys: {},
	shorcuts: {}
}

// List of smileys
smileys.list = [
	{
		"name": "classic",
		"list": [{
			"name": ":O",
			"image": "open_mouth",
			"custom": true
		}, {
			"name": ":D",
			"image": "smile",
			"custom": true
		}, {
			"name": "<3",
			"image": "heart",
			"custom": true
		}, {
			"name": ":)",
			"image": "smile",
			"custom": true
		}, {
			"name": ":/",
			"image": "confused",
			"custom": true
		}, {
			"name": ";)",
			"image": "wink",
			"custom": true
		}, {
			"name": ":(",
			"image": "frowning",
			"custom": true
		}, {
			"name": ":P",
			"image": "stuck_out_tongue",
			"custom": true
		}, {
			"name": "(lama)",
			"image": "lama",
			"custom": true
		}, {
			"name": ":B",
			"image": "grimacing",
			"custom": true
		}, {
			"name": "(lucky)",
			"image": "clover",
			"custom": true
		}]
	}, {
		"name": "people",
		"list": [{
			"name": ":grinning:",
			"image": "1f600"
		}, {
			"name": ":grimacing:",
			"image": "1f62c"
		}, {
			"name": ":grin:",
			"image": "1f601"
		}, {
			"name": ":joy:",
			"image": "1f602"
		}, {
			"name": ":smiley:",
			"image": "1f603"
		}, {
			"name": ":smile:",
			"image": "1f604"
		}, {
			"name": ":sweat_smile:",
			"image": "1f605"
		}, {
			"name": ":laughing:",
			"image": "1f606"
		}, {
			"name": ":innocent:",
			"image": "1f607"
		}, {
			"name": ":wink:",
			"image": "1f609"
		}, {
			"name": ":blush:",
			"image": "1f60a"
		}, {
			"name": ":relaxed:",
			"image": "263a"
		}, {
			"name": ":yum:",
			"image": "1f60b"
		}, {
			"name": ":relieved:",
			"image": "1f60c"
		}, {
			"name": ":heart_eyes:",
			"image": "1f60d"
		}, {
			"name": ":kissing_heart:",
			"image": "1f618"
		}, {
			"name": ":kissing:",
			"image": "1f617"
		}, {
			"name": ":kissing_smiling_eyes:",
			"image": "1f619"
		}, {
			"name": ":kissing_closed_eyes:",
			"image": "1f61a"
		}, {
			"name": ":stuck_out_tongue_winking_eye:",
			"image": "1f61c"
		}, {
			"name": ":stuck_out_tongue_closed_eyes:",
			"image": "1f61d"
		}, {
			"name": ":stuck_out_tongue:",
			"image": "1f61b"
		}, {
			"name": ":sunglasses:",
			"image": "1f60e"
		}, {
			"name": ":smirk:",
			"image": "1f60f"
		}, {
			"name": ":no_mouth:",
			"image": "1f636"
		}, {
			"name": ":neutral_face:",
			"image": "1f610"
		}, {
			"name": ":expressionless:",
			"image": "1f611"
		}, {
			"name": ":unamused:",
			"image": "1f612"
		}, {
			"name": ":flushed:",
			"image": "1f633"
		}, {
			"name": ":disappointed:",
			"image": "1f61e"
		}, {
			"name": ":worried:",
			"image": "1f61f"
		}, {
			"name": ":angry:",
			"image": "1f620"
		}, {
			"name": ":rage:",
			"image": "1f621"
		}, {
			"name": ":pensive:",
			"image": "1f614"
		}, {
			"name": ":confused:",
			"image": "1f615"
		}, {
			"name": ":persevere:",
			"image": "1f623"
		}, {
			"name": ":confounded:",
			"image": "1f616"
		}, {
			"name": ":tired_face:",
			"image": "1f62b"
		}, {
			"name": ":weary:",
			"image": "1f629"
		}, {
			"name": ":triumph:",
			"image": "1f624"
		}, {
			"name": ":open_mouth:",
			"image": "1f62e"
		}, {
			"name": ":scream:",
			"image": "1f631"
		}, {
			"name": ":fearful:",
			"image": "1f628"
		}, {
			"name": ":cold_sweat:",
			"image": "1f630"
		}, {
			"name": ":hushed:",
			"image": "1f62f"
		}, {
			"name": ":frowning:",
			"image": "1f626"
		}, {
			"name": ":anguished:",
			"image": "1f627"
		}, {
			"name": ":cry:",
			"image": "1f622"
		}, {
			"name": ":disappointed_relieved:",
			"image": "1f625"
		}, {
			"name": ":sleepy:",
			"image": "1f62a"
		}, {
			"name": ":sweat:",
			"image": "1f613"
		}, {
			"name": ":sob:",
			"image": "1f62d"
		}, {
			"name": ":dizzy_face:",
			"image": "1f635"
		}, {
			"name": ":astonished:",
			"image": "1f632"
		}, {
			"name": ":mask:",
			"image": "1f637"
		}, {
			"name": ":sleeping:",
			"image": "1f634"
		}, {
			"name": ":zzz:",
			"image": "1f4a4"
		}, {
			"name": ":poop:",
			"image": "1f4a9"
		}, {
			"name": ":smiling_imp:",
			"image": "1f608"
		}, {
			"name": ":imp:",
			"image": "1f47f"
		}, {
			"name": ":japanese_ogre:",
			"image": "1f479"
		}, {
			"name": ":japanese_goblin:",
			"image": "1f47a"
		}, {
			"name": ":skull:",
			"image": "1f480"
		}, {
			"name": ":ghost:",
			"image": "1f47b"
		}, {
			"name": ":alien:",
			"image": "1f47d"
		}, {
			"name": ":smiley_cat:",
			"image": "1f63a"
		}, {
			"name": ":smile_cat:",
			"image": "1f638"
		}, {
			"name": ":joy_cat:",
			"image": "1f639"
		}, {
			"name": ":heart_eyes_cat:",
			"image": "1f63b"
		}, {
			"name": ":smirk_cat:",
			"image": "1f63c"
		}, {
			"name": ":kissing_cat:",
			"image": "1f63d"
		}, {
			"name": ":scream_cat:",
			"image": "1f640"
		}, {
			"name": ":crying_cat_face:",
			"image": "1f63f"
		}, {
			"name": ":pouting_cat:",
			"image": "1f63e"
		}, {
			"name": ":raised_hands:",
			"image": "1f64c"
		}, {
			"name": ":clap:",
			"image": "1f44f"
		}, {
			"name": ":wave:",
			"image": "1f44b"
		}, {
			"name": ":thumbsup:",
			"image": "1f44d"
		}, {
			"name": ":thumbsdown:",
			"image": "1f44e"
		}, {
			"name": ":punch:",
			"image": "1f44a"
		}, {
			"name": ":fist:",
			"image": "270a"
		}, {
			"name": ":v:",
			"image": "270c"
		}, {
			"name": ":ok_hand:",
			"image": "1f44c"
		}, {
			"name": ":raised_hand:",
			"image": "270b"
		}, {
			"name": ":open_hands:",
			"image": "1f450"
		}, {
			"name": ":muscle:",
			"image": "1f4aa"
		}, {
			"name": ":pray:",
			"image": "1f64f"
		}, {
			"name": ":point_up:",
			"image": "261d"
		}, {
			"name": ":point_up_2:",
			"image": "1f446"
		}, {
			"name": ":point_down:",
			"image": "1f447"
		}, {
			"name": ":point_left:",
			"image": "1f448"
		}, {
			"name": ":point_right:",
			"image": "1f449"
		}, {
			"name": ":nail_care:",
			"image": "1f485"
		}, {
			"name": ":lips:",
			"image": "1f444"
		}, {
			"name": ":tongue:",
			"image": "1f445"
		}, {
			"name": ":ear:",
			"image": "1f442"
		}, {
			"name": ":nose:",
			"image": "1f443"
		}, {
			"name": ":eyes:",
			"image": "1f440"
		}, {
			"name": ":bust_in_silhouette:",
			"image": "1f464"
		}, {
			"name": ":busts_in_silhouette:",
			"image": "1f465"
		}, {
			"name": ":baby:",
			"image": "1f476"
		}, {
			"name": ":boy:",
			"image": "1f466"
		}, {
			"name": ":girl:",
			"image": "1f467"
		}, {
			"name": ":man:",
			"image": "1f468"
		}, {
			"name": ":woman:",
			"image": "1f469"
		}, {
			"name": ":person_with_blond_hair:",
			"image": "1f471"
		}, {
			"name": ":older_man:",
			"image": "1f474"
		}, {
			"name": ":older_woman:",
			"image": "1f475"
		}, {
			"name": ":man_with_gua_pi_mao:",
			"image": "1f472"
		}, {
			"name": ":man_with_turban:",
			"image": "1f473"
		}, {
			"name": ":cop:",
			"image": "1f46e"
		}, {
			"name": ":construction_worker:",
			"image": "1f477"
		}, {
			"name": ":guardsman:",
			"image": "1f482"
		}, {
			"name": ":santa:",
			"image": "1f385"
		}, {
			"name": ":angel:",
			"image": "1f47c"
		}, {
			"name": ":princess:",
			"image": "1f478"
		}, {
			"name": ":bride_with_veil:",
			"image": "1f470"
		}, {
			"name": ":walking:",
			"image": "1f6b6"
		}, {
			"name": ":runner:",
			"image": "1f3c3"
		}, {
			"name": ":dancer:",
			"image": "1f483"
		}, {
			"name": ":dancers:",
			"image": "1f46f"
		}, {
			"name": ":couple:",
			"image": "1f46b"
		}, {
			"name": ":two_men_holding_hands:",
			"image": "1f46c"
		}, {
			"name": ":two_women_holding_hands:",
			"image": "1f46d"
		}, {
			"name": ":bow:",
			"image": "1f647"
		}, {
			"name": ":information_desk_person:",
			"image": "1f481"
		}, {
			"name": ":no_good:",
			"image": "1f645"
		}, {
			"name": ":ok_woman:",
			"image": "1f646"
		}, {
			"name": ":raising_hand:",
			"image": "1f64b"
		}, {
			"name": ":person_with_pouting_face:",
			"image": "1f64e"
		}, {
			"name": ":person_frowning:",
			"image": "1f64d"
		}, {
			"name": ":haircut:",
			"image": "1f487"
		}, {
			"name": ":massage:",
			"image": "1f486"
		}, {
			"name": ":couple_with_heart:",
			"image": "1f491"
		}, {
			"name": ":couple_ww:",
			"image": "1f469-200d-2764-fe0f-200d-1f469"
		}, {
			"name": ":couple_mm:",
			"image": "1f468-200d-2764-fe0f-200d-1f468"
		}, {
			"name": ":couplekiss:",
			"image": "1f48f"
		}, {
			"name": ":kiss_ww:",
			"image": "1f469-200d-2764-fe0f-200d-1f48b-200d-1f469"
		}, {
			"name": ":kiss_mm:",
			"image": "1f468-200d-2764-fe0f-200d-1f48b-200d-1f468"
		}, {
			"name": ":family:",
			"image": "1f46a"
		}, {
			"name": ":family_mwg:",
			"image": "1f468-200d-1f469-200d-1f467"
		}, {
			"name": ":family_mwgb:",
			"image": "1f468-200d-1f469-200d-1f467-200d-1f466"
		}, {
			"name": ":family_mwbb:",
			"image": "1f468-200d-1f469-200d-1f466-200d-1f466"
		}, {
			"name": ":family_mwgg:",
			"image": "1f468-200d-1f469-200d-1f467-200d-1f467"
		}, {
			"name": ":family_wwb:",
			"image": "1f469-200d-1f469-200d-1f466"
		}, {
			"name": ":family_wwg:",
			"image": "1f469-200d-1f469-200d-1f467"
		}, {
			"name": ":family_wwgb:",
			"image": "1f469-200d-1f469-200d-1f467-200d-1f466"
		}, {
			"name": ":family_wwbb:",
			"image": "1f469-200d-1f469-200d-1f466-200d-1f466"
		}, {
			"name": ":family_wwgg:",
			"image": "1f469-200d-1f469-200d-1f467-200d-1f467"
		}, {
			"name": ":family_mmb:",
			"image": "1f468-200d-1f468-200d-1f466"
		}, {
			"name": ":family_mmg:",
			"image": "1f468-200d-1f468-200d-1f467"
		}, {
			"name": ":family_mmgb:",
			"image": "1f468-200d-1f468-200d-1f467-200d-1f466"
		}, {
			"name": ":family_mmbb:",
			"image": "1f468-200d-1f468-200d-1f466-200d-1f466"
		}, {
			"name": ":family_mmgg:",
			"image": "1f468-200d-1f468-200d-1f467-200d-1f467"
		}, {
			"name": ":womans_clothes:",
			"image": "1f45a"
		}, {
			"name": ":shirt:",
			"image": "1f455"
		}, {
			"name": ":jeans:",
			"image": "1f456"
		}, {
			"name": ":necktie:",
			"image": "1f454"
		}, {
			"name": ":dress:",
			"image": "1f457"
		}, {
			"name": ":bikini:",
			"image": "1f459"
		}, {
			"name": ":kimono:",
			"image": "1f458"
		}, {
			"name": ":lipstick:",
			"image": "1f484"
		}, {
			"name": ":kiss:",
			"image": "1f48b"
		}, {
			"name": ":footprints:",
			"image": "1f463"
		}, {
			"name": ":high_heel:",
			"image": "1f460"
		}, {
			"name": ":sandal:",
			"image": "1f461"
		}, {
			"name": ":boot:",
			"image": "1f462"
		}, {
			"name": ":mans_shoe:",
			"image": "1f45e"
		}, {
			"name": ":athletic_shoe:",
			"image": "1f45f"
		}, {
			"name": ":womans_hat:",
			"image": "1f452"
		}, {
			"name": ":tophat:",
			"image": "1f3a9"
		}, {
			"name": ":mortar_board:",
			"image": "1f393"
		}, {
			"name": ":crown:",
			"image": "1f451"
		}, {
			"name": ":school_satchel:",
			"image": "1f392"
		}, {
			"name": ":pouch:",
			"image": "1f45d"
		}, {
			"name": ":purse:",
			"image": "1f45b"
		}, {
			"name": ":handbag:",
			"image": "1f45c"
		}, {
			"name": ":briefcase:",
			"image": "1f4bc"
		}, {
			"name": ":eyeglasses:",
			"image": "1f453"
		}, {
			"name": ":ring:",
			"image": "1f48d"
		}, {
			"name": ":closed_umbrella:",
			"image": "1f302"
		}]
	}, {
		"name": "nature",
		"list": [{
			"name": ":dog:",
			"image": "1f436"
		}, {
			"name": ":cat:",
			"image": "1f431"
		}, {
			"name": ":mouse:",
			"image": "1f42d"
		}, {
			"name": ":hamster:",
			"image": "1f439"
		}, {
			"name": ":rabbit:",
			"image": "1f430"
		}, {
			"name": ":bear:",
			"image": "1f43b"
		}, {
			"name": ":panda_face:",
			"image": "1f43c"
		}, {
			"name": ":koala:",
			"image": "1f428"
		}, {
			"name": ":tiger:",
			"image": "1f42f"
		}, {
			"name": ":cow:",
			"image": "1f42e"
		}, {
			"name": ":pig:",
			"image": "1f437"
		}, {
			"name": ":pig_nose:",
			"image": "1f43d"
		}, {
			"name": ":frog:",
			"image": "1f438"
		}, {
			"name": ":octopus:",
			"image": "1f419"
		}, {
			"name": ":monkey_face:",
			"image": "1f435"
		}, {
			"name": ":see_no_evil:",
			"image": "1f648"
		}, {
			"name": ":hear_no_evil:",
			"image": "1f649"
		}, {
			"name": ":speak_no_evil:",
			"image": "1f64a"
		}, {
			"name": ":monkey:",
			"image": "1f412"
		}, {
			"name": ":chicken:",
			"image": "1f414"
		}, {
			"name": ":penguin:",
			"image": "1f427"
		}, {
			"name": ":bird:",
			"image": "1f426"
		}, {
			"name": ":baby_chick:",
			"image": "1f424"
		}, {
			"name": ":hatching_chick:",
			"image": "1f423"
		}, {
			"name": ":hatched_chick:",
			"image": "1f425"
		}, {
			"name": ":wolf:",
			"image": "1f43a"
		}, {
			"name": ":boar:",
			"image": "1f417"
		}, {
			"name": ":horse:",
			"image": "1f434"
		}, {
			"name": ":bee:",
			"image": "1f41d"
		}, {
			"name": ":bug:",
			"image": "1f41b"
		}, {
			"name": ":snail:",
			"image": "1f40c"
		}, {
			"name": ":beetle:",
			"image": "1f41e"
		}, {
			"name": ":ant:",
			"image": "1f41c"
		}, {
			"name": ":snake:",
			"image": "1f40d"
		}, {
			"name": ":turtle:",
			"image": "1f422"
		}, {
			"name": ":tropical_fish:",
			"image": "1f420"
		}, {
			"name": ":fish:",
			"image": "1f41f"
		}, {
			"name": ":blowfish:",
			"image": "1f421"
		}, {
			"name": ":dolphin:",
			"image": "1f42c"
		}, {
			"name": ":whale:",
			"image": "1f433"
		}, {
			"name": ":whale2:",
			"image": "1f40b"
		}, {
			"name": ":crocodile:",
			"image": "1f40a"
		}, {
			"name": ":leopard:",
			"image": "1f406"
		}, {
			"name": ":tiger2:",
			"image": "1f405"
		}, {
			"name": ":water_buffalo:",
			"image": "1f403"
		}, {
			"name": ":ox:",
			"image": "1f402"
		}, {
			"name": ":cow2:",
			"image": "1f404"
		}, {
			"name": ":dromedary_camel:",
			"image": "1f42a"
		}, {
			"name": ":camel:",
			"image": "1f42b"
		}, {
			"name": ":elephant:",
			"image": "1f418"
		}, {
			"name": ":goat:",
			"image": "1f410"
		}, {
			"name": ":ram:",
			"image": "1f40f"
		}, {
			"name": ":sheep:",
			"image": "1f411"
		}, {
			"name": ":racehorse:",
			"image": "1f40e"
		}, {
			"name": ":pig2:",
			"image": "1f416"
		}, {
			"name": ":rat:",
			"image": "1f400"
		}, {
			"name": ":mouse2:",
			"image": "1f401"
		}, {
			"name": ":rooster:",
			"image": "1f413"
		}, {
			"name": ":dog2:",
			"image": "1f415"
		}, {
			"name": ":poodle:",
			"image": "1f429"
		}, {
			"name": ":cat2:",
			"image": "1f408"
		}, {
			"name": ":rabbit2:",
			"image": "1f407"
		}, {
			"name": ":feet:",
			"image": "1f43e"
		}, {
			"name": ":dragon:",
			"image": "1f409"
		}, {
			"name": ":dragon_face:",
			"image": "1f432"
		}, {
			"name": ":cactus:",
			"image": "1f335"
		}, {
			"name": ":christmas_tree:",
			"image": "1f384"
		}, {
			"name": ":evergreen_tree:",
			"image": "1f332"
		}, {
			"name": ":deciduous_tree:",
			"image": "1f333"
		}, {
			"name": ":palm_tree:",
			"image": "1f334"
		}, {
			"name": ":seedling:",
			"image": "1f331"
		}, {
			"name": ":herb:",
			"image": "1f33f"
		}, {
			"name": ":four_leaf_clover:",
			"image": "1f340"
		}, {
			"name": ":bamboo:",
			"image": "1f38d"
		}, {
			"name": ":tanabata_tree:",
			"image": "1f38b"
		}, {
			"name": ":leaves:",
			"image": "1f343"
		}, {
			"name": ":fallen_leaf:",
			"image": "1f342"
		}, {
			"name": ":maple_leaf:",
			"image": "1f341"
		}, {
			"name": ":ear_of_rice:",
			"image": "1f33e"
		}, {
			"name": ":hibiscus:",
			"image": "1f33a"
		}, {
			"name": ":sunflower:",
			"image": "1f33b"
		}, {
			"name": ":rose:",
			"image": "1f339"
		}, {
			"name": ":tulip:",
			"image": "1f337"
		}, {
			"name": ":blossom:",
			"image": "1f33c"
		}, {
			"name": ":cherry_blossom:",
			"image": "1f338"
		}, {
			"name": ":bouquet:",
			"image": "1f490"
		}, {
			"name": ":mushroom:",
			"image": "1f344"
		}, {
			"name": ":chestnut:",
			"image": "1f330"
		}, {
			"name": ":jack_o_lantern:",
			"image": "1f383"
		}, {
			"name": ":shell:",
			"image": "1f41a"
		}, {
			"name": ":earth_americas:",
			"image": "1f30e"
		}, {
			"name": ":earth_africa:",
			"image": "1f30d"
		}, {
			"name": ":earth_asia:",
			"image": "1f30f"
		}, {
			"name": ":full_moon:",
			"image": "1f315"
		}, {
			"name": ":waning_gibbous_moon:",
			"image": "1f316"
		}, {
			"name": ":last_quarter_moon:",
			"image": "1f317"
		}, {
			"name": ":waning_crescent_moon:",
			"image": "1f318"
		}, {
			"name": ":new_moon:",
			"image": "1f311"
		}, {
			"name": ":waxing_crescent_moon:",
			"image": "1f312"
		}, {
			"name": ":first_quarter_moon:",
			"image": "1f313"
		}, {
			"name": ":waxing_gibbous_moon:",
			"image": "1f314"
		}, {
			"name": ":new_moon_with_face:",
			"image": "1f31a"
		}, {
			"name": ":full_moon_with_face:",
			"image": "1f31d"
		}, {
			"name": ":first_quarter_moon_with_face:",
			"image": "1f31b"
		}, {
			"name": ":last_quarter_moon_with_face:",
			"image": "1f31c"
		}, {
			"name": ":sun_with_face:",
			"image": "1f31e"
		}, {
			"name": ":crescent_moon:",
			"image": "1f319"
		}, {
			"name": ":star:",
			"image": "2b50"
		}, {
			"name": ":star2:",
			"image": "1f31f"
		}, {
			"name": ":dizzy:",
			"image": "1f4ab"
		}, {
			"name": ":sparkles:",
			"image": "2728"
		}, {
			"name": ":sunny:",
			"image": "2600"
		}, {
			"name": ":partly_sunny:",
			"image": "26c5"
		}, {
			"name": ":cloud:",
			"image": "2601"
		}, {
			"name": ":zap:",
			"image": "26a1"
		}, {
			"name": ":fire:",
			"image": "1f525"
		}, {
			"name": ":boom:",
			"image": "1f4a5"
		}, {
			"name": ":snowflake:",
			"image": "2744"
		}, {
			"name": ":snowman:",
			"image": "26c4"
		}, {
			"name": ":dash:",
			"image": "1f4a8"
		}, {
			"name": ":umbrella:",
			"image": "2614"
		}, {
			"name": ":droplet:",
			"image": "1f4a7"
		}, {
			"name": ":sweat_drops:",
			"image": "1f4a6"
		}, {
			"name": ":ocean:",
			"image": "1f30a"
		}]
	}, {
		"name": "food",
		"list": [{
			"name": ":green_apple:",
			"image": "1f34f"
		}, {
			"name": ":apple:",
			"image": "1f34e"
		}, {
			"name": ":pear:",
			"image": "1f350"
		}, {
			"name": ":tangerine:",
			"image": "1f34a"
		}, {
			"name": ":lemon:",
			"image": "1f34b"
		}, {
			"name": ":banana:",
			"image": "1f34c"
		}, {
			"name": ":watermelon:",
			"image": "1f349"
		}, {
			"name": ":grapes:",
			"image": "1f347"
		}, {
			"name": ":strawberry:",
			"image": "1f353"
		}, {
			"name": ":melon:",
			"image": "1f348"
		}, {
			"name": ":cherries:",
			"image": "1f352"
		}, {
			"name": ":peach:",
			"image": "1f351"
		}, {
			"name": ":pineapple:",
			"image": "1f34d"
		}, {
			"name": ":tomato:",
			"image": "1f345"
		}, {
			"name": ":eggplant:",
			"image": "1f346"
		}, {
			"name": ":corn:",
			"image": "1f33d"
		}, {
			"name": ":sweet_potato:",
			"image": "1f360"
		}, {
			"name": ":honey_pot:",
			"image": "1f36f"
		}, {
			"name": ":bread:",
			"image": "1f35e"
		}, {
			"name": ":poultry_leg:",
			"image": "1f357"
		}, {
			"name": ":meat_on_bone:",
			"image": "1f356"
		}, {
			"name": ":fried_shrimp:",
			"image": "1f364"
		}, {
			"name": ":cooking:",
			"image": "1f373"
		}, {
			"name": ":hamburger:",
			"image": "1f354"
		}, {
			"name": ":fries:",
			"image": "1f35f"
		}, {
			"name": ":pizza:",
			"image": "1f355"
		}, {
			"name": ":spaghetti:",
			"image": "1f35d"
		}, {
			"name": ":ramen:",
			"image": "1f35c"
		}, {
			"name": ":stew:",
			"image": "1f372"
		}, {
			"name": ":fish_cake:",
			"image": "1f365"
		}, {
			"name": ":sushi:",
			"image": "1f363"
		}, {
			"name": ":bento:",
			"image": "1f371"
		}, {
			"name": ":curry:",
			"image": "1f35b"
		}, {
			"name": ":rice_ball:",
			"image": "1f359"
		}, {
			"name": ":rice:",
			"image": "1f35a"
		}, {
			"name": ":rice_cracker:",
			"image": "1f358"
		}, {
			"name": ":oden:",
			"image": "1f362"
		}, {
			"name": ":dango:",
			"image": "1f361"
		}, {
			"name": ":shaved_ice:",
			"image": "1f367"
		}, {
			"name": ":ice_cream:",
			"image": "1f368"
		}, {
			"name": ":icecream:",
			"image": "1f366"
		}, {
			"name": ":cake:",
			"image": "1f370"
		}, {
			"name": ":birthday:",
			"image": "1f382"
		}, {
			"name": ":custard:",
			"image": "1f36e"
		}, {
			"name": ":candy:",
			"image": "1f36c"
		}, {
			"name": ":lollipop:",
			"image": "1f36d"
		}, {
			"name": ":chocolate_bar:",
			"image": "1f36b"
		}, {
			"name": ":doughnut:",
			"image": "1f369"
		}, {
			"name": ":cookie:",
			"image": "1f36a"
		}, {
			"name": ":beer:",
			"image": "1f37a"
		}, {
			"name": ":beers:",
			"image": "1f37b"
		}, {
			"name": ":wine_glass:",
			"image": "1f377"
		}, {
			"name": ":cocktail:",
			"image": "1f378"
		}, {
			"name": ":tropical_drink:",
			"image": "1f379"
		}, {
			"name": ":sake:",
			"image": "1f376"
		}, {
			"name": ":tea:",
			"image": "1f375"
		}, {
			"name": ":coffee:",
			"image": "2615"
		}, {
			"name": ":baby_bottle:",
			"image": "1f37c"
		}, {
			"name": ":fork_and_knife:",
			"image": "1f374"
		}]
	}, {
		"name": "activity",
		"list": [{
			"name": ":soccer:",
			"image": "26bd"
		}, {
			"name": ":basketball:",
			"image": "1f3c0"
		}, {
			"name": ":football:",
			"image": "1f3c8"
		}, {
			"name": ":baseball:",
			"image": "26be"
		}, {
			"name": ":tennis:",
			"image": "1f3be"
		}, {
			"name": ":rugby_football:",
			"image": "1f3c9"
		}, {
			"name": ":8ball:",
			"image": "1f3b1"
		}, {
			"name": ":golf:",
			"image": "26f3"
		}, {
			"name": ":ski:",
			"image": "1f3bf"
		}, {
			"name": ":snowboarder:",
			"image": "1f3c2"
		}, {
			"name": ":fishing_pole_and_fish:",
			"image": "1f3a3"
		}, {
			"name": ":rowboat:",
			"image": "1f6a3"
		}, {
			"name": ":swimmer:",
			"image": "1f3ca"
		}, {
			"name": ":surfer:",
			"image": "1f3c4"
		}, {
			"name": ":bath:",
			"image": "1f6c0"
		}, {
			"name": ":bicyclist:",
			"image": "1f6b4"
		}, {
			"name": ":mountain_bicyclist:",
			"image": "1f6b5"
		}, {
			"name": ":horse_racing:",
			"image": "1f3c7"
		}, {
			"name": ":trophy:",
			"image": "1f3c6"
		}, {
			"name": ":running_shirt_with_sash:",
			"image": "1f3bd"
		}, {
			"name": ":ticket:",
			"image": "1f3ab"
		}, {
			"name": ":performing_arts:",
			"image": "1f3ad"
		}, {
			"name": ":art:",
			"image": "1f3a8"
		}, {
			"name": ":circus_tent:",
			"image": "1f3aa"
		}, {
			"name": ":microphone:",
			"image": "1f3a4"
		}, {
			"name": ":headphones:",
			"image": "1f3a7"
		}, {
			"name": ":musical_score:",
			"image": "1f3bc"
		}, {
			"name": ":musical_keyboard:",
			"image": "1f3b9"
		}, {
			"name": ":saxophone:",
			"image": "1f3b7"
		}, {
			"name": ":trumpet:",
			"image": "1f3ba"
		}, {
			"name": ":guitar:",
			"image": "1f3b8"
		}, {
			"name": ":violin:",
			"image": "1f3bb"
		}, {
			"name": ":clapper:",
			"image": "1f3ac"
		}, {
			"name": ":video_game:",
			"image": "1f3ae"
		}, {
			"name": ":space_invader:",
			"image": "1f47e"
		}, {
			"name": ":dart:",
			"image": "1f3af"
		}, {
			"name": ":game_die:",
			"image": "1f3b2"
		}, {
			"name": ":slot_machine:",
			"image": "1f3b0"
		}, {
			"name": ":bowling:",
			"image": "1f3b3"
		}]
	}, {
		"name": "travel",
		"list": [{
			"name": ":red_car:",
			"image": "1f697"
		}, {
			"name": ":taxi:",
			"image": "1f695"
		}, {
			"name": ":blue_car:",
			"image": "1f699"
		}, {
			"name": ":bus:",
			"image": "1f68c"
		}, {
			"name": ":trolleybus:",
			"image": "1f68e"
		}, {
			"name": ":police_car:",
			"image": "1f693"
		}, {
			"name": ":ambulance:",
			"image": "1f691"
		}, {
			"name": ":fire_engine:",
			"image": "1f692"
		}, {
			"name": ":minibus:",
			"image": "1f690"
		}, {
			"name": ":truck:",
			"image": "1f69a"
		}, {
			"name": ":articulated_lorry:",
			"image": "1f69b"
		}, {
			"name": ":tractor:",
			"image": "1f69c"
		}, {
			"name": ":bike:",
			"image": "1f6b2"
		}, {
			"name": ":rotating_light:",
			"image": "1f6a8"
		}, {
			"name": ":oncoming_police_car:",
			"image": "1f694"
		}, {
			"name": ":oncoming_bus:",
			"image": "1f68d"
		}, {
			"name": ":oncoming_automobile:",
			"image": "1f698"
		}, {
			"name": ":oncoming_taxi:",
			"image": "1f696"
		}, {
			"name": ":aerial_tramway:",
			"image": "1f6a1"
		}, {
			"name": ":mountain_cableway:",
			"image": "1f6a0"
		}, {
			"name": ":suspension_railway:",
			"image": "1f69f"
		}, {
			"name": ":railway_car:",
			"image": "1f683"
		}, {
			"name": ":train:",
			"image": "1f68b"
		}, {
			"name": ":monorail:",
			"image": "1f69d"
		}, {
			"name": ":bullettrain_side:",
			"image": "1f684"
		}, {
			"name": ":bullettrain_front:",
			"image": "1f685"
		}, {
			"name": ":light_rail:",
			"image": "1f688"
		}, {
			"name": ":mountain_railway:",
			"image": "1f69e"
		}, {
			"name": ":steam_locomotive:",
			"image": "1f682"
		}, {
			"name": ":train2:",
			"image": "1f686"
		}, {
			"name": ":metro:",
			"image": "1f687"
		}, {
			"name": ":tram:",
			"image": "1f68a"
		}, {
			"name": ":station:",
			"image": "1f689"
		}, {
			"name": ":helicopter:",
			"image": "1f681"
		}, {
			"name": ":airplane:",
			"image": "2708"
		}, {
			"name": ":sailboat:",
			"image": "26f5"
		}, {
			"name": ":speedboat:",
			"image": "1f6a4"
		}, {
			"name": ":rocket:",
			"image": "1f680"
		}, {
			"name": ":seat:",
			"image": "1f4ba"
		}, {
			"name": ":anchor:",
			"image": "2693"
		}, {
			"name": ":construction:",
			"image": "1f6a7"
		}, {
			"name": ":fuelpump:",
			"image": "26fd"
		}, {
			"name": ":busstop:",
			"image": "1f68f"
		}, {
			"name": ":vertical_traffic_light:",
			"image": "1f6a6"
		}, {
			"name": ":traffic_light:",
			"image": "1f6a5"
		}, {
			"name": ":checkered_flag:",
			"image": "1f3c1"
		}, {
			"name": ":ship:",
			"image": "1f6a2"
		}, {
			"name": ":ferris_wheel:",
			"image": "1f3a1"
		}, {
			"name": ":roller_coaster:",
			"image": "1f3a2"
		}, {
			"name": ":carousel_horse:",
			"image": "1f3a0"
		}, {
			"name": ":foggy:",
			"image": "1f301"
		}, {
			"name": ":tokyo_tower:",
			"image": "1f5fc"
		}, {
			"name": ":factory:",
			"image": "1f3ed"
		}, {
			"name": ":fountain:",
			"image": "26f2"
		}, {
			"name": ":rice_scene:",
			"image": "1f391"
		}, {
			"name": ":mount_fuji:",
			"image": "1f5fb"
		}, {
			"name": ":volcano:",
			"image": "1f30b"
		}, {
			"name": ":japan:",
			"image": "1f5fe"
		}, {
			"name": ":tent:",
			"image": "26fa"
		}, {
			"name": ":sunrise:",
			"image": "1f305"
		}, {
			"name": ":sunrise_over_mountains:",
			"image": "1f304"
		}, {
			"name": ":city_sunset:",
			"image": "1f307"
		}, {
			"name": ":city_dusk:",
			"image": "1f306"
		}, {
			"name": ":night_with_stars:",
			"image": "1f303"
		}, {
			"name": ":bridge_at_night:",
			"image": "1f309"
		}, {
			"name": ":milky_way:",
			"image": "1f30c"
		}, {
			"name": ":stars:",
			"image": "1f320"
		}, {
			"name": ":sparkler:",
			"image": "1f387"
		}, {
			"name": ":fireworks:",
			"image": "1f386"
		}, {
			"name": ":rainbow:",
			"image": "1f308"
		}, {
			"name": ":european_castle:",
			"image": "1f3f0"
		}, {
			"name": ":japanese_castle:",
			"image": "1f3ef"
		}, {
			"name": ":statue_of_liberty:",
			"image": "1f5fd"
		}, {
			"name": ":house:",
			"image": "1f3e0"
		}, {
			"name": ":house_with_garden:",
			"image": "1f3e1"
		}, {
			"name": ":office:",
			"image": "1f3e2"
		}, {
			"name": ":department_store:",
			"image": "1f3ec"
		}, {
			"name": ":post_office:",
			"image": "1f3e3"
		}, {
			"name": ":european_post_office:",
			"image": "1f3e4"
		}, {
			"name": ":hospital:",
			"image": "1f3e5"
		}, {
			"name": ":bank:",
			"image": "1f3e6"
		}, {
			"name": ":hotel:",
			"image": "1f3e8"
		}, {
			"name": ":convenience_store:",
			"image": "1f3ea"
		}, {
			"name": ":school:",
			"image": "1f3eb"
		}, {
			"name": ":love_hotel:",
			"image": "1f3e9"
		}, {
			"name": ":wedding:",
			"image": "1f492"
		}, {
			"name": ":church:",
			"image": "26ea"
		}]
	}, {
		"name": "objects",
		"list": [{
			"name": ":watch:",
			"image": "231a"
		}, {
			"name": ":iphone:",
			"image": "1f4f1"
		}, {
			"name": ":calling:",
			"image": "1f4f2"
		}, {
			"name": ":computer:",
			"image": "1f4bb"
		}, {
			"name": ":minidisc:",
			"image": "1f4bd"
		}, {
			"name": ":floppy_disk:",
			"image": "1f4be"
		}, {
			"name": ":cd:",
			"image": "1f4bf"
		}, {
			"name": ":dvd:",
			"image": "1f4c0"
		}, {
			"name": ":vhs:",
			"image": "1f4fc"
		}, {
			"name": ":camera:",
			"image": "1f4f7"
		}, {
			"name": ":video_camera:",
			"image": "1f4f9"
		}, {
			"name": ":movie_camera:",
			"image": "1f3a5"
		}, {
			"name": ":telephone_receiver:",
			"image": "1f4de"
		}, {
			"name": ":telephone:",
			"image": "260e"
		}, {
			"name": ":pager:",
			"image": "1f4df"
		}, {
			"name": ":fax:",
			"image": "1f4e0"
		}, {
			"name": ":tv:",
			"image": "1f4fa"
		}, {
			"name": ":radio:",
			"image": "1f4fb"
		}, {
			"name": ":alarm_clock:",
			"image": "23f0"
		}, {
			"name": ":hourglass_flowing_sand:",
			"image": "23f3"
		}, {
			"name": ":hourglass:",
			"image": "231b"
		}, {
			"name": ":satellite:",
			"image": "1f4e1"
		}, {
			"name": ":battery:",
			"image": "1f50b"
		}, {
			"name": ":electric_plug:",
			"image": "1f50c"
		}, {
			"name": ":bulb:",
			"image": "1f4a1"
		}, {
			"name": ":flashlight:",
			"image": "1f526"
		}, {
			"name": ":money_with_wings:",
			"image": "1f4b8"
		}, {
			"name": ":dollar:",
			"image": "1f4b5"
		}, {
			"name": ":yen:",
			"image": "1f4b4"
		}, {
			"name": ":euro:",
			"image": "1f4b6"
		}, {
			"name": ":pound:",
			"image": "1f4b7"
		}, {
			"name": ":moneybag:",
			"image": "1f4b0"
		}, {
			"name": ":credit_card:",
			"image": "1f4b3"
		}, {
			"name": ":gem:",
			"image": "1f48e"
		}, {
			"name": ":wrench:",
			"image": "1f527"
		}, {
			"name": ":hammer:",
			"image": "1f528"
		}, {
			"name": ":nut_and_bolt:",
			"image": "1f529"
		}, {
			"name": ":gun:",
			"image": "1f52b"
		}, {
			"name": ":bomb:",
			"image": "1f4a3"
		}, {
			"name": ":knife:",
			"image": "1f52a"
		}, {
			"name": ":smoking:",
			"image": "1f6ac"
		}, {
			"name": ":crystal_ball:",
			"image": "1f52e"
		}, {
			"name": ":barber:",
			"image": "1f488"
		}, {
			"name": ":telescope:",
			"image": "1f52d"
		}, {
			"name": ":microscope:",
			"image": "1f52c"
		}, {
			"name": ":pill:",
			"image": "1f48a"
		}, {
			"name": ":syringe:",
			"image": "1f489"
		}, {
			"name": ":bookmark:",
			"image": "1f516"
		}, {
			"name": ":toilet:",
			"image": "1f6bd"
		}, {
			"name": ":shower:",
			"image": "1f6bf"
		}, {
			"name": ":bathtub:",
			"image": "1f6c1"
		}, {
			"name": ":key:",
			"image": "1f511"
		}, {
			"name": ":door:",
			"image": "1f6aa"
		}, {
			"name": ":moyai:",
			"image": "1f5ff"
		}, {
			"name": ":balloon:",
			"image": "1f388"
		}, {
			"name": ":flags:",
			"image": "1f38f"
		}, {
			"name": ":ribbon:",
			"image": "1f380"
		}, {
			"name": ":gift:",
			"image": "1f381"
		}, {
			"name": ":confetti_ball:",
			"image": "1f38a"
		}, {
			"name": ":tada:",
			"image": "1f389"
		}, {
			"name": ":dolls:",
			"image": "1f38e"
		}, {
			"name": ":wind_chime:",
			"image": "1f390"
		}, {
			"name": ":crossed_flags:",
			"image": "1f38c"
		}, {
			"name": ":izakaya_lantern:",
			"image": "1f3ee"
		}, {
			"name": ":envelope:",
			"image": "2709"
		}, {
			"name": ":envelope_with_arrow:",
			"image": "1f4e9"
		}, {
			"name": ":incoming_envelope:",
			"image": "1f4e8"
		}, {
			"name": ":e_mail:",
			"image": "1f4e7"
		}, {
			"name": ":love_letter:",
			"image": "1f48c"
		}, {
			"name": ":postbox:",
			"image": "1f4ee"
		}, {
			"name": ":mailbox_closed:",
			"image": "1f4ea"
		}, {
			"name": ":mailbox:",
			"image": "1f4eb"
		}, {
			"name": ":mailbox_with_mail:",
			"image": "1f4ec"
		}, {
			"name": ":mailbox_with_no_mail:",
			"image": "1f4ed"
		}, {
			"name": ":package:",
			"image": "1f4e6"
		}, {
			"name": ":postal_horn:",
			"image": "1f4ef"
		}, {
			"name": ":inbox_tray:",
			"image": "1f4e5"
		}, {
			"name": ":outbox_tray:",
			"image": "1f4e4"
		}, {
			"name": ":scroll:",
			"image": "1f4dc"
		}, {
			"name": ":page_with_curl:",
			"image": "1f4c3"
		}, {
			"name": ":bookmark_tabs:",
			"image": "1f4d1"
		}, {
			"name": ":bar_chart:",
			"image": "1f4ca"
		}, {
			"name": ":chart_with_upwards_trend:",
			"image": "1f4c8"
		}, {
			"name": ":chart_with_downwards_trend:",
			"image": "1f4c9"
		}, {
			"name": ":page_facing_up:",
			"image": "1f4c4"
		}, {
			"name": ":date:",
			"image": "1f4c5"
		}, {
			"name": ":calendar:",
			"image": "1f4c6"
		}, {
			"name": ":card_index:",
			"image": "1f4c7"
		}, {
			"name": ":clipboard:",
			"image": "1f4cb"
		}, {
			"name": ":file_folder:",
			"image": "1f4c1"
		}, {
			"name": ":open_file_folder:",
			"image": "1f4c2"
		}, {
			"name": ":newspaper:",
			"image": "1f4f0"
		}, {
			"name": ":notebook:",
			"image": "1f4d3"
		}, {
			"name": ":closed_book:",
			"image": "1f4d5"
		}, {
			"name": ":green_book:",
			"image": "1f4d7"
		}, {
			"name": ":blue_book:",
			"image": "1f4d8"
		}, {
			"name": ":orange_book:",
			"image": "1f4d9"
		}, {
			"name": ":notebook_with_decorative_cover:",
			"image": "1f4d4"
		}, {
			"name": ":ledger:",
			"image": "1f4d2"
		}, {
			"name": ":books:",
			"image": "1f4da"
		}, {
			"name": ":book:",
			"image": "1f4d6"
		}, {
			"name": ":link:",
			"image": "1f517"
		}, {
			"name": ":paperclip:",
			"image": "1f4ce"
		}, {
			"name": ":scissors:",
			"image": "2702"
		}, {
			"name": ":triangular_ruler:",
			"image": "1f4d0"
		}, {
			"name": ":straight_ruler:",
			"image": "1f4cf"
		}, {
			"name": ":pushpin:",
			"image": "1f4cc"
		}, {
			"name": ":round_pushpin:",
			"image": "1f4cd"
		}, {
			"name": ":triangular_flag_on_post:",
			"image": "1f6a9"
		}, {
			"name": ":closed_lock_with_key:",
			"image": "1f510"
		}, {
			"name": ":lock:",
			"image": "1f512"
		}, {
			"name": ":unlock:",
			"image": "1f513"
		}, {
			"name": ":lock_with_ink_pen:",
			"image": "1f50f"
		}, {
			"name": ":black_nib:",
			"image": "2712"
		}, {
			"name": ":pencil:",
			"image": "1f4dd"
		}, {
			"name": ":pencil2:",
			"image": "270f"
		}, {
			"name": ":mag:",
			"image": "1f50d"
		}, {
			"name": ":mag_right:",
			"image": "1f50e"
		}]
	}, {
		"name": "symbols",
		"list": [{
			"name": ":100:",
			"image": "1f4af"
		}, {
			"name": ":1234:",
			"image": "1f522"
		}, {
			"name": ":heart:",
			"image": "2764"
		}, {
			"name": ":yellow_heart:",
			"image": "1f49b"
		}, {
			"name": ":green_heart:",
			"image": "1f49a"
		}, {
			"name": ":blue_heart:",
			"image": "1f499"
		}, {
			"name": ":purple_heart:",
			"image": "1f49c"
		}, {
			"name": ":broken_heart:",
			"image": "1f494"
		}, {
			"name": ":two_hearts:",
			"image": "1f495"
		}, {
			"name": ":revolving_hearts:",
			"image": "1f49e"
		}, {
			"name": ":heartbeat:",
			"image": "1f493"
		}, {
			"name": ":heartpulse:",
			"image": "1f497"
		}, {
			"name": ":sparkling_heart:",
			"image": "1f496"
		}, {
			"name": ":cupid:",
			"image": "1f498"
		}, {
			"name": ":gift_heart:",
			"image": "1f49d"
		}, {
			"name": ":heart_decoration:",
			"image": "1f49f"
		}, {
			"name": ":six_pointed_star:",
			"image": "1f52f"
		}, {
			"name": ":ophiuchus:",
			"image": "26ce"
		}, {
			"name": ":aries:",
			"image": "2648"
		}, {
			"name": ":taurus:",
			"image": "2649"
		}, {
			"name": ":gemini:",
			"image": "264a"
		}, {
			"name": ":cancer:",
			"image": "264b"
		}, {
			"name": ":leo:",
			"image": "264c"
		}, {
			"name": ":virgo:",
			"image": "264d"
		}, {
			"name": ":libra:",
			"image": "264e"
		}, {
			"name": ":scorpius:",
			"image": "264f"
		}, {
			"name": ":sagittarius:",
			"image": "2650"
		}, {
			"name": ":capricorn:",
			"image": "2651"
		}, {
			"name": ":aquarius:",
			"image": "2652"
		}, {
			"name": ":pisces:",
			"image": "2653"
		}, {
			"name": ":id:",
			"image": "1f194"
		}, {
			"name": ":u7a7a:",
			"image": "1f233"
		}, {
			"name": ":u5272:",
			"image": "1f239"
		}, {
			"name": ":mobile_phone_off:",
			"image": "1f4f4"
		}, {
			"name": ":vibration_mode:",
			"image": "1f4f3"
		}, {
			"name": ":u6709:",
			"image": "1f236"
		}, {
			"name": ":u7121:",
			"image": "1f21a"
		}, {
			"name": ":u7533:",
			"image": "1f238"
		}, {
			"name": ":u55b6:",
			"image": "1f23a"
		}, {
			"name": ":u6708:",
			"image": "1f237"
		}, {
			"name": ":eight_pointed_black_star:",
			"image": "2734"
		}, {
			"name": ":vs:",
			"image": "1f19a"
		}, {
			"name": ":accept:",
			"image": "1f251"
		}, {
			"name": ":white_flower:",
			"image": "1f4ae"
		}, {
			"name": ":ideograph_advantage:",
			"image": "1f250"
		}, {
			"name": ":secret:",
			"image": "3299"
		}, {
			"name": ":congratulations:",
			"image": "3297"
		}, {
			"name": ":u5408:",
			"image": "1f234"
		}, {
			"name": ":u6e80:",
			"image": "1f235"
		}, {
			"name": ":u7981:",
			"image": "1f232"
		}, {
			"name": ":a:",
			"image": "1f170"
		}, {
			"name": ":b:",
			"image": "1f171"
		}, {
			"name": ":ab:",
			"image": "1f18e"
		}, {
			"name": ":cl:",
			"image": "1f191"
		}, {
			"name": ":o2:",
			"image": "1f17e"
		}, {
			"name": ":sos:",
			"image": "1f198"
		}, {
			"name": ":no_entry:",
			"image": "26d4"
		}, {
			"name": ":name_badge:",
			"image": "1f4db"
		}, {
			"name": ":no_entry_sign:",
			"image": "1f6ab"
		}, {
			"name": ":x:",
			"image": "274c"
		}, {
			"name": ":o:",
			"image": "2b55"
		}, {
			"name": ":anger:",
			"image": "1f4a2"
		}, {
			"name": ":hotsprings:",
			"image": "2668"
		}, {
			"name": ":no_pedestrians:",
			"image": "1f6b7"
		}, {
			"name": ":do_not_litter:",
			"image": "1f6af"
		}, {
			"name": ":no_bicycles:",
			"image": "1f6b3"
		}, {
			"name": ":non_potable_water:",
			"image": "1f6b1"
		}, {
			"name": ":underage:",
			"image": "1f51e"
		}, {
			"name": ":no_mobile_phones:",
			"image": "1f4f5"
		}, {
			"name": ":exclamation:",
			"image": "2757"
		}, {
			"name": ":grey_exclamation:",
			"image": "2755"
		}, {
			"name": ":question:",
			"image": "2753"
		}, {
			"name": ":grey_question:",
			"image": "2754"
		}, {
			"name": ":bangbang:",
			"image": "203c"
		}, {
			"name": ":interrobang:",
			"image": "2049"
		}, {
			"name": ":low_brightness:",
			"image": "1f505"
		}, {
			"name": ":high_brightness:",
			"image": "1f506"
		}, {
			"name": ":trident:",
			"image": "1f531"
		}, {
			"name": ":part_alternation_mark:",
			"image": "303d"
		}, {
			"name": ":warning:",
			"image": "26a0"
		}, {
			"name": ":children_crossing:",
			"image": "1f6b8"
		}, {
			"name": ":beginner:",
			"image": "1f530"
		}, {
			"name": ":recycle:",
			"image": "267b"
		}, {
			"name": ":u6307:",
			"image": "1f22f"
		}, {
			"name": ":chart:",
			"image": "1f4b9"
		}, {
			"name": ":sparkle:",
			"image": "2747"
		}, {
			"name": ":eight_spoked_asterisk:",
			"image": "2733"
		}, {
			"name": ":negative_squared_cross_mark:",
			"image": "274e"
		}, {
			"name": ":white_check_mark:",
			"image": "2705"
		}, {
			"name": ":diamond_shape_with_a_dot_inside:",
			"image": "1f4a0"
		}, {
			"name": ":cyclone:",
			"image": "1f300"
		}, {
			"name": ":loop:",
			"image": "27bf"
		}, {
			"name": ":globe_with_meridians:",
			"image": "1f310"
		}, {
			"name": ":m:",
			"image": "24c2"
		}, {
			"name": ":atm:",
			"image": "1f3e7"
		}, {
			"name": ":sa:",
			"image": "1f202"
		}, {
			"name": ":passport_control:",
			"image": "1f6c2"
		}, {
			"name": ":customs:",
			"image": "1f6c3"
		}, {
			"name": ":baggage_claim:",
			"image": "1f6c4"
		}, {
			"name": ":left_luggage:",
			"image": "1f6c5"
		}, {
			"name": ":wheelchair:",
			"image": "267f"
		}, {
			"name": ":no_smoking:",
			"image": "1f6ad"
		}, {
			"name": ":wc:",
			"image": "1f6be"
		}, {
			"name": ":parking:",
			"image": "1f17f"
		}, {
			"name": ":potable_water:",
			"image": "1f6b0"
		}, {
			"name": ":mens:",
			"image": "1f6b9"
		}, {
			"name": ":womens:",
			"image": "1f6ba"
		}, {
			"name": ":baby_symbol:",
			"image": "1f6bc"
		}, {
			"name": ":restroom:",
			"image": "1f6bb"
		}, {
			"name": ":put_litter_in_its_place:",
			"image": "1f6ae"
		}, {
			"name": ":cinema:",
			"image": "1f3a6"
		}, {
			"name": ":signal_strength:",
			"image": "1f4f6"
		}, {
			"name": ":koko:",
			"image": "1f201"
		}, {
			"name": ":ng:",
			"image": "1f196"
		}, {
			"name": ":ok:",
			"image": "1f197"
		}, {
			"name": ":up:",
			"image": "1f199"
		}, {
			"name": ":cool:",
			"image": "1f192"
		}, {
			"name": ":new:",
			"image": "1f195"
		}, {
			"name": ":free:",
			"image": "1f193"
		}, {
			"name": ":zero:",
			"image": "30-20e3"
		}, {
			"name": ":one:",
			"image": "31-20e3"
		}, {
			"name": ":two:",
			"image": "32-20e3"
		}, {
			"name": ":three:",
			"image": "33-20e3"
		}, {
			"name": ":four:",
			"image": "34-20e3"
		}, {
			"name": ":five:",
			"image": "35-20e3"
		}, {
			"name": ":six:",
			"image": "36-20e3"
		}, {
			"name": ":seven:",
			"image": "37-20e3"
		}, {
			"name": ":eight:",
			"image": "38-20e3"
		}, {
			"name": ":nine:",
			"image": "39-20e3"
		}, {
			"name": ":keycap_ten:",
			"image": "1f51f"
		}, {
			"name": ":arrow_forward:",
			"image": "25b6"
		}, {
			"name": ":fast_forward:",
			"image": "23e9"
		}, {
			"name": ":rewind:",
			"image": "23ea"
		}, {
			"name": ":twisted_rightwards_arrows:",
			"image": "1f500"
		}, {
			"name": ":repeat:",
			"image": "1f501"
		}, {
			"name": ":repeat_one:",
			"image": "1f502"
		}, {
			"name": ":arrow_backward:",
			"image": "25c0"
		}, {
			"name": ":arrow_up_small:",
			"image": "1f53c"
		}, {
			"name": ":arrow_down_small:",
			"image": "1f53d"
		}, {
			"name": ":arrow_double_up:",
			"image": "23eb"
		}, {
			"name": ":arrow_double_down:",
			"image": "23ec"
		}, {
			"name": ":arrow_right:",
			"image": "27a1"
		}, {
			"name": ":arrow_left:",
			"image": "2b05"
		}, {
			"name": ":arrow_up:",
			"image": "2b06"
		}, {
			"name": ":arrow_down:",
			"image": "2b07"
		}, {
			"name": ":arrow_upper_right:",
			"image": "2197"
		}, {
			"name": ":arrow_lower_right:",
			"image": "2198"
		}, {
			"name": ":arrow_lower_left:",
			"image": "2199"
		}, {
			"name": ":arrow_upper_left:",
			"image": "2196"
		}, {
			"name": ":arrow_up_down:",
			"image": "2195"
		}, {
			"name": ":left_right_arrow:",
			"image": "2194"
		}, {
			"name": ":arrows_counterclockwise:",
			"image": "1f504"
		}, {
			"name": ":arrow_right_hook:",
			"image": "21aa"
		}, {
			"name": ":leftwards_arrow_with_hook:",
			"image": "21a9"
		}, {
			"name": ":arrow_heading_up:",
			"image": "2934"
		}, {
			"name": ":arrow_heading_down:",
			"image": "2935"
		}, {
			"name": ":hash:",
			"image": "23-20e3"
		}, {
			"name": ":information_source:",
			"image": "2139"
		}, {
			"name": ":abc:",
			"image": "1f524"
		}, {
			"name": ":abcd:",
			"image": "1f521"
		}, {
			"name": ":capital_abcd:",
			"image": "1f520"
		}, {
			"name": ":symbols:",
			"image": "1f523"
		}, {
			"name": ":musical_note:",
			"image": "1f3b5"
		}, {
			"name": ":notes:",
			"image": "1f3b6"
		}, {
			"name": ":wavy_dash:",
			"image": "3030"
		}, {
			"name": ":curly_loop:",
			"image": "27b0"
		}, {
			"name": ":heavy_check_mark:",
			"image": "2714"
		}, {
			"name": ":arrows_clockwise:",
			"image": "1f503"
		}, {
			"name": ":heavy_plus_sign:",
			"image": "2795"
		}, {
			"name": ":heavy_minus_sign:",
			"image": "2796"
		}, {
			"name": ":heavy_division_sign:",
			"image": "2797"
		}, {
			"name": ":heavy_multiplication_x:",
			"image": "2716"
		}, {
			"name": ":heavy_dollar_sign:",
			"image": "1f4b2"
		}, {
			"name": ":currency_exchange:",
			"image": "1f4b1"
		}, {
			"name": ":copyright:",
			"image": "a9"
		}, {
			"name": ":registered:",
			"image": "ae"
		}, {
			"name": ":tm:",
			"image": "2122"
		}, {
			"name": ":end:",
			"image": "1f51a"
		}, {
			"name": ":back:",
			"image": "1f519"
		}, {
			"name": ":on:",
			"image": "1f51b"
		}, {
			"name": ":top:",
			"image": "1f51d"
		}, {
			"name": ":soon:",
			"image": "1f51c"
		}, {
			"name": ":ballot_box_with_check:",
			"image": "2611"
		}, {
			"name": ":radio_button:",
			"image": "1f518"
		}, {
			"name": ":white_circle:",
			"image": "26aa"
		}, {
			"name": ":black_circle:",
			"image": "26ab"
		}, {
			"name": ":red_circle:",
			"image": "1f534"
		}, {
			"name": ":large_blue_circle:",
			"image": "1f535"
		}, {
			"name": ":small_orange_diamond:",
			"image": "1f538"
		}, {
			"name": ":small_blue_diamond:",
			"image": "1f539"
		}, {
			"name": ":large_orange_diamond:",
			"image": "1f536"
		}, {
			"name": ":large_blue_diamond:",
			"image": "1f537"
		}, {
			"name": ":small_red_triangle:",
			"image": "1f53a"
		}, {
			"name": ":black_small_square:",
			"image": "25aa"
		}, {
			"name": ":white_small_square:",
			"image": "25ab"
		}, {
			"name": ":black_large_square:",
			"image": "2b1b"
		}, {
			"name": ":white_large_square:",
			"image": "2b1c"
		}, {
			"name": ":small_red_triangle_down:",
			"image": "1f53b"
		}, {
			"name": ":black_medium_square:",
			"image": "25fc"
		}, {
			"name": ":white_medium_square:",
			"image": "25fb"
		}, {
			"name": ":black_medium_small_square:",
			"image": "25fe"
		}, {
			"name": ":white_medium_small_square:",
			"image": "25fd"
		}, {
			"name": ":black_square_button:",
			"image": "1f532"
		}, {
			"name": ":white_square_button:",
			"image": "1f533"
		}, {
			"name": ":speaker:",
			"image": "1f508"
		}, {
			"name": ":sound:",
			"image": "1f509"
		}, {
			"name": ":loud_sound:",
			"image": "1f50a"
		}, {
			"name": ":mute:",
			"image": "1f507"
		}, {
			"name": ":mega:",
			"image": "1f4e3"
		}, {
			"name": ":loudspeaker:",
			"image": "1f4e2"
		}, {
			"name": ":bell:",
			"image": "1f514"
		}, {
			"name": ":no_bell:",
			"image": "1f515"
		}, {
			"name": ":black_joker:",
			"image": "1f0cf"
		}, {
			"name": ":mahjong:",
			"image": "1f004"
		}, {
			"name": ":spades:",
			"image": "2660"
		}, {
			"name": ":clubs:",
			"image": "2663"
		}, {
			"name": ":hearts:",
			"image": "2665"
		}, {
			"name": ":diamonds:",
			"image": "2666"
		}, {
			"name": ":flower_playing_cards:",
			"image": "1f3b4"
		}, {
			"name": ":thought_balloon:",
			"image": "1f4ad"
		}, {
			"name": ":speech_balloon:",
			"image": "1f4ac"
		}, {
			"name": ":clock1:",
			"image": "1f550"
		}, {
			"name": ":clock2:",
			"image": "1f551"
		}, {
			"name": ":clock3:",
			"image": "1f552"
		}, {
			"name": ":clock4:",
			"image": "1f553"
		}, {
			"name": ":clock5:",
			"image": "1f554"
		}, {
			"name": ":clock6:",
			"image": "1f555"
		}, {
			"name": ":clock7:",
			"image": "1f556"
		}, {
			"name": ":clock8:",
			"image": "1f557"
		}, {
			"name": ":clock9:",
			"image": "1f558"
		}, {
			"name": ":clock10:",
			"image": "1f559"
		}, {
			"name": ":clock11:",
			"image": "1f55a"
		}, {
			"name": ":clock12:",
			"image": "1f55b"
		}, {
			"name": ":clock130:",
			"image": "1f55c"
		}, {
			"name": ":clock230:",
			"image": "1f55d"
		}, {
			"name": ":clock330:",
			"image": "1f55e"
		}, {
			"name": ":clock430:",
			"image": "1f55f"
		}, {
			"name": ":clock530:",
			"image": "1f560"
		}, {
			"name": ":clock630:",
			"image": "1f561"
		}, {
			"name": ":clock730:",
			"image": "1f562"
		}, {
			"name": ":clock830:",
			"image": "1f563"
		}, {
			"name": ":clock930:",
			"image": "1f564"
		}, {
			"name": ":clock1030:",
			"image": "1f565"
		}, {
			"name": ":clock1130:",
			"image": "1f566"
		}, {
			"name": ":clock1230:",
			"image": "1f567"
		}, {
			"name": ":regional_indicator_z:",
			"image": "1f1ff"
		}, {
			"name": ":regional_indicator_y:",
			"image": "1f1fe"
		}, {
			"name": ":regional_indicator_x:",
			"image": "1f1fd"
		}, {
			"name": ":regional_indicator_w:",
			"image": "1f1fc"
		}, {
			"name": ":regional_indicator_v:",
			"image": "1f1fb"
		}, {
			"name": ":regional_indicator_u:",
			"image": "1f1fa"
		}, {
			"name": ":regional_indicator_t:",
			"image": "1f1f9"
		}, {
			"name": ":regional_indicator_s:",
			"image": "1f1f8"
		}, {
			"name": ":regional_indicator_r:",
			"image": "1f1f7"
		}, {
			"name": ":regional_indicator_q:",
			"image": "1f1f6"
		}, {
			"name": ":regional_indicator_p:",
			"image": "1f1f5"
		}, {
			"name": ":regional_indicator_o:",
			"image": "1f1f4"
		}, {
			"name": ":regional_indicator_n:",
			"image": "1f1f3"
		}, {
			"name": ":regional_indicator_m:",
			"image": "1f1f2"
		}, {
			"name": ":regional_indicator_l:",
			"image": "1f1f1"
		}, {
			"name": ":regional_indicator_k:",
			"image": "1f1f0"
		}, {
			"name": ":regional_indicator_j:",
			"image": "1f1ef"
		}, {
			"name": ":regional_indicator_i:",
			"image": "1f1ee"
		}, {
			"name": ":regional_indicator_h:",
			"image": "1f1ed"
		}, {
			"name": ":regional_indicator_g:",
			"image": "1f1ec"
		}, {
			"name": ":regional_indicator_f:",
			"image": "1f1eb"
		}, {
			"name": ":regional_indicator_e:",
			"image": "1f1ea"
		}, {
			"name": ":regional_indicator_d:",
			"image": "1f1e9"
		}, {
			"name": ":regional_indicator_c:",
			"image": "1f1e8"
		}, {
			"name": ":regional_indicator_b:",
			"image": "1f1e7"
		}, {
			"name": ":regional_indicator_a:",
			"image": "1f1e6"
		}]
	}, {
		"name": "flags",
		"list": [{
			"name": ":flag_ac:",
			"image": "1f1e6-1f1e8"
		}, {
			"name": ":flag_af:",
			"image": "1f1e6-1f1eb"
		}, {
			"name": ":flag_al:",
			"image": "1f1e6-1f1f1"
		}, {
			"name": ":flag_dz:",
			"image": "1f1e9-1f1ff"
		}, {
			"name": ":flag_ad:",
			"image": "1f1e6-1f1e9"
		}, {
			"name": ":flag_ao:",
			"image": "1f1e6-1f1f4"
		}, {
			"name": ":flag_ai:",
			"image": "1f1e6-1f1ee"
		}, {
			"name": ":flag_ag:",
			"image": "1f1e6-1f1ec"
		}, {
			"name": ":flag_ar:",
			"image": "1f1e6-1f1f7"
		}, {
			"name": ":flag_am:",
			"image": "1f1e6-1f1f2"
		}, {
			"name": ":flag_aw:",
			"image": "1f1e6-1f1fc"
		}, {
			"name": ":flag_au:",
			"image": "1f1e6-1f1fa"
		}, {
			"name": ":flag_at:",
			"image": "1f1e6-1f1f9"
		}, {
			"name": ":flag_az:",
			"image": "1f1e6-1f1ff"
		}, {
			"name": ":flag_bs:",
			"image": "1f1e7-1f1f8"
		}, {
			"name": ":flag_bh:",
			"image": "1f1e7-1f1ed"
		}, {
			"name": ":flag_bd:",
			"image": "1f1e7-1f1e9"
		}, {
			"name": ":flag_bb:",
			"image": "1f1e7-1f1e7"
		}, {
			"name": ":flag_by:",
			"image": "1f1e7-1f1fe"
		}, {
			"name": ":flag_be:",
			"image": "1f1e7-1f1ea"
		}, {
			"name": ":flag_bz:",
			"image": "1f1e7-1f1ff"
		}, {
			"name": ":flag_bj:",
			"image": "1f1e7-1f1ef"
		}, {
			"name": ":flag_bm:",
			"image": "1f1e7-1f1f2"
		}, {
			"name": ":flag_bt:",
			"image": "1f1e7-1f1f9"
		}, {
			"name": ":flag_bo:",
			"image": "1f1e7-1f1f4"
		}, {
			"name": ":flag_ba:",
			"image": "1f1e7-1f1e6"
		}, {
			"name": ":flag_bw:",
			"image": "1f1e7-1f1fc"
		}, {
			"name": ":flag_br:",
			"image": "1f1e7-1f1f7"
		}, {
			"name": ":flag_bn:",
			"image": "1f1e7-1f1f3"
		}, {
			"name": ":flag_bg:",
			"image": "1f1e7-1f1ec"
		}, {
			"name": ":flag_bf:",
			"image": "1f1e7-1f1eb"
		}, {
			"name": ":flag_bi:",
			"image": "1f1e7-1f1ee"
		}, {
			"name": ":flag_cv:",
			"image": "1f1e8-1f1fb"
		}, {
			"name": ":flag_kh:",
			"image": "1f1f0-1f1ed"
		}, {
			"name": ":flag_cm:",
			"image": "1f1e8-1f1f2"
		}, {
			"name": ":flag_ca:",
			"image": "1f1e8-1f1e6"
		}, {
			"name": ":flag_ky:",
			"image": "1f1f0-1f1fe"
		}, {
			"name": ":flag_cf:",
			"image": "1f1e8-1f1eb"
		}, {
			"name": ":flag_td:",
			"image": "1f1f9-1f1e9"
		}, {
			"name": ":flag_cl:",
			"image": "1f1e8-1f1f1"
		}, {
			"name": ":flag_cn:",
			"image": "1f1e8-1f1f3"
		}, {
			"name": ":flag_co:",
			"image": "1f1e8-1f1f4"
		}, {
			"name": ":flag_km:",
			"image": "1f1f0-1f1f2"
		}, {
			"name": ":flag_cg:",
			"image": "1f1e8-1f1ec"
		}, {
			"name": ":flag_cd:",
			"image": "1f1e8-1f1e9"
		}, {
			"name": ":flag_cr:",
			"image": "1f1e8-1f1f7"
		}, {
			"name": ":flag_hr:",
			"image": "1f1ed-1f1f7"
		}, {
			"name": ":flag_cu:",
			"image": "1f1e8-1f1fa"
		}, {
			"name": ":flag_cy:",
			"image": "1f1e8-1f1fe"
		}, {
			"name": ":flag_cz:",
			"image": "1f1e8-1f1ff"
		}, {
			"name": ":flag_dk:",
			"image": "1f1e9-1f1f0"
		}, {
			"name": ":flag_dj:",
			"image": "1f1e9-1f1ef"
		}, {
			"name": ":flag_dm:",
			"image": "1f1e9-1f1f2"
		}, {
			"name": ":flag_do:",
			"image": "1f1e9-1f1f4"
		}, {
			"name": ":flag_ec:",
			"image": "1f1ea-1f1e8"
		}, {
			"name": ":flag_eg:",
			"image": "1f1ea-1f1ec"
		}, {
			"name": ":flag_sv:",
			"image": "1f1f8-1f1fb"
		}, {
			"name": ":flag_gq:",
			"image": "1f1ec-1f1f6"
		}, {
			"name": ":flag_er:",
			"image": "1f1ea-1f1f7"
		}, {
			"name": ":flag_ee:",
			"image": "1f1ea-1f1ea"
		}, {
			"name": ":flag_et:",
			"image": "1f1ea-1f1f9"
		}, {
			"name": ":flag_fk:",
			"image": "1f1eb-1f1f0"
		}, {
			"name": ":flag_fo:",
			"image": "1f1eb-1f1f4"
		}, {
			"name": ":flag_fj:",
			"image": "1f1eb-1f1ef"
		}, {
			"name": ":flag_fi:",
			"image": "1f1eb-1f1ee"
		}, {
			"name": ":flag_fr:",
			"image": "1f1eb-1f1f7"
		}, {
			"name": ":flag_pf:",
			"image": "1f1f5-1f1eb"
		}, {
			"name": ":flag_ga:",
			"image": "1f1ec-1f1e6"
		}, {
			"name": ":flag_gm:",
			"image": "1f1ec-1f1f2"
		}, {
			"name": ":flag_ge:",
			"image": "1f1ec-1f1ea"
		}, {
			"name": ":flag_de:",
			"image": "1f1e9-1f1ea"
		}, {
			"name": ":flag_gh:",
			"image": "1f1ec-1f1ed"
		}, {
			"name": ":flag_gi:",
			"image": "1f1ec-1f1ee"
		}, {
			"name": ":flag_gr:",
			"image": "1f1ec-1f1f7"
		}, {
			"name": ":flag_gl:",
			"image": "1f1ec-1f1f1"
		}, {
			"name": ":flag_gd:",
			"image": "1f1ec-1f1e9"
		}, {
			"name": ":flag_gu:",
			"image": "1f1ec-1f1fa"
		}, {
			"name": ":flag_gt:",
			"image": "1f1ec-1f1f9"
		}, {
			"name": ":flag_gn:",
			"image": "1f1ec-1f1f3"
		}, {
			"name": ":flag_gw:",
			"image": "1f1ec-1f1fc"
		}, {
			"name": ":flag_gy:",
			"image": "1f1ec-1f1fe"
		}, {
			"name": ":flag_ht:",
			"image": "1f1ed-1f1f9"
		}, {
			"name": ":flag_hn:",
			"image": "1f1ed-1f1f3"
		}, {
			"name": ":flag_hk:",
			"image": "1f1ed-1f1f0"
		}, {
			"name": ":flag_hu:",
			"image": "1f1ed-1f1fa"
		}, {
			"name": ":flag_is:",
			"image": "1f1ee-1f1f8"
		}, {
			"name": ":flag_in:",
			"image": "1f1ee-1f1f3"
		}, {
			"name": ":flag_id:",
			"image": "1f1ee-1f1e9"
		}, {
			"name": ":flag_ir:",
			"image": "1f1ee-1f1f7"
		}, {
			"name": ":flag_iq:",
			"image": "1f1ee-1f1f6"
		}, {
			"name": ":flag_ie:",
			"image": "1f1ee-1f1ea"
		}, {
			"name": ":flag_il:",
			"image": "1f1ee-1f1f1"
		}, {
			"name": ":flag_it:",
			"image": "1f1ee-1f1f9"
		}, {
			"name": ":flag_ci:",
			"image": "1f1e8-1f1ee"
		}, {
			"name": ":flag_jm:",
			"image": "1f1ef-1f1f2"
		}, {
			"name": ":flag_jp:",
			"image": "1f1ef-1f1f5"
		}, {
			"name": ":flag_je:",
			"image": "1f1ef-1f1ea"
		}, {
			"name": ":flag_jo:",
			"image": "1f1ef-1f1f4"
		}, {
			"name": ":flag_kz:",
			"image": "1f1f0-1f1ff"
		}, {
			"name": ":flag_ke:",
			"image": "1f1f0-1f1ea"
		}, {
			"name": ":flag_ki:",
			"image": "1f1f0-1f1ee"
		}, {
			"name": ":flag_xk:",
			"image": "1f1fd-1f1f0"
		}, {
			"name": ":flag_kw:",
			"image": "1f1f0-1f1fc"
		}, {
			"name": ":flag_kg:",
			"image": "1f1f0-1f1ec"
		}, {
			"name": ":flag_la:",
			"image": "1f1f1-1f1e6"
		}, {
			"name": ":flag_lv:",
			"image": "1f1f1-1f1fb"
		}, {
			"name": ":flag_lb:",
			"image": "1f1f1-1f1e7"
		}, {
			"name": ":flag_ls:",
			"image": "1f1f1-1f1f8"
		}, {
			"name": ":flag_lr:",
			"image": "1f1f1-1f1f7"
		}, {
			"name": ":flag_ly:",
			"image": "1f1f1-1f1fe"
		}, {
			"name": ":flag_li:",
			"image": "1f1f1-1f1ee"
		}, {
			"name": ":flag_lt:",
			"image": "1f1f1-1f1f9"
		}, {
			"name": ":flag_lu:",
			"image": "1f1f1-1f1fa"
		}, {
			"name": ":flag_mo:",
			"image": "1f1f2-1f1f4"
		}, {
			"name": ":flag_mk:",
			"image": "1f1f2-1f1f0"
		}, {
			"name": ":flag_mg:",
			"image": "1f1f2-1f1ec"
		}, {
			"name": ":flag_mw:",
			"image": "1f1f2-1f1fc"
		}, {
			"name": ":flag_my:",
			"image": "1f1f2-1f1fe"
		}, {
			"name": ":flag_mv:",
			"image": "1f1f2-1f1fb"
		}, {
			"name": ":flag_ml:",
			"image": "1f1f2-1f1f1"
		}, {
			"name": ":flag_mt:",
			"image": "1f1f2-1f1f9"
		}, {
			"name": ":flag_mh:",
			"image": "1f1f2-1f1ed"
		}, {
			"name": ":flag_mr:",
			"image": "1f1f2-1f1f7"
		}, {
			"name": ":flag_mu:",
			"image": "1f1f2-1f1fa"
		}, {
			"name": ":flag_mx:",
			"image": "1f1f2-1f1fd"
		}, {
			"name": ":flag_fm:",
			"image": "1f1eb-1f1f2"
		}, {
			"name": ":flag_md:",
			"image": "1f1f2-1f1e9"
		}, {
			"name": ":flag_mc:",
			"image": "1f1f2-1f1e8"
		}, {
			"name": ":flag_mn:",
			"image": "1f1f2-1f1f3"
		}, {
			"name": ":flag_me:",
			"image": "1f1f2-1f1ea"
		}, {
			"name": ":flag_ms:",
			"image": "1f1f2-1f1f8"
		}, {
			"name": ":flag_ma:",
			"image": "1f1f2-1f1e6"
		}, {
			"name": ":flag_mz:",
			"image": "1f1f2-1f1ff"
		}, {
			"name": ":flag_mm:",
			"image": "1f1f2-1f1f2"
		}, {
			"name": ":flag_na:",
			"image": "1f1f3-1f1e6"
		}, {
			"name": ":flag_nr:",
			"image": "1f1f3-1f1f7"
		}, {
			"name": ":flag_np:",
			"image": "1f1f3-1f1f5"
		}, {
			"name": ":flag_nl:",
			"image": "1f1f3-1f1f1"
		}, {
			"name": ":flag_nc:",
			"image": "1f1f3-1f1e8"
		}, {
			"name": ":flag_nz:",
			"image": "1f1f3-1f1ff"
		}, {
			"name": ":flag_ni:",
			"image": "1f1f3-1f1ee"
		}, {
			"name": ":flag_ne:",
			"image": "1f1f3-1f1ea"
		}, {
			"name": ":flag_ng:",
			"image": "1f1f3-1f1ec"
		}, {
			"name": ":flag_nu:",
			"image": "1f1f3-1f1fa"
		}, {
			"name": ":flag_kp:",
			"image": "1f1f0-1f1f5"
		}, {
			"name": ":flag_no:",
			"image": "1f1f3-1f1f4"
		}, {
			"name": ":flag_om:",
			"image": "1f1f4-1f1f2"
		}, {
			"name": ":flag_pk:",
			"image": "1f1f5-1f1f0"
		}, {
			"name": ":flag_pw:",
			"image": "1f1f5-1f1fc"
		}, {
			"name": ":flag_ps:",
			"image": "1f1f5-1f1f8"
		}, {
			"name": ":flag_pa:",
			"image": "1f1f5-1f1e6"
		}, {
			"name": ":flag_pg:",
			"image": "1f1f5-1f1ec"
		}, {
			"name": ":flag_py:",
			"image": "1f1f5-1f1fe"
		}, {
			"name": ":flag_pe:",
			"image": "1f1f5-1f1ea"
		}, {
			"name": ":flag_ph:",
			"image": "1f1f5-1f1ed"
		}, {
			"name": ":flag_pl:",
			"image": "1f1f5-1f1f1"
		}, {
			"name": ":flag_pt:",
			"image": "1f1f5-1f1f9"
		}, {
			"name": ":flag_pr:",
			"image": "1f1f5-1f1f7"
		}, {
			"name": ":flag_qa:",
			"image": "1f1f6-1f1e6"
		}, {
			"name": ":flag_ro:",
			"image": "1f1f7-1f1f4"
		}, {
			"name": ":flag_ru:",
			"image": "1f1f7-1f1fa"
		}, {
			"name": ":flag_rw:",
			"image": "1f1f7-1f1fc"
		}, {
			"name": ":flag_sh:",
			"image": "1f1f8-1f1ed"
		}, {
			"name": ":flag_kn:",
			"image": "1f1f0-1f1f3"
		}, {
			"name": ":flag_lc:",
			"image": "1f1f1-1f1e8"
		}, {
			"name": ":flag_vc:",
			"image": "1f1fb-1f1e8"
		}, {
			"name": ":flag_ws:",
			"image": "1f1fc-1f1f8"
		}, {
			"name": ":flag_sm:",
			"image": "1f1f8-1f1f2"
		}, {
			"name": ":flag_st:",
			"image": "1f1f8-1f1f9"
		}, {
			"name": ":flag_sa:",
			"image": "1f1f8-1f1e6"
		}, {
			"name": ":flag_sn:",
			"image": "1f1f8-1f1f3"
		}, {
			"name": ":flag_rs:",
			"image": "1f1f7-1f1f8"
		}, {
			"name": ":flag_sc:",
			"image": "1f1f8-1f1e8"
		}, {
			"name": ":flag_sl:",
			"image": "1f1f8-1f1f1"
		}, {
			"name": ":flag_sg:",
			"image": "1f1f8-1f1ec"
		}, {
			"name": ":flag_sk:",
			"image": "1f1f8-1f1f0"
		}, {
			"name": ":flag_si:",
			"image": "1f1f8-1f1ee"
		}, {
			"name": ":flag_sb:",
			"image": "1f1f8-1f1e7"
		}, {
			"name": ":flag_so:",
			"image": "1f1f8-1f1f4"
		}, {
			"name": ":flag_za:",
			"image": "1f1ff-1f1e6"
		}, {
			"name": ":flag_kr:",
			"image": "1f1f0-1f1f7"
		}, {
			"name": ":flag_es:",
			"image": "1f1ea-1f1f8"
		}, {
			"name": ":flag_lk:",
			"image": "1f1f1-1f1f0"
		}, {
			"name": ":flag_sd:",
			"image": "1f1f8-1f1e9"
		}, {
			"name": ":flag_sr:",
			"image": "1f1f8-1f1f7"
		}, {
			"name": ":flag_sz:",
			"image": "1f1f8-1f1ff"
		}, {
			"name": ":flag_se:",
			"image": "1f1f8-1f1ea"
		}, {
			"name": ":flag_ch:",
			"image": "1f1e8-1f1ed"
		}, {
			"name": ":flag_sy:",
			"image": "1f1f8-1f1fe"
		}, {
			"name": ":flag_tw:",
			"image": "1f1f9-1f1fc"
		}, {
			"name": ":flag_tj:",
			"image": "1f1f9-1f1ef"
		}, {
			"name": ":flag_tz:",
			"image": "1f1f9-1f1ff"
		}, {
			"name": ":flag_th:",
			"image": "1f1f9-1f1ed"
		}, {
			"name": ":flag_tl:",
			"image": "1f1f9-1f1f1"
		}, {
			"name": ":flag_tg:",
			"image": "1f1f9-1f1ec"
		}, {
			"name": ":flag_to:",
			"image": "1f1f9-1f1f4"
		}, {
			"name": ":flag_tt:",
			"image": "1f1f9-1f1f9"
		}, {
			"name": ":flag_tn:",
			"image": "1f1f9-1f1f3"
		}, {
			"name": ":flag_tr:",
			"image": "1f1f9-1f1f7"
		}, {
			"name": ":flag_tm:",
			"image": "1f1f9-1f1f2"
		}, {
			"name": ":flag_tv:",
			"image": "1f1f9-1f1fb"
		}, {
			"name": ":flag_ug:",
			"image": "1f1fa-1f1ec"
		}, {
			"name": ":flag_ua:",
			"image": "1f1fa-1f1e6"
		}, {
			"name": ":flag_ae:",
			"image": "1f1e6-1f1ea"
		}, {
			"name": ":flag_gb:",
			"image": "1f1ec-1f1e7"
		}, {
			"name": ":flag_us:",
			"image": "1f1fa-1f1f8"
		}, {
			"name": ":flag_vi:",
			"image": "1f1fb-1f1ee"
		}, {
			"name": ":flag_uy:",
			"image": "1f1fa-1f1fe"
		}, {
			"name": ":flag_uz:",
			"image": "1f1fa-1f1ff"
		}, {
			"name": ":flag_vu:",
			"image": "1f1fb-1f1fa"
		}, {
			"name": ":flag_va:",
			"image": "1f1fb-1f1e6"
		}, {
			"name": ":flag_ve:",
			"image": "1f1fb-1f1ea"
		}, {
			"name": ":flag_vn:",
			"image": "1f1fb-1f1f3"
		}, {
			"name": ":flag_wf:",
			"image": "1f1fc-1f1eb"
		}, {
			"name": ":flag_eh:",
			"image": "1f1ea-1f1ed"
		}, {
			"name": ":flag_ye:",
			"image": "1f1fe-1f1ea"
		}, {
			"name": ":flag_zm:",
			"image": "1f1ff-1f1f2"
		}, {
			"name": ":flag_zw:",
			"image": "1f1ff-1f1fc"
		}, {
			"name": ":flag_re:",
			"image": "1f1f7-1f1ea"
		}, {
			"name": ":flag_ax:",
			"image": "1f1e6-1f1fd"
		}, {
			"name": ":flag_ta:",
			"image": "1f1f9-1f1e6"
		}, {
			"name": ":flag_io:",
			"image": "1f1ee-1f1f4"
		}, {
			"name": ":flag_bq:",
			"image": "1f1e7-1f1f6"
		}, {
			"name": ":flag_cx:",
			"image": "1f1e8-1f1fd"
		}, {
			"name": ":flag_cc:",
			"image": "1f1e8-1f1e8"
		}, {
			"name": ":flag_gg:",
			"image": "1f1ec-1f1ec"
		}, {
			"name": ":flag_im:",
			"image": "1f1ee-1f1f2"
		}, {
			"name": ":flag_yt:",
			"image": "1f1fe-1f1f9"
		}, {
			"name": ":flag_nf:",
			"image": "1f1f3-1f1eb"
		}, {
			"name": ":flag_pn:",
			"image": "1f1f5-1f1f3"
		}, {
			"name": ":flag_bl:",
			"image": "1f1e7-1f1f1"
		}, {
			"name": ":flag_pm:",
			"image": "1f1f5-1f1f2"
		}, {
			"name": ":flag_gs:",
			"image": "1f1ec-1f1f8"
		}, {
			"name": ":flag_tk:",
			"image": "1f1f9-1f1f0"
		}, {
			"name": ":flag_bv:",
			"image": "1f1e7-1f1fb"
		}, {
			"name": ":flag_hm:",
			"image": "1f1ed-1f1f2"
		}, {
			"name": ":flag_sj:",
			"image": "1f1f8-1f1ef"
		}, {
			"name": ":flag_um:",
			"image": "1f1fa-1f1f2"
		}, {
			"name": ":flag_ic:",
			"image": "1f1ee-1f1e8"
		}, {
			"name": ":flag_ea:",
			"image": "1f1ea-1f1e6"
		}, {
			"name": ":flag_cp:",
			"image": "1f1e8-1f1f5"
		}, {
			"name": ":flag_dg:",
			"image": "1f1e9-1f1ec"
		}, {
			"name": ":flag_as:",
			"image": "1f1e6-1f1f8"
		}, {
			"name": ":flag_aq:",
			"image": "1f1e6-1f1f6"
		}, {
			"name": ":flag_vg:",
			"image": "1f1fb-1f1ec"
		}, {
			"name": ":flag_ck:",
			"image": "1f1e8-1f1f0"
		}, {
			"name": ":flag_cw:",
			"image": "1f1e8-1f1fc"
		}, {
			"name": ":flag_eu:",
			"image": "1f1ea-1f1fa"
		}, {
			"name": ":flag_gf:",
			"image": "1f1ec-1f1eb"
		}, {
			"name": ":flag_tf:",
			"image": "1f1f9-1f1eb"
		}, {
			"name": ":flag_gp:",
			"image": "1f1ec-1f1f5"
		}, {
			"name": ":flag_mq:",
			"image": "1f1f2-1f1f6"
		}, {
			"name": ":flag_mp:",
			"image": "1f1f2-1f1f5"
		}, {
			"name": ":flag_sx:",
			"image": "1f1f8-1f1fd"
		}, {
			"name": ":flag_ss:",
			"image": "1f1f8-1f1f8"
		}, {
			"name": ":flag_tc:",
			"image": "1f1f9-1f1e8"
		}, {
			"name": ":flag_mf:",
			"image": "1f1f2-1f1eb"
		}, {
			"name": ":gay_pride_flag:",
			"image": "1f3f3-fe0f-200d-1f308"
		}]
	}
]

// List of emojis
smileys.emojis = {
	"100": "💯",
	"1234": "🔢",
	"grinning": "😀",
	"grimacing": "😬",
	"grin": "😁",
	"joy": "😂",
	"smiley": "😃",
	"smile": "😄",
	"sweat_smile": "😅",
	"laughing": "😆",
	"satisfied": "😆",
	"innocent": "😇",
	"wink": "😉",
	"blush": "😊",
	"relaxed": "☺",
	"yum": "😋",
	"relieved": "😌",
	"heart_eyes": "😍",
	"kissing_heart": "😘",
	"kissing": "😗",
	"kissing_smiling_eyes": "😙",
	"kissing_closed_eyes": "😚",
	"stuck_out_tongue_winking_eye": "😜",
	"stuck_out_tongue_closed_eyes": "😝",
	"stuck_out_tongue": "😛",
	"sunglasses": "😎",
	"smirk": "😏",
	"no_mouth": "😶",
	"neutral_face": "😐",
	"expressionless": "😑",
	"unamused": "😒",
	"flushed": "😳",
	"disappointed": "😞",
	"worried": "😟",
	"angry": "😠",
	"rage": "😡",
	"pensive": "😔",
	"confused": "😕",
	"persevere": "😣",
	"confounded": "😖",
	"tired_face": "😫",
	"weary": "😩",
	"triumph": "😤",
	"open_mouth": "😮",
	"scream": "😱",
	"fearful": "😨",
	"cold_sweat": "😰",
	"hushed": "😯",
	"frowning": "😦",
	"anguished": "😧",
	"cry": "😢",
	"disappointed_relieved": "😥",
	"sleepy": "😪",
	"sweat": "😓",
	"sob": "😭",
	"dizzy_face": "😵",
	"astonished": "😲",
	"mask": "😷",
	"sleeping": "😴",
	"zzz": "💤",
	"poop": "💩",
	"shit": "💩",
	"hankey": "💩",
	"poo": "💩",
	"smiling_imp": "😈",
	"imp": "👿",
	"japanese_ogre": "👹",
	"japanese_goblin": "👺",
	"skull": "💀",
	"skeleton": "💀",
	"ghost": "👻",
	"alien": "👽",
	"smiley_cat": "😺",
	"smile_cat": "😸",
	"joy_cat": "😹",
	"heart_eyes_cat": "😻",
	"smirk_cat": "😼",
	"kissing_cat": "😽",
	"scream_cat": "🙀",
	"crying_cat_face": "😿",
	"pouting_cat": "😾",
	"raised_hands": "🙌",
	"clap": "👏",
	"wave": "👋",
	"thumbsup": "👍",
	"+1": "👍",
	"thumbup": "👍",
	"thumbsdown": "👎",
	"-1": "👎",
	"thumbdown": "👎",
	"punch": "👊",
	"fist": "✊",
	"v": "✌",
	"ok_hand": "👌",
	"raised_hand": "✋",
	"open_hands": "👐",
	"muscle": "💪",
	"pray": "🙏",
	"point_up": "☝",
	"point_up_2": "👆",
	"point_down": "👇",
	"point_left": "👈",
	"point_right": "👉",
	"nail_care": "💅",
	"lips": "👄",
	"tongue": "👅",
	"ear": "👂",
	"nose": "👃",
	"eyes": "👀",
	"bust_in_silhouette": "👤",
	"busts_in_silhouette": "👥",
	"baby": "👶",
	"boy": "👦",
	"girl": "👧",
	"man": "👨",
	"woman": "👩",
	"person_with_blond_hair": "👱",
	"older_man": "👴",
	"older_woman": "👵",
	"grandma": "👵",
	"man_with_gua_pi_mao": "👲",
	"man_with_turban": "👳",
	"cop": "👮",
	"construction_worker": "👷",
	"guardsman": "💂",
	"santa": "🎅",
	"angel": "👼",
	"princess": "👸",
	"bride_with_veil": "👰",
	"walking": "🚶",
	"runner": "🏃",
	"dancer": "💃",
	"dancers": "👯",
	"couple": "👫",
	"two_men_holding_hands": "👬",
	"two_women_holding_hands": "👭",
	"bow": "🙇",
	"information_desk_person": "💁",
	"no_good": "🙅",
	"ok_woman": "🙆",
	"raising_hand": "🙋",
	"person_with_pouting_face": "🙎",
	"person_frowning": "🙍",
	"haircut": "💇",
	"massage": "💆",
	"couple_with_heart": "💑",
	"couple_ww": "👩‍❤️‍👩",
	"couple_with_heart_ww": "👩‍❤️‍👩",
	"couple_mm": "👨‍❤️‍👨",
	"couple_with_heart_mm": "👨‍❤️‍👨",
	"couplekiss": "💏",
	"kiss_ww": "👩‍❤️‍💋‍👩",
	"couplekiss_ww": "👩‍❤️‍💋‍👩",
	"kiss_mm": "👨‍❤️‍💋‍👨",
	"couplekiss_mm": "👨‍❤️‍💋‍👨",
	"family": "👪",
	"family_mwg": "👨‍👩‍👧",
	"family_mwgb": "👨‍👩‍👧‍👦",
	"family_mwbb": "👨‍👩‍👦‍👦",
	"family_mwgg": "👨‍👩‍👧‍👧",
	"family_wwb": "👩‍👩‍👦",
	"family_wwg": "👩‍👩‍👧",
	"family_wwgb": "👩‍👩‍👧‍👦",
	"family_wwbb": "👩‍👩‍👦‍👦",
	"family_wwgg": "👩‍👩‍👧‍👧",
	"family_mmb": "👨‍👨‍👦",
	"family_mmg": "👨‍👨‍👧",
	"family_mmgb": "👨‍👨‍👧‍👦",
	"family_mmbb": "👨‍👨‍👦‍👦",
	"family_mmgg": "👨‍👨‍👧‍👧",
	"womans_clothes": "👚",
	"shirt": "👕",
	"jeans": "👖",
	"necktie": "👔",
	"dress": "👗",
	"bikini": "👙",
	"kimono": "👘",
	"lipstick": "💄",
	"kiss": "💋",
	"footprints": "👣",
	"high_heel": "👠",
	"sandal": "👡",
	"boot": "👢",
	"mans_shoe": "👞",
	"athletic_shoe": "👟",
	"womans_hat": "👒",
	"tophat": "🎩",
	"mortar_board": "🎓",
	"crown": "👑",
	"school_satchel": "🎒",
	"pouch": "👝",
	"purse": "👛",
	"handbag": "👜",
	"briefcase": "💼",
	"eyeglasses": "👓",
	"ring": "💍",
	"closed_umbrella": "🌂",
	"dog": "🐶",
	"cat": "🐱",
	"mouse": "🐭",
	"hamster": "🐹",
	"rabbit": "🐰",
	"bear": "🐻",
	"panda_face": "🐼",
	"koala": "🐨",
	"tiger": "🐯",
	"cow": "🐮",
	"pig": "🐷",
	"pig_nose": "🐽",
	"frog": "🐸",
	"octopus": "🐙",
	"monkey_face": "🐵",
	"see_no_evil": "🙈",
	"hear_no_evil": "🙉",
	"speak_no_evil": "🙊",
	"monkey": "🐒",
	"chicken": "🐔",
	"penguin": "🐧",
	"bird": "🐦",
	"baby_chick": "🐤",
	"hatching_chick": "🐣",
	"hatched_chick": "🐥",
	"wolf": "🐺",
	"boar": "🐗",
	"horse": "🐴",
	"bee": "🐝",
	"bug": "🐛",
	"snail": "🐌",
	"beetle": "🐞",
	"ant": "🐜",
	"snake": "🐍",
	"turtle": "🐢",
	"tropical_fish": "🐠",
	"fish": "🐟",
	"blowfish": "🐡",
	"dolphin": "🐬",
	"whale": "🐳",
	"whale2": "🐋",
	"crocodile": "🐊",
	"leopard": "🐆",
	"tiger2": "🐅",
	"water_buffalo": "🐃",
	"ox": "🐂",
	"cow2": "🐄",
	"dromedary_camel": "🐪",
	"camel": "🐫",
	"elephant": "🐘",
	"goat": "🐐",
	"ram": "🐏",
	"sheep": "🐑",
	"racehorse": "🐎",
	"pig2": "🐖",
	"rat": "🐀",
	"mouse2": "🐁",
	"rooster": "🐓",
	"dog2": "🐕",
	"poodle": "🐩",
	"cat2": "🐈",
	"rabbit2": "🐇",
	"feet": "🐾",
	"paw_prints": "🐾",
	"dragon": "🐉",
	"dragon_face": "🐲",
	"cactus": "🌵",
	"christmas_tree": "🎄",
	"evergreen_tree": "🌲",
	"deciduous_tree": "🌳",
	"palm_tree": "🌴",
	"seedling": "🌱",
	"herb": "🌿",
	"four_leaf_clover": "🍀",
	"bamboo": "🎍",
	"tanabata_tree": "🎋",
	"leaves": "🍃",
	"fallen_leaf": "🍂",
	"maple_leaf": "🍁",
	"ear_of_rice": "🌾",
	"hibiscus": "🌺",
	"sunflower": "🌻",
	"rose": "🌹",
	"tulip": "🌷",
	"blossom": "🌼",
	"cherry_blossom": "🌸",
	"bouquet": "💐",
	"mushroom": "🍄",
	"chestnut": "🌰",
	"jack_o_lantern": "🎃",
	"shell": "🐚",
	"earth_americas": "🌎",
	"earth_africa": "🌍",
	"earth_asia": "🌏",
	"full_moon": "🌕",
	"waning_gibbous_moon": "🌖",
	"last_quarter_moon": "🌗",
	"waning_crescent_moon": "🌘",
	"new_moon": "🌑",
	"waxing_crescent_moon": "🌒",
	"first_quarter_moon": "🌓",
	"waxing_gibbous_moon": "🌔",
	"new_moon_with_face": "🌚",
	"full_moon_with_face": "🌝",
	"first_quarter_moon_with_face": "🌛",
	"last_quarter_moon_with_face": "🌜",
	"sun_with_face": "🌞",
	"crescent_moon": "🌙",
	"star": "⭐",
	"star2": "🌟",
	"dizzy": "💫",
	"sparkles": "✨",
	"sunny": "☀",
	"partly_sunny": "⛅",
	"cloud": "☁",
	"zap": "⚡",
	"fire": "🔥",
	"flame": "🔥",
	"boom": "💥",
	"snowflake": "❄",
	"snowman": "⛄",
	"dash": "💨",
	"umbrella": "☔",
	"droplet": "💧",
	"sweat_drops": "💦",
	"ocean": "🌊",
	"green_apple": "🍏",
	"apple": "🍎",
	"pear": "🍐",
	"tangerine": "🍊",
	"lemon": "🍋",
	"banana": "🍌",
	"watermelon": "🍉",
	"grapes": "🍇",
	"strawberry": "🍓",
	"melon": "🍈",
	"cherries": "🍒",
	"peach": "🍑",
	"pineapple": "🍍",
	"tomato": "🍅",
	"eggplant": "🍆",
	"corn": "🌽",
	"sweet_potato": "🍠",
	"honey_pot": "🍯",
	"bread": "🍞",
	"poultry_leg": "🍗",
	"meat_on_bone": "🍖",
	"fried_shrimp": "🍤",
	"cooking": "🍳",
	"hamburger": "🍔",
	"fries": "🍟",
	"pizza": "🍕",
	"spaghetti": "🍝",
	"ramen": "🍜",
	"stew": "🍲",
	"fish_cake": "🍥",
	"sushi": "🍣",
	"bento": "🍱",
	"curry": "🍛",
	"rice_ball": "🍙",
	"rice": "🍚",
	"rice_cracker": "🍘",
	"oden": "🍢",
	"dango": "🍡",
	"shaved_ice": "🍧",
	"ice_cream": "🍨",
	"icecream": "🍦",
	"cake": "🍰",
	"birthday": "🎂",
	"custard": "🍮",
	"pudding": "🍮",
	"flan": "🍮",
	"candy": "🍬",
	"lollipop": "🍭",
	"chocolate_bar": "🍫",
	"doughnut": "🍩",
	"cookie": "🍪",
	"beer": "🍺",
	"beers": "🍻",
	"wine_glass": "🍷",
	"cocktail": "🍸",
	"tropical_drink": "🍹",
	"sake": "🍶",
	"tea": "🍵",
	"coffee": "☕",
	"baby_bottle": "🍼",
	"fork_and_knife": "🍴",
	"soccer": "⚽",
	"basketball": "🏀",
	"football": "🏈",
	"baseball": "⚾",
	"tennis": "🎾",
	"rugby_football": "🏉",
	"8ball": "🎱",
	"golf": "⛳",
	"ski": "🎿",
	"snowboarder": "🏂",
	"fishing_pole_and_fish": "🎣",
	"rowboat": "🚣",
	"swimmer": "🏊",
	"surfer": "🏄",
	"bath": "🛀",
	"bicyclist": "🚴",
	"mountain_bicyclist": "🚵",
	"horse_racing": "🏇",
	"trophy": "🏆",
	"running_shirt_with_sash": "🎽",
	"ticket": "🎫",
	"performing_arts": "🎭",
	"art": "🎨",
	"circus_tent": "🎪",
	"microphone": "🎤",
	"headphones": "🎧",
	"musical_score": "🎼",
	"musical_keyboard": "🎹",
	"saxophone": "🎷",
	"trumpet": "🎺",
	"guitar": "🎸",
	"violin": "🎻",
	"clapper": "🎬",
	"video_game": "🎮",
	"space_invader": "👾",
	"dart": "🎯",
	"game_die": "🎲",
	"slot_machine": "🎰",
	"bowling": "🎳",
	"red_car": "🚗",
	"taxi": "🚕",
	"blue_car": "🚙",
	"bus": "🚌",
	"trolleybus": "🚎",
	"police_car": "🚓",
	"ambulance": "🚑",
	"fire_engine": "🚒",
	"minibus": "🚐",
	"truck": "🚚",
	"articulated_lorry": "🚛",
	"tractor": "🚜",
	"bike": "🚲",
	"rotating_light": "🚨",
	"oncoming_police_car": "🚔",
	"oncoming_bus": "🚍",
	"oncoming_automobile": "🚘",
	"oncoming_taxi": "🚖",
	"aerial_tramway": "🚡",
	"mountain_cableway": "🚠",
	"suspension_railway": "🚟",
	"railway_car": "🚃",
	"train": "🚋",
	"monorail": "🚝",
	"bullettrain_side": "🚄",
	"bullettrain_front": "🚅",
	"light_rail": "🚈",
	"mountain_railway": "🚞",
	"steam_locomotive": "🚂",
	"train2": "🚆",
	"metro": "🚇",
	"tram": "🚊",
	"station": "🚉",
	"helicopter": "🚁",
	"airplane": "✈",
	"sailboat": "⛵",
	"speedboat": "🚤",
	"rocket": "🚀",
	"seat": "💺",
	"anchor": "⚓",
	"construction": "🚧",
	"fuelpump": "⛽",
	"busstop": "🚏",
	"vertical_traffic_light": "🚦",
	"traffic_light": "🚥",
	"checkered_flag": "🏁",
	"ship": "🚢",
	"ferris_wheel": "🎡",
	"roller_coaster": "🎢",
	"carousel_horse": "🎠",
	"foggy": "🌁",
	"tokyo_tower": "🗼",
	"factory": "🏭",
	"fountain": "⛲",
	"rice_scene": "🎑",
	"mount_fuji": "🗻",
	"volcano": "🌋",
	"japan": "🗾",
	"tent": "⛺",
	"sunrise": "🌅",
	"sunrise_over_mountains": "🌄",
	"city_sunset": "🌇",
	"city_sunrise": "🌇",
	"city_dusk": "🌆",
	"night_with_stars": "🌃",
	"bridge_at_night": "🌉",
	"milky_way": "🌌",
	"stars": "🌠",
	"sparkler": "🎇",
	"fireworks": "🎆",
	"rainbow": "🌈",
	"european_castle": "🏰",
	"japanese_castle": "🏯",
	"statue_of_liberty": "🗽",
	"house": "🏠",
	"house_with_garden": "🏡",
	"office": "🏢",
	"department_store": "🏬",
	"post_office": "🏣",
	"european_post_office": "🏤",
	"hospital": "🏥",
	"bank": "🏦",
	"hotel": "🏨",
	"convenience_store": "🏪",
	"school": "🏫",
	"love_hotel": "🏩",
	"wedding": "💒",
	"church": "⛪",
	"watch": "⌚",
	"iphone": "📱",
	"calling": "📲",
	"computer": "💻",
	"minidisc": "💽",
	"floppy_disk": "💾",
	"cd": "💿",
	"dvd": "📀",
	"vhs": "📼",
	"camera": "📷",
	"video_camera": "📹",
	"movie_camera": "🎥",
	"telephone_receiver": "📞",
	"telephone": "☎",
	"pager": "📟",
	"fax": "📠",
	"tv": "📺",
	"radio": "📻",
	"alarm_clock": "⏰",
	"hourglass_flowing_sand": "⏳",
	"hourglass": "⌛",
	"satellite": "📡",
	"battery": "🔋",
	"electric_plug": "🔌",
	"bulb": "💡",
	"flashlight": "🔦",
	"money_with_wings": "💸",
	"dollar": "💵",
	"yen": "💴",
	"euro": "💶",
	"pound": "💷",
	"moneybag": "💰",
	"credit_card": "💳",
	"gem": "💎",
	"wrench": "🔧",
	"hammer": "🔨",
	"nut_and_bolt": "🔩",
	"gun": "🔫",
	"bomb": "💣",
	"knife": "🔪",
	"smoking": "🚬",
	"crystal_ball": "🔮",
	"barber": "💈",
	"telescope": "🔭",
	"microscope": "🔬",
	"pill": "💊",
	"syringe": "💉",
	"bookmark": "🔖",
	"toilet": "🚽",
	"shower": "🚿",
	"bathtub": "🛁",
	"key": "🔑",
	"door": "🚪",
	"moyai": "🗿",
	"balloon": "🎈",
	"flags": "🎏",
	"ribbon": "🎀",
	"gift": "🎁",
	"confetti_ball": "🎊",
	"tada": "🎉",
	"dolls": "🎎",
	"wind_chime": "🎐",
	"crossed_flags": "🎌",
	"izakaya_lantern": "🏮",
	"envelope": "✉",
	"envelope_with_arrow": "📩",
	"incoming_envelope": "📨",
	"e_mail": "📧",
	"email": "📧",
	"love_letter": "💌",
	"postbox": "📮",
	"mailbox_closed": "📪",
	"mailbox": "📫",
	"mailbox_with_mail": "📬",
	"mailbox_with_no_mail": "📭",
	"package": "📦",
	"postal_horn": "📯",
	"inbox_tray": "📥",
	"outbox_tray": "📤",
	"scroll": "📜",
	"page_with_curl": "📃",
	"bookmark_tabs": "📑",
	"bar_chart": "📊",
	"chart_with_upwards_trend": "📈",
	"chart_with_downwards_trend": "📉",
	"page_facing_up": "📄",
	"date": "📅",
	"calendar": "📆",
	"card_index": "📇",
	"clipboard": "📋",
	"file_folder": "📁",
	"open_file_folder": "📂",
	"newspaper": "📰",
	"notebook": "📓",
	"closed_book": "📕",
	"green_book": "📗",
	"blue_book": "📘",
	"orange_book": "📙",
	"notebook_with_decorative_cover": "📔",
	"ledger": "📒",
	"books": "📚",
	"book": "📖",
	"link": "🔗",
	"paperclip": "📎",
	"scissors": "✂",
	"triangular_ruler": "📐",
	"straight_ruler": "📏",
	"pushpin": "📌",
	"round_pushpin": "📍",
	"triangular_flag_on_post": "🚩",
	"closed_lock_with_key": "🔐",
	"lock": "🔒",
	"unlock": "🔓",
	"lock_with_ink_pen": "🔏",
	"black_nib": "✒",
	"pencil": "📝",
	"pencil2": "✏",
	"mag": "🔍",
	"mag_right": "🔎",
	"heart": "❤",
	"yellow_heart": "💛",
	"green_heart": "💚",
	"blue_heart": "💙",
	"purple_heart": "💜",
	"broken_heart": "💔",
	"two_hearts": "💕",
	"revolving_hearts": "💞",
	"heartbeat": "💓",
	"heartpulse": "💗",
	"sparkling_heart": "💖",
	"cupid": "💘",
	"gift_heart": "💝",
	"heart_decoration": "💟",
	"six_pointed_star": "🔯",
	"ophiuchus": "⛎",
	"aries": "♈",
	"taurus": "♉",
	"gemini": "♊",
	"cancer": "♋",
	"leo": "♌",
	"virgo": "♍",
	"libra": "♎",
	"scorpius": "♏",
	"sagittarius": "♐",
	"capricorn": "♑",
	"aquarius": "♒",
	"pisces": "♓",
	"id": "🆔",
	"u7a7a": "🈳",
	"u5272": "🈹",
	"mobile_phone_off": "📴",
	"vibration_mode": "📳",
	"u6709": "🈶",
	"u7121": "🈚",
	"u7533": "🈸",
	"u55b6": "🈺",
	"u6708": "🈷",
	"eight_pointed_black_star": "✴",
	"vs": "🆚",
	"accept": "🉑",
	"white_flower": "💮",
	"ideograph_advantage": "🉐",
	"secret": "㊙",
	"congratulations": "㊗",
	"u5408": "🈴",
	"u6e80": "🈵",
	"u7981": "🈲",
	"a": "🅰",
	"b": "🅱",
	"ab": "🆎",
	"cl": "🆑",
	"o2": "🅾",
	"sos": "🆘",
	"no_entry": "⛔",
	"name_badge": "📛",
	"no_entry_sign": "🚫",
	"x": "❌",
	"o": "⭕",
	"anger": "💢",
	"hotsprings": "♨",
	"no_pedestrians": "🚷",
	"do_not_litter": "🚯",
	"no_bicycles": "🚳",
	"non_potable_water": "🚱",
	"underage": "🔞",
	"no_mobile_phones": "📵",
	"exclamation": "❗",
	"grey_exclamation": "❕",
	"question": "❓",
	"grey_question": "❔",
	"bangbang": "‼",
	"interrobang": "⁉",
	"low_brightness": "🔅",
	"high_brightness": "🔆",
	"trident": "🔱",
	"part_alternation_mark": "〽",
	"warning": "⚠",
	"children_crossing": "🚸",
	"beginner": "🔰",
	"recycle": "♻",
	"u6307": "🈯",
	"chart": "💹",
	"sparkle": "❇",
	"eight_spoked_asterisk": "✳",
	"negative_squared_cross_mark": "❎",
	"white_check_mark": "✅",
	"diamond_shape_with_a_dot_inside": "💠",
	"cyclone": "🌀",
	"loop": "➿",
	"globe_with_meridians": "🌐",
	"m": "Ⓜ",
	"atm": "🏧",
	"sa": "🈂",
	"passport_control": "🛂",
	"customs": "🛃",
	"baggage_claim": "🛄",
	"left_luggage": "🛅",
	"wheelchair": "♿",
	"no_smoking": "🚭",
	"wc": "🚾",
	"parking": "🅿",
	"potable_water": "🚰",
	"mens": "🚹",
	"womens": "🚺",
	"baby_symbol": "🚼",
	"restroom": "🚻",
	"put_litter_in_its_place": "🚮",
	"cinema": "🎦",
	"signal_strength": "📶",
	"koko": "🈁",
	"ng": "🆖",
	"ok": "🆗",
	"up": "🆙",
	"cool": "🆒",
	"new": "🆕",
	"free": "🆓",
	"zero": "0⃣",
	"one": "1⃣",
	"two": "2⃣",
	"three": "3⃣",
	"four": "4⃣",
	"five": "5⃣",
	"six": "6⃣",
	"seven": "7⃣",
	"eight": "8⃣",
	"nine": "9⃣",
	"keycap_ten": "🔟",
	"arrow_forward": "▶",
	"fast_forward": "⏩",
	"rewind": "⏪",
	"twisted_rightwards_arrows": "🔀",
	"repeat": "🔁",
	"repeat_one": "🔂",
	"arrow_backward": "◀",
	"arrow_up_small": "🔼",
	"arrow_down_small": "🔽",
	"arrow_double_up": "⏫",
	"arrow_double_down": "⏬",
	"arrow_right": "➡",
	"arrow_left": "⬅",
	"arrow_up": "⬆",
	"arrow_down": "⬇",
	"arrow_upper_right": "↗",
	"arrow_lower_right": "↘",
	"arrow_lower_left": "↙",
	"arrow_upper_left": "↖",
	"arrow_up_down": "↕",
	"left_right_arrow": "↔",
	"arrows_counterclockwise": "🔄",
	"arrow_right_hook": "↪",
	"leftwards_arrow_with_hook": "↩",
	"arrow_heading_up": "⤴",
	"arrow_heading_down": "⤵",
	"hash": "#⃣",
	"information_source": "ℹ",
	"abc": "🔤",
	"abcd": "🔡",
	"capital_abcd": "🔠",
	"symbols": "🔣",
	"musical_note": "🎵",
	"notes": "🎶",
	"wavy_dash": "〰",
	"curly_loop": "➰",
	"heavy_check_mark": "✔",
	"arrows_clockwise": "🔃",
	"heavy_plus_sign": "➕",
	"heavy_minus_sign": "➖",
	"heavy_division_sign": "➗",
	"heavy_multiplication_x": "✖",
	"heavy_dollar_sign": "💲",
	"currency_exchange": "💱",
	"copyright": "©",
	"registered": "®",
	"tm": "™",
	"end": "🔚",
	"back": "🔙",
	"on": "🔛",
	"top": "🔝",
	"soon": "🔜",
	"ballot_box_with_check": "☑",
	"radio_button": "🔘",
	"white_circle": "⚪",
	"black_circle": "⚫",
	"red_circle": "🔴",
	"large_blue_circle": "🔵",
	"small_orange_diamond": "🔸",
	"small_blue_diamond": "🔹",
	"large_orange_diamond": "🔶",
	"large_blue_diamond": "🔷",
	"small_red_triangle": "🔺",
	"black_small_square": "▪",
	"white_small_square": "▫",
	"black_large_square": "⬛",
	"white_large_square": "⬜",
	"small_red_triangle_down": "🔻",
	"black_medium_square": "◼",
	"white_medium_square": "◻",
	"black_medium_small_square": "◾",
	"white_medium_small_square": "◽",
	"black_square_button": "🔲",
	"white_square_button": "🔳",
	"speaker": "🔈",
	"sound": "🔉",
	"loud_sound": "🔊",
	"mute": "🔇",
	"mega": "📣",
	"loudspeaker": "📢",
	"bell": "🔔",
	"no_bell": "🔕",
	"black_joker": "🃏",
	"mahjong": "🀄",
	"spades": "♠",
	"clubs": "♣",
	"hearts": "♥",
	"diamonds": "♦",
	"flower_playing_cards": "🎴",
	"thought_balloon": "💭",
	"speech_balloon": "💬",
	"clock1": "🕐",
	"clock2": "🕑",
	"clock3": "🕒",
	"clock4": "🕓",
	"clock5": "🕔",
	"clock6": "🕕",
	"clock7": "🕖",
	"clock8": "🕗",
	"clock9": "🕘",
	"clock10": "🕙",
	"clock11": "🕚",
	"clock12": "🕛",
	"clock130": "🕜",
	"clock230": "🕝",
	"clock330": "🕞",
	"clock430": "🕟",
	"clock530": "🕠",
	"clock630": "🕡",
	"clock730": "🕢",
	"clock830": "🕣",
	"clock930": "🕤",
	"clock1030": "🕥",
	"clock1130": "🕦",
	"clock1230": "🕧",
	"regional_indicator_z": "🇿",
	"regional_indicator_y": "🇾",
	"regional_indicator_x": "🇽",
	"regional_indicator_w": "🇼",
	"regional_indicator_v": "🇻",
	"regional_indicator_u": "🇺",
	"regional_indicator_t": "🇹",
	"regional_indicator_s": "🇸",
	"regional_indicator_r": "🇷",
	"regional_indicator_q": "🇶",
	"regional_indicator_p": "🇵",
	"regional_indicator_o": "🇴",
	"regional_indicator_n": "🇳",
	"regional_indicator_m": "🇲",
	"regional_indicator_l": "🇱",
	"regional_indicator_k": "🇰",
	"regional_indicator_j": "🇯",
	"regional_indicator_i": "🇮",
	"regional_indicator_h": "🇭",
	"regional_indicator_g": "🇬",
	"regional_indicator_f": "🇫",
	"regional_indicator_e": "🇪",
	"regional_indicator_d": "🇩",
	"regional_indicator_c": "🇨",
	"regional_indicator_b": "🇧",
	"regional_indicator_a": "🇦",
	"flag_ac": "🇦🇨",
	"flag_af": "🇦🇫",
	"flag_al": "🇦🇱",
	"flag_dz": "🇩🇿",
	"flag_ad": "🇦🇩",
	"flag_ao": "🇦🇴",
	"flag_ai": "🇦🇮",
	"flag_ag": "🇦🇬",
	"flag_ar": "🇦🇷",
	"flag_am": "🇦🇲",
	"flag_aw": "🇦🇼",
	"flag_au": "🇦🇺",
	"flag_at": "🇦🇹",
	"flag_az": "🇦🇿",
	"flag_bs": "🇧🇸",
	"flag_bh": "🇧🇭",
	"flag_bd": "🇧🇩",
	"flag_bb": "🇧🇧",
	"flag_by": "🇧🇾",
	"flag_be": "🇧🇪",
	"flag_bz": "🇧🇿",
	"flag_bj": "🇧🇯",
	"flag_bm": "🇧🇲",
	"flag_bt": "🇧🇹",
	"flag_bo": "🇧🇴",
	"flag_ba": "🇧🇦",
	"flag_bw": "🇧🇼",
	"flag_br": "🇧🇷",
	"flag_bn": "🇧🇳",
	"flag_bg": "🇧🇬",
	"flag_bf": "🇧🇫",
	"flag_bi": "🇧🇮",
	"flag_cv": "🇨🇻",
	"flag_kh": "🇰🇭",
	"flag_cm": "🇨🇲",
	"flag_ca": "🇨🇦",
	"flag_ky": "🇰🇾",
	"flag_cf": "🇨🇫",
	"flag_td": "🇹🇩",
	"flag_cl": "🇨🇱",
	"flag_cn": "🇨🇳",
	"flag_co": "🇨🇴",
	"flag_km": "🇰🇲",
	"flag_cg": "🇨🇬",
	"flag_cd": "🇨🇩",
	"flag_cr": "🇨🇷",
	"flag_hr": "🇭🇷",
	"flag_cu": "🇨🇺",
	"flag_cy": "🇨🇾",
	"flag_cz": "🇨🇿",
	"flag_dk": "🇩🇰",
	"flag_dj": "🇩🇯",
	"flag_dm": "🇩🇲",
	"flag_do": "🇩🇴",
	"flag_ec": "🇪🇨",
	"flag_eg": "🇪🇬",
	"flag_sv": "🇸🇻",
	"flag_gq": "🇬🇶",
	"flag_er": "🇪🇷",
	"flag_ee": "🇪🇪",
	"flag_et": "🇪🇹",
	"flag_fk": "🇫🇰",
	"flag_fo": "🇫🇴",
	"flag_fj": "🇫🇯",
	"flag_fi": "🇫🇮",
	"flag_fr": "🇫🇷",
	"flag_pf": "🇵🇫",
	"flag_ga": "🇬🇦",
	"flag_gm": "🇬🇲",
	"flag_ge": "🇬🇪",
	"flag_de": "🇩🇪",
	"flag_gh": "🇬🇭",
	"flag_gi": "🇬🇮",
	"flag_gr": "🇬🇷",
	"flag_gl": "🇬🇱",
	"flag_gd": "🇬🇩",
	"flag_gu": "🇬🇺",
	"flag_gt": "🇬🇹",
	"flag_gn": "🇬🇳",
	"flag_gw": "🇬🇼",
	"flag_gy": "🇬🇾",
	"flag_ht": "🇭🇹",
	"flag_hn": "🇭🇳",
	"flag_hk": "🇭🇰",
	"flag_hu": "🇭🇺",
	"flag_is": "🇮🇸",
	"flag_in": "🇮🇳",
	"flag_id": "🇮🇩",
	"flag_ir": "🇮🇷",
	"flag_iq": "🇮🇶",
	"flag_ie": "🇮🇪",
	"flag_il": "🇮🇱",
	"flag_it": "🇮🇹",
	"flag_ci": "🇨🇮",
	"flag_jm": "🇯🇲",
	"flag_jp": "🇯🇵",
	"flag_je": "🇯🇪",
	"flag_jo": "🇯🇴",
	"flag_kz": "🇰🇿",
	"flag_ke": "🇰🇪",
	"flag_ki": "🇰🇮",
	"flag_xk": "🇽🇰",
	"flag_kw": "🇰🇼",
	"flag_kg": "🇰🇬",
	"flag_la": "🇱🇦",
	"flag_lv": "🇱🇻",
	"flag_lb": "🇱🇧",
	"flag_ls": "🇱🇸",
	"flag_lr": "🇱🇷",
	"flag_ly": "🇱🇾",
	"flag_li": "🇱🇮",
	"flag_lt": "🇱🇹",
	"flag_lu": "🇱🇺",
	"flag_mo": "🇲🇴",
	"flag_mk": "🇲🇰",
	"flag_mg": "🇲🇬",
	"flag_mw": "🇲🇼",
	"flag_my": "🇲🇾",
	"flag_mv": "🇲🇻",
	"flag_ml": "🇲🇱",
	"flag_mt": "🇲🇹",
	"flag_mh": "🇲🇭",
	"flag_mr": "🇲🇷",
	"flag_mu": "🇲🇺",
	"flag_mx": "🇲🇽",
	"flag_fm": "🇫🇲",
	"flag_md": "🇲🇩",
	"flag_mc": "🇲🇨",
	"flag_mn": "🇲🇳",
	"flag_me": "🇲🇪",
	"flag_ms": "🇲🇸",
	"flag_ma": "🇲🇦",
	"flag_mz": "🇲🇿",
	"flag_mm": "🇲🇲",
	"flag_na": "🇳🇦",
	"flag_nr": "🇳🇷",
	"flag_np": "🇳🇵",
	"flag_nl": "🇳🇱",
	"flag_nc": "🇳🇨",
	"flag_nz": "🇳🇿",
	"flag_ni": "🇳🇮",
	"flag_ne": "🇳🇪",
	"flag_ng": "🇳🇬",
	"flag_nu": "🇳🇺",
	"flag_kp": "🇰🇵",
	"flag_no": "🇳🇴",
	"flag_om": "🇴🇲",
	"flag_pk": "🇵🇰",
	"flag_pw": "🇵🇼",
	"flag_ps": "🇵🇸",
	"flag_pa": "🇵🇦",
	"flag_pg": "🇵🇬",
	"flag_py": "🇵🇾",
	"flag_pe": "🇵🇪",
	"flag_ph": "🇵🇭",
	"flag_pl": "🇵🇱",
	"flag_pt": "🇵🇹",
	"flag_pr": "🇵🇷",
	"flag_qa": "🇶🇦",
	"flag_ro": "🇷🇴",
	"flag_ru": "🇷🇺",
	"flag_rw": "🇷🇼",
	"flag_sh": "🇸🇭",
	"flag_kn": "🇰🇳",
	"flag_lc": "🇱🇨",
	"flag_vc": "🇻🇨",
	"flag_ws": "🇼🇸",
	"flag_sm": "🇸🇲",
	"flag_st": "🇸🇹",
	"flag_sa": "🇸🇦",
	"flag_sn": "🇸🇳",
	"flag_rs": "🇷🇸",
	"flag_sc": "🇸🇨",
	"flag_sl": "🇸🇱",
	"flag_sg": "🇸🇬",
	"flag_sk": "🇸🇰",
	"flag_si": "🇸🇮",
	"flag_sb": "🇸🇧",
	"flag_so": "🇸🇴",
	"flag_za": "🇿🇦",
	"flag_kr": "🇰🇷",
	"flag_es": "🇪🇸",
	"flag_lk": "🇱🇰",
	"flag_sd": "🇸🇩",
	"flag_sr": "🇸🇷",
	"flag_sz": "🇸🇿",
	"flag_se": "🇸🇪",
	"flag_ch": "🇨🇭",
	"flag_sy": "🇸🇾",
	"flag_tw": "🇹🇼",
	"flag_tj": "🇹🇯",
	"flag_tz": "🇹🇿",
	"flag_th": "🇹🇭",
	"flag_tl": "🇹🇱",
	"flag_tg": "🇹🇬",
	"flag_to": "🇹🇴",
	"flag_tt": "🇹🇹",
	"flag_tn": "🇹🇳",
	"flag_tr": "🇹🇷",
	"flag_tm": "🇹🇲",
	"flag_tv": "🇹🇻",
	"flag_ug": "🇺🇬",
	"flag_ua": "🇺🇦",
	"flag_ae": "🇦🇪",
	"flag_gb": "🇬🇧",
	"flag_us": "🇺🇸",
	"flag_vi": "🇻🇮",
	"flag_uy": "🇺🇾",
	"flag_uz": "🇺🇿",
	"flag_vu": "🇻🇺",
	"flag_va": "🇻🇦",
	"flag_ve": "🇻🇪",
	"flag_vn": "🇻🇳",
	"flag_wf": "🇼🇫",
	"flag_eh": "🇪🇭",
	"flag_ye": "🇾🇪",
	"flag_zm": "🇿🇲",
	"flag_zw": "🇿🇼",
	"flag_re": "🇷🇪",
	"flag_ax": "🇦🇽",
	"flag_ta": "🇹🇦",
	"flag_io": "🇮🇴",
	"flag_bq": "🇧🇶",
	"flag_cx": "🇨🇽",
	"flag_cc": "🇨🇨",
	"flag_gg": "🇬🇬",
	"flag_im": "🇮🇲",
	"flag_yt": "🇾🇹",
	"flag_nf": "🇳🇫",
	"flag_pn": "🇵🇳",
	"flag_bl": "🇧🇱",
	"flag_pm": "🇵🇲",
	"flag_gs": "🇬🇸",
	"flag_tk": "🇹🇰",
	"flag_bv": "🇧🇻",
	"flag_hm": "🇭🇲",
	"flag_sj": "🇸🇯",
	"flag_um": "🇺🇲",
	"flag_ic": "🇮🇨",
	"flag_ea": "🇪🇦",
	"flag_cp": "🇨🇵",
	"flag_dg": "🇩🇬",
	"flag_as": "🇦🇸",
	"flag_aq": "🇦🇶",
	"flag_vg": "🇻🇬",
	"flag_ck": "🇨🇰",
	"flag_cw": "🇨🇼",
	"flag_eu": "🇪🇺",
	"flag_gf": "🇬🇫",
	"flag_tf": "🇹🇫",
	"flag_gp": "🇬🇵",
	"flag_mq": "🇲🇶",
	"flag_mp": "🇲🇵",
	"flag_sx": "🇸🇽",
	"flag_ss": "🇸🇸",
	"flag_tc": "🇹🇨",
	"flag_mf": "🇲🇫",
	"gay_pride_flag": "🏳️‍🌈",
	"rainbow_flag": "🏳️‍🌈"
}

// List of smileys shortcuts
smileys.shorcuts = {
	"&gt;:(": ":angry:",
	"&gt;:-(": ":angry:",
	"&gt;=(": ":angry:",
	"&gt;=-(": ":angry:",
	":\")": ":blush:",
	":-\")": ":blush:",
	"=\")": ":blush:",
	"=-\")": ":blush:",
	"&lt;/3": ":broken_heart:",
	"&lt;\\3": ":broken_heart:",
	":\\": ":/",
	":-\\": ":/",
	":-/": ":/",
	"=-\\": ":/",
	"=-/": ":/",
	":&#39;(": ":cry:",
	":&#39;-(": ":cry:",
	":,(": ":cry:",
	":,-(": ":cry:",
	"=&#39;(": ":cry:",
	"=&#39;-(": ":cry:",
	"=,(": ":cry:",
	"=,-(": ":cry:",
	":-(": ":(",
	"=(": ":(",
	"=-(": ":(",
	":b": ":B",
	"&lt;3": "<3",
	"(l)": "<3",
	"(L)": "<3",
	"]:(": ":imp:",
	"]:-(": ":imp:",
	"]=(": ":imp:",
	"]=-(": ":imp:",
	"o:)": ":innocent:",
	"O:)": ":innocent:",
	"o:-)": ":innocent:",
	"O:-)": ":innocent:",
	"0:)": ":innocent:",
	"0:-)": ":innocent:",
	"o=)": ":innocent:",
	"O=)": ":innocent:",
	"o=-)": ":innocent:",
	"O=-)": ":innocent:",
	"0=)": ":innocent:",
	"0=-)": ":innocent:",
	":&#39;)": ":joy:",
	":&#39;-)": ":joy:",
	":,)": ":joy:",
	":,-)": ":joy:",
	":&#39;D": ":joy:",
	":&#39;-D": ":joy:",
	":,D": ":joy:",
	":,-D": ":joy:",
	"=&#39;)": ":joy:",
	"=&#39;-)": ":joy:",
	"=,)": ":joy:",
	"=,-)": ":joy:",
	"=&#39;D": ":joy:",
	"=&#39;-D": ":joy:",
	"=,D": ":joy:",
	"=,-D": ":joy:",
	":*": ":kissing:",
	":-*": ":kissing:",
	"=*": ":kissing:",
	"=-*": ":kissing:",
	"x-)": ":laughing:",
	"X-)": ":laughing:",
	":|": ":neutral_face:",
	":-|": ":neutral_face:",
	"=|": ":neutral_face:",
	"=-|": ":neutral_face:",
	":o": ":O",
	":-o": ":O",
	":-O": ":O",
	"=o": ":O",
	"=-o": ":O",
	"=O": ":O",
	"=-O": ":O",
	":@": ":rage:",
	":-@": ":rage:",
	"=@": ":rage:",
	"=-@": ":rage:",
	":-D": ":D",
	"=D": ":D",
	"=-D": ":D",
	":-)": ":)",
	"=)": ":)",
	"=-)": ":)",
	":]": ":)",
	":-]": ":)",
	"=]": ":)",
	"=-]": ":)",
	"]:)": ":smiling_imp:",
	"]:-)": ":smiling_imp:",
	"]=)": ":smiling_imp:",
	"]=-)": ":smiling_imp:",
	":,&#39;(": ":sob:",
	":,&#39;-(": ":sob:",
	";(": ":sob:",
	";-(": ":sob:",
	"=,&#39;(": ":sob:",
	"=,&#39;-(": ":sob:",
	":-P": ":P",
	"=P": ":P",
	"=-P": ":P",
	":p": ":P",
	":-p": ":P",
	"=p": ":P",
	"=-p": ":P",
	"8-)": ":sunglasses:",
	"B-)": ":sunglasses:",
	",:(": ":sweat:",
	",:-(": ":sweat:",
	",=(": ":sweat:",
	",=-(": ":sweat:",
	",:)": ":sweat_smile:",
	",:-)": ":sweat_smile:",
	",=)": ":sweat_smile:",
	",=-)": ":sweat_smile:",
	":s": ":unamused:",
	":-S": ":unamused:",
	":z": ":unamused:",
	":-Z": ":unamused:",
	":$": ":unamused:",
	":-$": ":unamused:",
	"=s": ":unamused:",
	"=-S": ":unamused:",
	"=z": ":unamused:",
	"=-Z": ":unamused:",
	"=$": ":unamused:",
	"=-$": ":unamused:",
	";-)": ";)"
}

// List of custom smileys
smileys.custom = {
	":O": {
		"name": ":O",
		"image": "open_mouth"
	},
	":D": {
		"name": ":D",
		"image": "grinning"
	},
	"<3": {
		"name": "<3",
		"image": "heart"
	},
	":)": {
		"name": ":)",
		"image": "smile"
	},
	":/": {
		"name": ":/",
		"image": "confused"
	},
	";)": {
		"name": ";)",
		"image": "wink"
	},
	":(": {
		"name": ":(",
		"image": "frowning"
	},
	":P": {
		"name": ":P",
		"image": "stuck_out_tongue"
	},
	"(lama)": {
		"name": "(lama)",
		"image": "lama"
	},
	":B": {
		"name": ":B",
		"image": "grimacing"
	},
	"(lucky)": {
		"name": "(lucky)",
		"image": "clover"
	}
}
